#!/usr/bin/env python3
"""
Add gamification i18n keys to all 18 language blocks in i18n.ts.
Inserts after 'diet.empty' (last existing key) in each language block.
"""

import re

FILE = 'facesyma_mobile/src/utils/i18n.ts'

# Keys for each language (in insertion order)
ALL_KEYS = {
    'tr': [
        ("gamification.title", "Oyunlaştırma"),
        ("gamification.coins", "Coinlerim"),
        ("gamification.leaderboard", "Sıralama Tablosu"),
        ("gamification.badges", "Rozetler"),
        ("gamification.challenges", "Meydan Okumalar"),
        ("gamification.missions", "Görevler"),
        ("gamification.meal_game", "Yemek Oyunu"),
        ("gamification.discovery", "Keşif Oyunları"),
        ("coin.balance", "Coin Bakiyesi"),
        ("coin.history", "İşlem Geçmişi"),
        ("coin.daily_quest", "Günlük Görev"),
        ("coin.total_earned", "Toplam Kazanılan"),
        ("coin.streak", "Günlük Seri"),
        ("coin.claim", "Günlük Görevi Al"),
        ("coin.claimed", "Bugün alındı ✓"),
        ("coin.empty", "Henüz işlem yok"),
        ("coin.earned", "kazanıldı"),
        ("coin.spent", "harcandı"),
        ("leaderboard.title", "Sıralama Tablosu"),
        ("leaderboard.global", "Küresel"),
        ("leaderboard.trending", "Yükselen"),
        ("leaderboard.rank", "Sıra"),
        ("leaderboard.my_rank", "Benim Sıram"),
        ("leaderboard.empty", "Henüz sıralama verisi yok"),
        ("leaderboard.coins", "Coin"),
        ("badge.title", "Rozetlerim"),
        ("badge.all_badges", "Tüm Rozetler"),
        ("badge.locked", "Kilitli"),
        ("badge.bronze", "Bronz"),
        ("badge.silver", "Gümüş"),
        ("badge.gold", "Altın"),
        ("badge.platinum", "Platin"),
        ("badge.progress", "İlerleme"),
        ("badge.empty", "Henüz rozet kazanılmadı"),
        ("challenge.title", "Meydan Okumalar"),
        ("challenge.join", "Katıl"),
        ("challenge.active", "Aktif"),
        ("challenge.empty", "Aktif meydan okuma yok"),
        ("challenge.score", "Puan"),
        ("meal_game.title", "Yemek Oyunu"),
        ("meal_game.week_country", "Bu Haftanın Mutfağı"),
        ("meal_game.select_meal", "Yemek Seç"),
        ("meal_game.guess_match", "Kişiliğine uyuyor mu?"),
        ("meal_game.yes", "Evet, Uyuyor! 🎯"),
        ("meal_game.no", "Hayır, Uymuyor 😅"),
        ("meal_game.unsure", "Emin Değilim 🤔"),
        ("meal_game.correct", "✓ Doğru!"),
        ("meal_game.wrong", "✗ Yanlış"),
        ("meal_game.earned", "coin kazandın!"),
        ("meal_game.leaderboard", "Haftalık Sıralama"),
        ("meal_game.history", "Yemek Geçmişi"),
        ("meal_game.empty", "Bugün seçim yapılmadı"),
        ("discovery.title", "Keşif Oyunları"),
        ("discovery.trait_discovery", "Sıfat Keşfi"),
        ("discovery.sifat_learning", "Sıfat Öğrenme"),
        ("discovery.face_quiz", "Yüz Testi"),
        ("discovery.start", "Oyunu Başlat"),
        ("discovery.correct", "✓ Doğru!"),
        ("discovery.wrong", "✗ Yanlış"),
        ("discovery.score", "Puan"),
        ("discovery.finish", "Oyun Bitti!"),
        ("discovery.next_question", "Sonraki Soru"),
    ],
    'en': [
        ("gamification.title", "Gamification"),
        ("gamification.coins", "My Coins"),
        ("gamification.leaderboard", "Leaderboard"),
        ("gamification.badges", "Badges"),
        ("gamification.challenges", "Challenges"),
        ("gamification.missions", "Missions"),
        ("gamification.meal_game", "Meal Game"),
        ("gamification.discovery", "Discovery Games"),
        ("coin.balance", "Coin Balance"),
        ("coin.history", "Transaction History"),
        ("coin.daily_quest", "Daily Quest"),
        ("coin.total_earned", "Total Earned"),
        ("coin.streak", "Day Streak"),
        ("coin.claim", "Claim Daily Quest"),
        ("coin.claimed", "Claimed today ✓"),
        ("coin.empty", "No transactions yet"),
        ("coin.earned", "earned"),
        ("coin.spent", "spent"),
        ("leaderboard.title", "Leaderboard"),
        ("leaderboard.global", "Global"),
        ("leaderboard.trending", "Trending"),
        ("leaderboard.rank", "Rank"),
        ("leaderboard.my_rank", "My Rank"),
        ("leaderboard.empty", "No leaderboard data yet"),
        ("leaderboard.coins", "Coins"),
        ("badge.title", "My Badges"),
        ("badge.all_badges", "All Badges"),
        ("badge.locked", "Locked"),
        ("badge.bronze", "Bronze"),
        ("badge.silver", "Silver"),
        ("badge.gold", "Gold"),
        ("badge.platinum", "Platinum"),
        ("badge.progress", "Progress"),
        ("badge.empty", "No badges earned yet"),
        ("challenge.title", "Challenges"),
        ("challenge.join", "Join"),
        ("challenge.active", "Active"),
        ("challenge.empty", "No active challenges"),
        ("challenge.score", "Score"),
        ("meal_game.title", "Meal Game"),
        ("meal_game.week_country", "This Week's Cuisine"),
        ("meal_game.select_meal", "Select Meal"),
        ("meal_game.guess_match", "Does it match your personality?"),
        ("meal_game.yes", "Yes, It Matches! 🎯"),
        ("meal_game.no", "No, Doesn't Match 😅"),
        ("meal_game.unsure", "Not Sure 🤔"),
        ("meal_game.correct", "✓ Correct!"),
        ("meal_game.wrong", "✗ Wrong"),
        ("meal_game.earned", "coins earned!"),
        ("meal_game.leaderboard", "Weekly Leaderboard"),
        ("meal_game.history", "Meal History"),
        ("meal_game.empty", "No selections today"),
        ("discovery.title", "Discovery Games"),
        ("discovery.trait_discovery", "Trait Discovery"),
        ("discovery.sifat_learning", "Sifat Learning"),
        ("discovery.face_quiz", "Face Quiz"),
        ("discovery.start", "Start Game"),
        ("discovery.correct", "✓ Correct!"),
        ("discovery.wrong", "✗ Wrong"),
        ("discovery.score", "Score"),
        ("discovery.finish", "Game Over!"),
        ("discovery.next_question", "Next Question"),
    ],
    'de': [
        ("gamification.title", "Gamification"),
        ("gamification.coins", "Meine Coins"),
        ("gamification.leaderboard", "Rangliste"),
        ("gamification.badges", "Abzeichen"),
        ("gamification.challenges", "Herausforderungen"),
        ("gamification.missions", "Missionen"),
        ("gamification.meal_game", "Mahlzeitenspiel"),
        ("gamification.discovery", "Entdeckungsspiele"),
        ("coin.balance", "Coin-Guthaben"),
        ("coin.history", "Transaktionshistorie"),
        ("coin.daily_quest", "Tägliche Quest"),
        ("coin.total_earned", "Gesamt verdient"),
        ("coin.streak", "Tages-Serie"),
        ("coin.claim", "Tägliche Quest abholen"),
        ("coin.claimed", "Heute abgeholt ✓"),
        ("coin.empty", "Noch keine Transaktionen"),
        ("coin.earned", "verdient"),
        ("coin.spent", "ausgegeben"),
        ("leaderboard.title", "Rangliste"),
        ("leaderboard.global", "Global"),
        ("leaderboard.trending", "Im Aufstieg"),
        ("leaderboard.rank", "Rang"),
        ("leaderboard.my_rank", "Mein Rang"),
        ("leaderboard.empty", "Noch keine Rangliste"),
        ("leaderboard.coins", "Coins"),
        ("badge.title", "Meine Abzeichen"),
        ("badge.all_badges", "Alle Abzeichen"),
        ("badge.locked", "Gesperrt"),
        ("badge.bronze", "Bronze"),
        ("badge.silver", "Silber"),
        ("badge.gold", "Gold"),
        ("badge.platinum", "Platin"),
        ("badge.progress", "Fortschritt"),
        ("badge.empty", "Noch keine Abzeichen"),
        ("challenge.title", "Herausforderungen"),
        ("challenge.join", "Beitreten"),
        ("challenge.active", "Aktiv"),
        ("challenge.empty", "Keine aktiven Herausforderungen"),
        ("challenge.score", "Punkte"),
        ("meal_game.title", "Mahlzeitenspiel"),
        ("meal_game.week_country", "Küche dieser Woche"),
        ("meal_game.select_meal", "Mahlzeit auswählen"),
        ("meal_game.guess_match", "Passt es zu deiner Persönlichkeit?"),
        ("meal_game.yes", "Ja, passt! 🎯"),
        ("meal_game.no", "Nein, passt nicht 😅"),
        ("meal_game.unsure", "Nicht sicher 🤔"),
        ("meal_game.correct", "✓ Richtig!"),
        ("meal_game.wrong", "✗ Falsch"),
        ("meal_game.earned", "Coins verdient!"),
        ("meal_game.leaderboard", "Wochenrangliste"),
        ("meal_game.history", "Mahlzeitenhistorie"),
        ("meal_game.empty", "Heute noch keine Auswahl"),
        ("discovery.title", "Entdeckungsspiele"),
        ("discovery.trait_discovery", "Merkmal-Entdeckung"),
        ("discovery.sifat_learning", "Sifat-Lernen"),
        ("discovery.face_quiz", "Gesichtsquiz"),
        ("discovery.start", "Spiel starten"),
        ("discovery.correct", "✓ Richtig!"),
        ("discovery.wrong", "✗ Falsch"),
        ("discovery.score", "Punkte"),
        ("discovery.finish", "Spiel vorbei!"),
        ("discovery.next_question", "Nächste Frage"),
    ],
    'ru': [
        ("gamification.title", "Геймификация"),
        ("gamification.coins", "Мои монеты"),
        ("gamification.leaderboard", "Рейтинг"),
        ("gamification.badges", "Значки"),
        ("gamification.challenges", "Испытания"),
        ("gamification.missions", "Миссии"),
        ("gamification.meal_game", "Игра с едой"),
        ("gamification.discovery", "Игры открытий"),
        ("coin.balance", "Баланс монет"),
        ("coin.history", "История транзакций"),
        ("coin.daily_quest", "Ежедневное задание"),
        ("coin.total_earned", "Всего заработано"),
        ("coin.streak", "Серия дней"),
        ("coin.claim", "Получить задание"),
        ("coin.claimed", "Получено сегодня ✓"),
        ("coin.empty", "Нет транзакций"),
        ("coin.earned", "заработано"),
        ("coin.spent", "потрачено"),
        ("leaderboard.title", "Таблица лидеров"),
        ("leaderboard.global", "Глобальный"),
        ("leaderboard.trending", "В тренде"),
        ("leaderboard.rank", "Место"),
        ("leaderboard.my_rank", "Моё место"),
        ("leaderboard.empty", "Нет данных рейтинга"),
        ("leaderboard.coins", "Монеты"),
        ("badge.title", "Мои значки"),
        ("badge.all_badges", "Все значки"),
        ("badge.locked", "Заблокировано"),
        ("badge.bronze", "Бронза"),
        ("badge.silver", "Серебро"),
        ("badge.gold", "Золото"),
        ("badge.platinum", "Платина"),
        ("badge.progress", "Прогресс"),
        ("badge.empty", "Значки ещё не получены"),
        ("challenge.title", "Испытания"),
        ("challenge.join", "Участвовать"),
        ("challenge.active", "Активные"),
        ("challenge.empty", "Нет активных испытаний"),
        ("challenge.score", "Очки"),
        ("meal_game.title", "Игра с едой"),
        ("meal_game.week_country", "Кухня этой недели"),
        ("meal_game.select_meal", "Выбрать блюдо"),
        ("meal_game.guess_match", "Подходит вашей личности?"),
        ("meal_game.yes", "Да, подходит! 🎯"),
        ("meal_game.no", "Нет, не подходит 😅"),
        ("meal_game.unsure", "Не уверен 🤔"),
        ("meal_game.correct", "✓ Верно!"),
        ("meal_game.wrong", "✗ Неверно"),
        ("meal_game.earned", "монет заработано!"),
        ("meal_game.leaderboard", "Недельный рейтинг"),
        ("meal_game.history", "История блюд"),
        ("meal_game.empty", "Сегодня нет выборов"),
        ("discovery.title", "Игры открытий"),
        ("discovery.trait_discovery", "Открытие черт"),
        ("discovery.sifat_learning", "Изучение сыфат"),
        ("discovery.face_quiz", "Тест лица"),
        ("discovery.start", "Начать игру"),
        ("discovery.correct", "✓ Верно!"),
        ("discovery.wrong", "✗ Неверно"),
        ("discovery.score", "Очки"),
        ("discovery.finish", "Игра окончена!"),
        ("discovery.next_question", "Следующий вопрос"),
    ],
    'ar': [
        ("gamification.title", "الألعاب"),
        ("gamification.coins", "عملاتي"),
        ("gamification.leaderboard", "لوحة المتصدرين"),
        ("gamification.badges", "الشارات"),
        ("gamification.challenges", "التحديات"),
        ("gamification.missions", "المهام"),
        ("gamification.meal_game", "لعبة الطعام"),
        ("gamification.discovery", "ألعاب الاكتشاف"),
        ("coin.balance", "رصيد العملات"),
        ("coin.history", "سجل المعاملات"),
        ("coin.daily_quest", "المهمة اليومية"),
        ("coin.total_earned", "إجمالي المكسوب"),
        ("coin.streak", "سلسلة الأيام"),
        ("coin.claim", "احصل على المهمة اليومية"),
        ("coin.claimed", "تم الاستلام اليوم ✓"),
        ("coin.empty", "لا توجد معاملات"),
        ("coin.earned", "مكسوب"),
        ("coin.spent", "مُنفق"),
        ("leaderboard.title", "لوحة المتصدرين"),
        ("leaderboard.global", "عالمي"),
        ("leaderboard.trending", "صاعد"),
        ("leaderboard.rank", "المركز"),
        ("leaderboard.my_rank", "مركزي"),
        ("leaderboard.empty", "لا توجد بيانات بعد"),
        ("leaderboard.coins", "عملات"),
        ("badge.title", "شاراتي"),
        ("badge.all_badges", "كل الشارات"),
        ("badge.locked", "مقفل"),
        ("badge.bronze", "برونز"),
        ("badge.silver", "فضة"),
        ("badge.gold", "ذهب"),
        ("badge.platinum", "بلاتين"),
        ("badge.progress", "التقدم"),
        ("badge.empty", "لم تُكسب شارات بعد"),
        ("challenge.title", "التحديات"),
        ("challenge.join", "انضم"),
        ("challenge.active", "نشط"),
        ("challenge.empty", "لا توجد تحديات نشطة"),
        ("challenge.score", "النقاط"),
        ("meal_game.title", "لعبة الطعام"),
        ("meal_game.week_country", "مطبخ هذا الأسبوع"),
        ("meal_game.select_meal", "اختر وجبة"),
        ("meal_game.guess_match", "هل يناسب شخصيتك؟"),
        ("meal_game.yes", "نعم، يناسب! 🎯"),
        ("meal_game.no", "لا، لا يناسب 😅"),
        ("meal_game.unsure", "غير متأكد 🤔"),
        ("meal_game.correct", "✓ صحيح!"),
        ("meal_game.wrong", "✗ خطأ"),
        ("meal_game.earned", "عملات مكتسبة!"),
        ("meal_game.leaderboard", "ترتيب الأسبوع"),
        ("meal_game.history", "سجل الوجبات"),
        ("meal_game.empty", "لا اختيارات اليوم"),
        ("discovery.title", "ألعاب الاكتشاف"),
        ("discovery.trait_discovery", "اكتشاف الصفات"),
        ("discovery.sifat_learning", "تعلم الصفات"),
        ("discovery.face_quiz", "اختبار الوجه"),
        ("discovery.start", "ابدأ اللعبة"),
        ("discovery.correct", "✓ صحيح!"),
        ("discovery.wrong", "✗ خطأ"),
        ("discovery.score", "النقاط"),
        ("discovery.finish", "انتهت اللعبة!"),
        ("discovery.next_question", "السؤال التالي"),
    ],
    'es': [
        ("gamification.title", "Gamificación"),
        ("gamification.coins", "Mis Monedas"),
        ("gamification.leaderboard", "Clasificación"),
        ("gamification.badges", "Insignias"),
        ("gamification.challenges", "Desafíos"),
        ("gamification.missions", "Misiones"),
        ("gamification.meal_game", "Juego de Comidas"),
        ("gamification.discovery", "Juegos de Descubrimiento"),
        ("coin.balance", "Saldo de Monedas"),
        ("coin.history", "Historial de Transacciones"),
        ("coin.daily_quest", "Misión Diaria"),
        ("coin.total_earned", "Total Ganado"),
        ("coin.streak", "Racha de Días"),
        ("coin.claim", "Reclamar Misión Diaria"),
        ("coin.claimed", "Reclamado hoy ✓"),
        ("coin.empty", "Sin transacciones aún"),
        ("coin.earned", "ganado"),
        ("coin.spent", "gastado"),
        ("leaderboard.title", "Clasificación"),
        ("leaderboard.global", "Global"),
        ("leaderboard.trending", "Tendencia"),
        ("leaderboard.rank", "Rango"),
        ("leaderboard.my_rank", "Mi Rango"),
        ("leaderboard.empty", "Sin datos de clasificación"),
        ("leaderboard.coins", "Monedas"),
        ("badge.title", "Mis Insignias"),
        ("badge.all_badges", "Todas las Insignias"),
        ("badge.locked", "Bloqueado"),
        ("badge.bronze", "Bronce"),
        ("badge.silver", "Plata"),
        ("badge.gold", "Oro"),
        ("badge.platinum", "Platino"),
        ("badge.progress", "Progreso"),
        ("badge.empty", "Sin insignias aún"),
        ("challenge.title", "Desafíos"),
        ("challenge.join", "Unirse"),
        ("challenge.active", "Activo"),
        ("challenge.empty", "Sin desafíos activos"),
        ("challenge.score", "Puntuación"),
        ("meal_game.title", "Juego de Comidas"),
        ("meal_game.week_country", "Cocina de Esta Semana"),
        ("meal_game.select_meal", "Seleccionar Comida"),
        ("meal_game.guess_match", "¿Coincide con tu personalidad?"),
        ("meal_game.yes", "¡Sí, coincide! 🎯"),
        ("meal_game.no", "No, no coincide 😅"),
        ("meal_game.unsure", "No estoy seguro 🤔"),
        ("meal_game.correct", "✓ ¡Correcto!"),
        ("meal_game.wrong", "✗ Incorrecto"),
        ("meal_game.earned", "monedas ganadas!"),
        ("meal_game.leaderboard", "Clasificación Semanal"),
        ("meal_game.history", "Historial de Comidas"),
        ("meal_game.empty", "Sin selecciones hoy"),
        ("discovery.title", "Juegos de Descubrimiento"),
        ("discovery.trait_discovery", "Descubrimiento de Rasgos"),
        ("discovery.sifat_learning", "Aprendizaje Sifat"),
        ("discovery.face_quiz", "Quiz Facial"),
        ("discovery.start", "Iniciar Juego"),
        ("discovery.correct", "✓ ¡Correcto!"),
        ("discovery.wrong", "✗ Incorrecto"),
        ("discovery.score", "Puntuación"),
        ("discovery.finish", "¡Juego terminado!"),
        ("discovery.next_question", "Siguiente Pregunta"),
    ],
    'ko': [
        ("gamification.title", "게임화"),
        ("gamification.coins", "내 코인"),
        ("gamification.leaderboard", "순위표"),
        ("gamification.badges", "배지"),
        ("gamification.challenges", "도전"),
        ("gamification.missions", "임무"),
        ("gamification.meal_game", "식사 게임"),
        ("gamification.discovery", "발견 게임"),
        ("coin.balance", "코인 잔액"),
        ("coin.history", "거래 내역"),
        ("coin.daily_quest", "일일 퀘스트"),
        ("coin.total_earned", "총 획득"),
        ("coin.streak", "연속 일수"),
        ("coin.claim", "일일 퀘스트 수령"),
        ("coin.claimed", "오늘 수령 완료 ✓"),
        ("coin.empty", "거래 내역 없음"),
        ("coin.earned", "획득"),
        ("coin.spent", "사용"),
        ("leaderboard.title", "순위표"),
        ("leaderboard.global", "전체"),
        ("leaderboard.trending", "상승 중"),
        ("leaderboard.rank", "순위"),
        ("leaderboard.my_rank", "내 순위"),
        ("leaderboard.empty", "순위 데이터 없음"),
        ("leaderboard.coins", "코인"),
        ("badge.title", "내 배지"),
        ("badge.all_badges", "모든 배지"),
        ("badge.locked", "잠김"),
        ("badge.bronze", "브론즈"),
        ("badge.silver", "실버"),
        ("badge.gold", "골드"),
        ("badge.platinum", "플래티넘"),
        ("badge.progress", "진행"),
        ("badge.empty", "아직 배지 없음"),
        ("challenge.title", "도전"),
        ("challenge.join", "참가"),
        ("challenge.active", "활성"),
        ("challenge.empty", "활성 도전 없음"),
        ("challenge.score", "점수"),
        ("meal_game.title", "식사 게임"),
        ("meal_game.week_country", "이번 주 요리"),
        ("meal_game.select_meal", "식사 선택"),
        ("meal_game.guess_match", "당신의 성격과 맞나요?"),
        ("meal_game.yes", "네, 맞아요! 🎯"),
        ("meal_game.no", "아니요, 안 맞아요 😅"),
        ("meal_game.unsure", "모르겠어요 🤔"),
        ("meal_game.correct", "✓ 정답!"),
        ("meal_game.wrong", "✗ 오답"),
        ("meal_game.earned", "코인 획득!"),
        ("meal_game.leaderboard", "주간 순위"),
        ("meal_game.history", "식사 기록"),
        ("meal_game.empty", "오늘 선택 없음"),
        ("discovery.title", "발견 게임"),
        ("discovery.trait_discovery", "특성 발견"),
        ("discovery.sifat_learning", "시파트 학습"),
        ("discovery.face_quiz", "얼굴 퀴즈"),
        ("discovery.start", "게임 시작"),
        ("discovery.correct", "✓ 정답!"),
        ("discovery.wrong", "✗ 오답"),
        ("discovery.score", "점수"),
        ("discovery.finish", "게임 종료!"),
        ("discovery.next_question", "다음 질문"),
    ],
    'ja': [
        ("gamification.title", "ゲーミフィケーション"),
        ("gamification.coins", "マイコイン"),
        ("gamification.leaderboard", "ランキング"),
        ("gamification.badges", "バッジ"),
        ("gamification.challenges", "チャレンジ"),
        ("gamification.missions", "ミッション"),
        ("gamification.meal_game", "食事ゲーム"),
        ("gamification.discovery", "ディスカバリーゲーム"),
        ("coin.balance", "コイン残高"),
        ("coin.history", "取引履歴"),
        ("coin.daily_quest", "デイリークエスト"),
        ("coin.total_earned", "総獲得数"),
        ("coin.streak", "連続日数"),
        ("coin.claim", "デイリークエストを受け取る"),
        ("coin.claimed", "本日受取済み ✓"),
        ("coin.empty", "取引履歴なし"),
        ("coin.earned", "獲得"),
        ("coin.spent", "使用"),
        ("leaderboard.title", "ランキング"),
        ("leaderboard.global", "グローバル"),
        ("leaderboard.trending", "上昇中"),
        ("leaderboard.rank", "順位"),
        ("leaderboard.my_rank", "自分の順位"),
        ("leaderboard.empty", "ランキングデータなし"),
        ("leaderboard.coins", "コイン"),
        ("badge.title", "マイバッジ"),
        ("badge.all_badges", "全バッジ"),
        ("badge.locked", "ロック中"),
        ("badge.bronze", "ブロンズ"),
        ("badge.silver", "シルバー"),
        ("badge.gold", "ゴールド"),
        ("badge.platinum", "プラチナ"),
        ("badge.progress", "進捗"),
        ("badge.empty", "バッジなし"),
        ("challenge.title", "チャレンジ"),
        ("challenge.join", "参加"),
        ("challenge.active", "アクティブ"),
        ("challenge.empty", "アクティブなチャレンジなし"),
        ("challenge.score", "スコア"),
        ("meal_game.title", "食事ゲーム"),
        ("meal_game.week_country", "今週の料理"),
        ("meal_game.select_meal", "食事を選ぶ"),
        ("meal_game.guess_match", "あなたの性格に合いますか？"),
        ("meal_game.yes", "はい、合います！🎯"),
        ("meal_game.no", "いいえ、合いません😅"),
        ("meal_game.unsure", "わかりません🤔"),
        ("meal_game.correct", "✓ 正解！"),
        ("meal_game.wrong", "✗ 不正解"),
        ("meal_game.earned", "コイン獲得！"),
        ("meal_game.leaderboard", "週間ランキング"),
        ("meal_game.history", "食事履歴"),
        ("meal_game.empty", "今日の選択なし"),
        ("discovery.title", "ディスカバリーゲーム"),
        ("discovery.trait_discovery", "特性発見"),
        ("discovery.sifat_learning", "スィファット学習"),
        ("discovery.face_quiz", "顔クイズ"),
        ("discovery.start", "ゲームを始める"),
        ("discovery.correct", "✓ 正解！"),
        ("discovery.wrong", "✗ 不正解"),
        ("discovery.score", "スコア"),
        ("discovery.finish", "ゲーム終了！"),
        ("discovery.next_question", "次の質問"),
    ],
    'zh': [
        ("gamification.title", "游戏化"),
        ("gamification.coins", "我的金币"),
        ("gamification.leaderboard", "排行榜"),
        ("gamification.badges", "徽章"),
        ("gamification.challenges", "挑战"),
        ("gamification.missions", "任务"),
        ("gamification.meal_game", "饮食游戏"),
        ("gamification.discovery", "探索游戏"),
        ("coin.balance", "金币余额"),
        ("coin.history", "交易记录"),
        ("coin.daily_quest", "每日任务"),
        ("coin.total_earned", "总获得"),
        ("coin.streak", "连续天数"),
        ("coin.claim", "领取每日任务"),
        ("coin.claimed", "今日已领取 ✓"),
        ("coin.empty", "暂无交易记录"),
        ("coin.earned", "已获得"),
        ("coin.spent", "已消耗"),
        ("leaderboard.title", "排行榜"),
        ("leaderboard.global", "全球"),
        ("leaderboard.trending", "上升中"),
        ("leaderboard.rank", "排名"),
        ("leaderboard.my_rank", "我的排名"),
        ("leaderboard.empty", "暂无排行数据"),
        ("leaderboard.coins", "金币"),
        ("badge.title", "我的徽章"),
        ("badge.all_badges", "所有徽章"),
        ("badge.locked", "已锁定"),
        ("badge.bronze", "铜牌"),
        ("badge.silver", "银牌"),
        ("badge.gold", "金牌"),
        ("badge.platinum", "铂金"),
        ("badge.progress", "进度"),
        ("badge.empty", "暂无徽章"),
        ("challenge.title", "挑战"),
        ("challenge.join", "加入"),
        ("challenge.active", "活跃"),
        ("challenge.empty", "暂无活跃挑战"),
        ("challenge.score", "分数"),
        ("meal_game.title", "饮食游戏"),
        ("meal_game.week_country", "本周菜系"),
        ("meal_game.select_meal", "选择食物"),
        ("meal_game.guess_match", "符合你的个性吗？"),
        ("meal_game.yes", "是的，符合！🎯"),
        ("meal_game.no", "不，不符合😅"),
        ("meal_game.unsure", "不确定🤔"),
        ("meal_game.correct", "✓ 正确！"),
        ("meal_game.wrong", "✗ 错误"),
        ("meal_game.earned", "金币已获得！"),
        ("meal_game.leaderboard", "每周排行"),
        ("meal_game.history", "饮食记录"),
        ("meal_game.empty", "今日无选择"),
        ("discovery.title", "探索游戏"),
        ("discovery.trait_discovery", "特质探索"),
        ("discovery.sifat_learning", "Sifat学习"),
        ("discovery.face_quiz", "面部测验"),
        ("discovery.start", "开始游戏"),
        ("discovery.correct", "✓ 正确！"),
        ("discovery.wrong", "✗ 错误"),
        ("discovery.score", "分数"),
        ("discovery.finish", "游戏结束！"),
        ("discovery.next_question", "下一题"),
    ],
    'hi': [
        ("gamification.title", "गेमीफिकेशन"),
        ("gamification.coins", "मेरे कॉइन"),
        ("gamification.leaderboard", "लीडरबोर्ड"),
        ("gamification.badges", "बैज"),
        ("gamification.challenges", "चुनौतियां"),
        ("gamification.missions", "मिशन"),
        ("gamification.meal_game", "भोजन खेल"),
        ("gamification.discovery", "खोज खेल"),
        ("coin.balance", "कॉइन बैलेंस"),
        ("coin.history", "लेनदेन इतिहास"),
        ("coin.daily_quest", "दैनिक क्वेस्ट"),
        ("coin.total_earned", "कुल अर्जित"),
        ("coin.streak", "दिन की श्रृंखला"),
        ("coin.claim", "दैनिक क्वेस्ट लें"),
        ("coin.claimed", "आज लिया गया ✓"),
        ("coin.empty", "कोई लेनदेन नहीं"),
        ("coin.earned", "अर्जित"),
        ("coin.spent", "खर्च"),
        ("leaderboard.title", "लीडरबोर्ड"),
        ("leaderboard.global", "वैश्विक"),
        ("leaderboard.trending", "ट्रेंडिंग"),
        ("leaderboard.rank", "रैंक"),
        ("leaderboard.my_rank", "मेरी रैंक"),
        ("leaderboard.empty", "कोई डेटा नहीं"),
        ("leaderboard.coins", "कॉइन"),
        ("badge.title", "मेरे बैज"),
        ("badge.all_badges", "सभी बैज"),
        ("badge.locked", "लॉक"),
        ("badge.bronze", "कांस्य"),
        ("badge.silver", "चांदी"),
        ("badge.gold", "सोना"),
        ("badge.platinum", "प्लेटिनम"),
        ("badge.progress", "प्रगति"),
        ("badge.empty", "अभी तक कोई बैज नहीं"),
        ("challenge.title", "चुनौतियां"),
        ("challenge.join", "शामिल हों"),
        ("challenge.active", "सक्रिय"),
        ("challenge.empty", "कोई सक्रिय चुनौती नहीं"),
        ("challenge.score", "स्कोर"),
        ("meal_game.title", "भोजन खेल"),
        ("meal_game.week_country", "इस सप्ताह का व्यंजन"),
        ("meal_game.select_meal", "भोजन चुनें"),
        ("meal_game.guess_match", "क्या यह आपके व्यक्तित्व से मेल खाता है?"),
        ("meal_game.yes", "हां, मेल खाता है! 🎯"),
        ("meal_game.no", "नहीं, मेल नहीं खाता 😅"),
        ("meal_game.unsure", "निश्चित नहीं 🤔"),
        ("meal_game.correct", "✓ सही!"),
        ("meal_game.wrong", "✗ गलत"),
        ("meal_game.earned", "कॉइन अर्जित!"),
        ("meal_game.leaderboard", "साप्ताहिक रैंकिंग"),
        ("meal_game.history", "भोजन इतिहास"),
        ("meal_game.empty", "आज कोई चयन नहीं"),
        ("discovery.title", "खोज खेल"),
        ("discovery.trait_discovery", "विशेषता खोज"),
        ("discovery.sifat_learning", "सिफ़त सीखना"),
        ("discovery.face_quiz", "चेहरा क्विज़"),
        ("discovery.start", "खेल शुरू करें"),
        ("discovery.correct", "✓ सही!"),
        ("discovery.wrong", "✗ गलत"),
        ("discovery.score", "स्कोर"),
        ("discovery.finish", "खेल समाप्त!"),
        ("discovery.next_question", "अगला प्रश्न"),
    ],
    'fr': [
        ("gamification.title", "Gamification"),
        ("gamification.coins", "Mes Pièces"),
        ("gamification.leaderboard", "Classement"),
        ("gamification.badges", "Badges"),
        ("gamification.challenges", "Défis"),
        ("gamification.missions", "Missions"),
        ("gamification.meal_game", "Jeu des Repas"),
        ("gamification.discovery", "Jeux de Découverte"),
        ("coin.balance", "Solde de Pièces"),
        ("coin.history", "Historique des Transactions"),
        ("coin.daily_quest", "Quête Quotidienne"),
        ("coin.total_earned", "Total Gagné"),
        ("coin.streak", "Série de Jours"),
        ("coin.claim", "Réclamer la Quête"),
        ("coin.claimed", "Réclamé aujourd'hui ✓"),
        ("coin.empty", "Aucune transaction"),
        ("coin.earned", "gagné"),
        ("coin.spent", "dépensé"),
        ("leaderboard.title", "Classement"),
        ("leaderboard.global", "Mondial"),
        ("leaderboard.trending", "En hausse"),
        ("leaderboard.rank", "Rang"),
        ("leaderboard.my_rank", "Mon Rang"),
        ("leaderboard.empty", "Aucune donnée"),
        ("leaderboard.coins", "Pièces"),
        ("badge.title", "Mes Badges"),
        ("badge.all_badges", "Tous les Badges"),
        ("badge.locked", "Verrouillé"),
        ("badge.bronze", "Bronze"),
        ("badge.silver", "Argent"),
        ("badge.gold", "Or"),
        ("badge.platinum", "Platine"),
        ("badge.progress", "Progrès"),
        ("badge.empty", "Aucun badge encore"),
        ("challenge.title", "Défis"),
        ("challenge.join", "Rejoindre"),
        ("challenge.active", "Actif"),
        ("challenge.empty", "Aucun défi actif"),
        ("challenge.score", "Score"),
        ("meal_game.title", "Jeu des Repas"),
        ("meal_game.week_country", "Cuisine de la Semaine"),
        ("meal_game.select_meal", "Choisir un Repas"),
        ("meal_game.guess_match", "Correspond à votre personnalité?"),
        ("meal_game.yes", "Oui, ça correspond! 🎯"),
        ("meal_game.no", "Non, ça ne correspond pas 😅"),
        ("meal_game.unsure", "Pas sûr 🤔"),
        ("meal_game.correct", "✓ Correct!"),
        ("meal_game.wrong", "✗ Incorrect"),
        ("meal_game.earned", "pièces gagnées!"),
        ("meal_game.leaderboard", "Classement Hebdo"),
        ("meal_game.history", "Historique des Repas"),
        ("meal_game.empty", "Aucune sélection aujourd'hui"),
        ("discovery.title", "Jeux de Découverte"),
        ("discovery.trait_discovery", "Découverte des Traits"),
        ("discovery.sifat_learning", "Apprentissage Sifat"),
        ("discovery.face_quiz", "Quiz Visage"),
        ("discovery.start", "Démarrer le Jeu"),
        ("discovery.correct", "✓ Correct!"),
        ("discovery.wrong", "✗ Incorrect"),
        ("discovery.score", "Score"),
        ("discovery.finish", "Jeu terminé!"),
        ("discovery.next_question", "Question Suivante"),
    ],
    'pt': [
        ("gamification.title", "Gamificação"),
        ("gamification.coins", "Minhas Moedas"),
        ("gamification.leaderboard", "Classificação"),
        ("gamification.badges", "Medalhas"),
        ("gamification.challenges", "Desafios"),
        ("gamification.missions", "Missões"),
        ("gamification.meal_game", "Jogo de Refeições"),
        ("gamification.discovery", "Jogos de Descoberta"),
        ("coin.balance", "Saldo de Moedas"),
        ("coin.history", "Histórico de Transações"),
        ("coin.daily_quest", "Missão Diária"),
        ("coin.total_earned", "Total Ganho"),
        ("coin.streak", "Sequência de Dias"),
        ("coin.claim", "Reivindicar Missão"),
        ("coin.claimed", "Reivindicado hoje ✓"),
        ("coin.empty", "Sem transações ainda"),
        ("coin.earned", "ganho"),
        ("coin.spent", "gasto"),
        ("leaderboard.title", "Classificação"),
        ("leaderboard.global", "Global"),
        ("leaderboard.trending", "Em alta"),
        ("leaderboard.rank", "Rank"),
        ("leaderboard.my_rank", "Meu Rank"),
        ("leaderboard.empty", "Sem dados de classificação"),
        ("leaderboard.coins", "Moedas"),
        ("badge.title", "Minhas Medalhas"),
        ("badge.all_badges", "Todas as Medalhas"),
        ("badge.locked", "Bloqueado"),
        ("badge.bronze", "Bronze"),
        ("badge.silver", "Prata"),
        ("badge.gold", "Ouro"),
        ("badge.platinum", "Platina"),
        ("badge.progress", "Progresso"),
        ("badge.empty", "Sem medalhas ainda"),
        ("challenge.title", "Desafios"),
        ("challenge.join", "Participar"),
        ("challenge.active", "Ativo"),
        ("challenge.empty", "Sem desafios ativos"),
        ("challenge.score", "Pontuação"),
        ("meal_game.title", "Jogo de Refeições"),
        ("meal_game.week_country", "Culinária desta Semana"),
        ("meal_game.select_meal", "Selecionar Refeição"),
        ("meal_game.guess_match", "Corresponde à sua personalidade?"),
        ("meal_game.yes", "Sim, corresponde! 🎯"),
        ("meal_game.no", "Não corresponde 😅"),
        ("meal_game.unsure", "Não tenho certeza 🤔"),
        ("meal_game.correct", "✓ Correto!"),
        ("meal_game.wrong", "✗ Errado"),
        ("meal_game.earned", "moedas ganhas!"),
        ("meal_game.leaderboard", "Classificação Semanal"),
        ("meal_game.history", "Histórico de Refeições"),
        ("meal_game.empty", "Sem seleções hoje"),
        ("discovery.title", "Jogos de Descoberta"),
        ("discovery.trait_discovery", "Descoberta de Traços"),
        ("discovery.sifat_learning", "Aprendizado Sifat"),
        ("discovery.face_quiz", "Quiz Facial"),
        ("discovery.start", "Iniciar Jogo"),
        ("discovery.correct", "✓ Correto!"),
        ("discovery.wrong", "✗ Errado"),
        ("discovery.score", "Pontuação"),
        ("discovery.finish", "Jogo encerrado!"),
        ("discovery.next_question", "Próxima Pergunta"),
    ],
    'bn': [
        ("gamification.title", "গেমিফিকেশন"),
        ("gamification.coins", "আমার কয়েন"),
        ("gamification.leaderboard", "লিডারবোর্ড"),
        ("gamification.badges", "ব্যাজ"),
        ("gamification.challenges", "চ্যালেঞ্জ"),
        ("gamification.missions", "মিশন"),
        ("gamification.meal_game", "খাবার গেম"),
        ("gamification.discovery", "আবিষ্কার গেম"),
        ("coin.balance", "কয়েন ব্যালেন্স"),
        ("coin.history", "লেনদেন ইতিহাস"),
        ("coin.daily_quest", "দৈনিক কোয়েস্ট"),
        ("coin.total_earned", "মোট অর্জিত"),
        ("coin.streak", "দিনের ধারা"),
        ("coin.claim", "দৈনিক কোয়েস্ট নিন"),
        ("coin.claimed", "আজ নেওয়া হয়েছে ✓"),
        ("coin.empty", "কোনো লেনদেন নেই"),
        ("coin.earned", "অর্জিত"),
        ("coin.spent", "ব্যয়"),
        ("leaderboard.title", "লিডারবোর্ড"),
        ("leaderboard.global", "বৈশ্বিক"),
        ("leaderboard.trending", "ট্রেন্ডিং"),
        ("leaderboard.rank", "র‍্যাংক"),
        ("leaderboard.my_rank", "আমার র‍্যাংক"),
        ("leaderboard.empty", "কোনো ডেটা নেই"),
        ("leaderboard.coins", "কয়েন"),
        ("badge.title", "আমার ব্যাজ"),
        ("badge.all_badges", "সব ব্যাজ"),
        ("badge.locked", "লক"),
        ("badge.bronze", "ব্রোঞ্জ"),
        ("badge.silver", "রুপা"),
        ("badge.gold", "সোনা"),
        ("badge.platinum", "প্লাটিনাম"),
        ("badge.progress", "অগ্রগতি"),
        ("badge.empty", "এখনো কোনো ব্যাজ নেই"),
        ("challenge.title", "চ্যালেঞ্জ"),
        ("challenge.join", "যোগ দিন"),
        ("challenge.active", "সক্রিয়"),
        ("challenge.empty", "সক্রিয় চ্যালেঞ্জ নেই"),
        ("challenge.score", "স্কোর"),
        ("meal_game.title", "খাবার গেম"),
        ("meal_game.week_country", "এই সপ্তাহের রান্না"),
        ("meal_game.select_meal", "খাবার বেছে নিন"),
        ("meal_game.guess_match", "আপনার ব্যক্তিত্বের সাথে মেলে?"),
        ("meal_game.yes", "হ্যাঁ, মেলে! 🎯"),
        ("meal_game.no", "না, মেলে না 😅"),
        ("meal_game.unsure", "নিশ্চিত নই 🤔"),
        ("meal_game.correct", "✓ সঠিক!"),
        ("meal_game.wrong", "✗ ভুল"),
        ("meal_game.earned", "কয়েন অর্জিত!"),
        ("meal_game.leaderboard", "সাপ্তাহিক র‍্যাংকিং"),
        ("meal_game.history", "খাবার ইতিহাস"),
        ("meal_game.empty", "আজ কোনো নির্বাচন নেই"),
        ("discovery.title", "আবিষ্কার গেম"),
        ("discovery.trait_discovery", "বৈশিষ্ট্য আবিষ্কার"),
        ("discovery.sifat_learning", "সিফাত শিক্ষা"),
        ("discovery.face_quiz", "মুখ কুইজ"),
        ("discovery.start", "গেম শুরু করুন"),
        ("discovery.correct", "✓ সঠিক!"),
        ("discovery.wrong", "✗ ভুল"),
        ("discovery.score", "স্কোর"),
        ("discovery.finish", "গেম শেষ!"),
        ("discovery.next_question", "পরবর্তী প্রশ্ন"),
    ],
    'id': [
        ("gamification.title", "Gamifikasi"),
        ("gamification.coins", "Koin Saya"),
        ("gamification.leaderboard", "Papan Peringkat"),
        ("gamification.badges", "Lencana"),
        ("gamification.challenges", "Tantangan"),
        ("gamification.missions", "Misi"),
        ("gamification.meal_game", "Game Makanan"),
        ("gamification.discovery", "Game Penemuan"),
        ("coin.balance", "Saldo Koin"),
        ("coin.history", "Riwayat Transaksi"),
        ("coin.daily_quest", "Kuis Harian"),
        ("coin.total_earned", "Total Diperoleh"),
        ("coin.streak", "Rangkaian Hari"),
        ("coin.claim", "Ambil Kuis Harian"),
        ("coin.claimed", "Sudah diambil hari ini ✓"),
        ("coin.empty", "Belum ada transaksi"),
        ("coin.earned", "diperoleh"),
        ("coin.spent", "digunakan"),
        ("leaderboard.title", "Papan Peringkat"),
        ("leaderboard.global", "Global"),
        ("leaderboard.trending", "Tren"),
        ("leaderboard.rank", "Peringkat"),
        ("leaderboard.my_rank", "Peringkat Saya"),
        ("leaderboard.empty", "Belum ada data peringkat"),
        ("leaderboard.coins", "Koin"),
        ("badge.title", "Lencana Saya"),
        ("badge.all_badges", "Semua Lencana"),
        ("badge.locked", "Terkunci"),
        ("badge.bronze", "Perunggu"),
        ("badge.silver", "Perak"),
        ("badge.gold", "Emas"),
        ("badge.platinum", "Platinum"),
        ("badge.progress", "Kemajuan"),
        ("badge.empty", "Belum ada lencana"),
        ("challenge.title", "Tantangan"),
        ("challenge.join", "Bergabung"),
        ("challenge.active", "Aktif"),
        ("challenge.empty", "Tidak ada tantangan aktif"),
        ("challenge.score", "Skor"),
        ("meal_game.title", "Game Makanan"),
        ("meal_game.week_country", "Masakan Minggu Ini"),
        ("meal_game.select_meal", "Pilih Makanan"),
        ("meal_game.guess_match", "Cocok dengan kepribadian Anda?"),
        ("meal_game.yes", "Ya, Cocok! 🎯"),
        ("meal_game.no", "Tidak Cocok 😅"),
        ("meal_game.unsure", "Tidak Yakin 🤔"),
        ("meal_game.correct", "✓ Benar!"),
        ("meal_game.wrong", "✗ Salah"),
        ("meal_game.earned", "koin diperoleh!"),
        ("meal_game.leaderboard", "Peringkat Mingguan"),
        ("meal_game.history", "Riwayat Makanan"),
        ("meal_game.empty", "Belum ada pilihan hari ini"),
        ("discovery.title", "Game Penemuan"),
        ("discovery.trait_discovery", "Penemuan Sifat"),
        ("discovery.sifat_learning", "Pembelajaran Sifat"),
        ("discovery.face_quiz", "Kuis Wajah"),
        ("discovery.start", "Mulai Game"),
        ("discovery.correct", "✓ Benar!"),
        ("discovery.wrong", "✗ Salah"),
        ("discovery.score", "Skor"),
        ("discovery.finish", "Game Selesai!"),
        ("discovery.next_question", "Pertanyaan Berikutnya"),
    ],
    'ur': [
        ("gamification.title", "گیمیفیکیشن"),
        ("gamification.coins", "میرے سکے"),
        ("gamification.leaderboard", "لیڈربورڈ"),
        ("gamification.badges", "بیجز"),
        ("gamification.challenges", "چیلنجز"),
        ("gamification.missions", "مشن"),
        ("gamification.meal_game", "کھانے کا کھیل"),
        ("gamification.discovery", "دریافت کھیل"),
        ("coin.balance", "سکے کا بیلنس"),
        ("coin.history", "لین دین کی تاریخ"),
        ("coin.daily_quest", "روزانہ کوئسٹ"),
        ("coin.total_earned", "کل کمائے"),
        ("coin.streak", "روزانہ سلسلہ"),
        ("coin.claim", "روزانہ کوئسٹ لیں"),
        ("coin.claimed", "آج لے لیا ✓"),
        ("coin.empty", "کوئی لین دین نہیں"),
        ("coin.earned", "کمایا"),
        ("coin.spent", "خرچ"),
        ("leaderboard.title", "لیڈربورڈ"),
        ("leaderboard.global", "عالمی"),
        ("leaderboard.trending", "ٹرینڈنگ"),
        ("leaderboard.rank", "درجہ"),
        ("leaderboard.my_rank", "میرا درجہ"),
        ("leaderboard.empty", "کوئی ڈیٹا نہیں"),
        ("leaderboard.coins", "سکے"),
        ("badge.title", "میرے بیجز"),
        ("badge.all_badges", "تمام بیجز"),
        ("badge.locked", "بند"),
        ("badge.bronze", "کانسہ"),
        ("badge.silver", "چاندی"),
        ("badge.gold", "سونا"),
        ("badge.platinum", "پلاٹینم"),
        ("badge.progress", "پیشرفت"),
        ("badge.empty", "ابھی کوئی بیج نہیں"),
        ("challenge.title", "چیلنجز"),
        ("challenge.join", "شامل ہوں"),
        ("challenge.active", "فعال"),
        ("challenge.empty", "کوئی فعال چیلنج نہیں"),
        ("challenge.score", "اسکور"),
        ("meal_game.title", "کھانے کا کھیل"),
        ("meal_game.week_country", "اس ہفتے کا کھانا"),
        ("meal_game.select_meal", "کھانا منتخب کریں"),
        ("meal_game.guess_match", "کیا یہ آپکی شخصیت سے میل کھاتا ہے؟"),
        ("meal_game.yes", "ہاں، میل کھاتا ہے! 🎯"),
        ("meal_game.no", "نہیں، میل نہیں کھاتا 😅"),
        ("meal_game.unsure", "یقین نہیں 🤔"),
        ("meal_game.correct", "✓ درست!"),
        ("meal_game.wrong", "✗ غلط"),
        ("meal_game.earned", "سکے کمائے!"),
        ("meal_game.leaderboard", "ہفتہ وار درجہ بندی"),
        ("meal_game.history", "کھانے کی تاریخ"),
        ("meal_game.empty", "آج کوئی انتخاب نہیں"),
        ("discovery.title", "دریافت کھیل"),
        ("discovery.trait_discovery", "خاصیت دریافت"),
        ("discovery.sifat_learning", "صفت سیکھنا"),
        ("discovery.face_quiz", "چہرہ کوئز"),
        ("discovery.start", "کھیل شروع کریں"),
        ("discovery.correct", "✓ درست!"),
        ("discovery.wrong", "✗ غلط"),
        ("discovery.score", "اسکور"),
        ("discovery.finish", "کھیل ختم!"),
        ("discovery.next_question", "اگلا سوال"),
    ],
    'it': [
        ("gamification.title", "Gamification"),
        ("gamification.coins", "Le Mie Monete"),
        ("gamification.leaderboard", "Classifica"),
        ("gamification.badges", "Badge"),
        ("gamification.challenges", "Sfide"),
        ("gamification.missions", "Missioni"),
        ("gamification.meal_game", "Gioco dei Pasti"),
        ("gamification.discovery", "Giochi di Scoperta"),
        ("coin.balance", "Saldo Monete"),
        ("coin.history", "Storico Transazioni"),
        ("coin.daily_quest", "Quest Giornaliera"),
        ("coin.total_earned", "Totale Guadagnato"),
        ("coin.streak", "Serie Giorni"),
        ("coin.claim", "Riscatta Quest"),
        ("coin.claimed", "Riscattato oggi ✓"),
        ("coin.empty", "Nessuna transazione"),
        ("coin.earned", "guadagnato"),
        ("coin.spent", "speso"),
        ("leaderboard.title", "Classifica"),
        ("leaderboard.global", "Globale"),
        ("leaderboard.trending", "In salita"),
        ("leaderboard.rank", "Posizione"),
        ("leaderboard.my_rank", "La Mia Posizione"),
        ("leaderboard.empty", "Nessun dato classifica"),
        ("leaderboard.coins", "Monete"),
        ("badge.title", "I Miei Badge"),
        ("badge.all_badges", "Tutti i Badge"),
        ("badge.locked", "Bloccato"),
        ("badge.bronze", "Bronzo"),
        ("badge.silver", "Argento"),
        ("badge.gold", "Oro"),
        ("badge.platinum", "Platino"),
        ("badge.progress", "Progressi"),
        ("badge.empty", "Nessun badge ancora"),
        ("challenge.title", "Sfide"),
        ("challenge.join", "Unisciti"),
        ("challenge.active", "Attivo"),
        ("challenge.empty", "Nessuna sfida attiva"),
        ("challenge.score", "Punteggio"),
        ("meal_game.title", "Gioco dei Pasti"),
        ("meal_game.week_country", "Cucina della Settimana"),
        ("meal_game.select_meal", "Seleziona Pasto"),
        ("meal_game.guess_match", "Corrisponde alla tua personalità?"),
        ("meal_game.yes", "Sì, corrisponde! 🎯"),
        ("meal_game.no", "No, non corrisponde 😅"),
        ("meal_game.unsure", "Non sono sicuro 🤔"),
        ("meal_game.correct", "✓ Corretto!"),
        ("meal_game.wrong", "✗ Sbagliato"),
        ("meal_game.earned", "monete guadagnate!"),
        ("meal_game.leaderboard", "Classifica Settimanale"),
        ("meal_game.history", "Storico Pasti"),
        ("meal_game.empty", "Nessuna selezione oggi"),
        ("discovery.title", "Giochi di Scoperta"),
        ("discovery.trait_discovery", "Scoperta dei Tratti"),
        ("discovery.sifat_learning", "Apprendimento Sifat"),
        ("discovery.face_quiz", "Quiz Volto"),
        ("discovery.start", "Avvia Gioco"),
        ("discovery.correct", "✓ Corretto!"),
        ("discovery.wrong", "✗ Sbagliato"),
        ("discovery.score", "Punteggio"),
        ("discovery.finish", "Gioco Terminato!"),
        ("discovery.next_question", "Domanda Successiva"),
    ],
    'vi': [
        ("gamification.title", "Trò chơi hóa"),
        ("gamification.coins", "Xu của tôi"),
        ("gamification.leaderboard", "Bảng xếp hạng"),
        ("gamification.badges", "Huy hiệu"),
        ("gamification.challenges", "Thử thách"),
        ("gamification.missions", "Nhiệm vụ"),
        ("gamification.meal_game", "Trò chơi ăn uống"),
        ("gamification.discovery", "Trò chơi khám phá"),
        ("coin.balance", "Số dư xu"),
        ("coin.history", "Lịch sử giao dịch"),
        ("coin.daily_quest", "Nhiệm vụ hàng ngày"),
        ("coin.total_earned", "Tổng kiếm được"),
        ("coin.streak", "Chuỗi ngày"),
        ("coin.claim", "Nhận nhiệm vụ"),
        ("coin.claimed", "Đã nhận hôm nay ✓"),
        ("coin.empty", "Chưa có giao dịch"),
        ("coin.earned", "kiếm được"),
        ("coin.spent", "đã dùng"),
        ("leaderboard.title", "Bảng xếp hạng"),
        ("leaderboard.global", "Toàn cầu"),
        ("leaderboard.trending", "Đang tăng"),
        ("leaderboard.rank", "Hạng"),
        ("leaderboard.my_rank", "Hạng của tôi"),
        ("leaderboard.empty", "Chưa có dữ liệu"),
        ("leaderboard.coins", "Xu"),
        ("badge.title", "Huy hiệu của tôi"),
        ("badge.all_badges", "Tất cả huy hiệu"),
        ("badge.locked", "Đã khóa"),
        ("badge.bronze", "Đồng"),
        ("badge.silver", "Bạc"),
        ("badge.gold", "Vàng"),
        ("badge.platinum", "Bạch kim"),
        ("badge.progress", "Tiến độ"),
        ("badge.empty", "Chưa có huy hiệu"),
        ("challenge.title", "Thử thách"),
        ("challenge.join", "Tham gia"),
        ("challenge.active", "Đang hoạt động"),
        ("challenge.empty", "Không có thử thách"),
        ("challenge.score", "Điểm"),
        ("meal_game.title", "Trò chơi ăn uống"),
        ("meal_game.week_country", "Ẩm thực tuần này"),
        ("meal_game.select_meal", "Chọn món ăn"),
        ("meal_game.guess_match", "Phù hợp tính cách bạn?"),
        ("meal_game.yes", "Có, phù hợp! 🎯"),
        ("meal_game.no", "Không phù hợp 😅"),
        ("meal_game.unsure", "Không chắc 🤔"),
        ("meal_game.correct", "✓ Đúng!"),
        ("meal_game.wrong", "✗ Sai"),
        ("meal_game.earned", "xu kiếm được!"),
        ("meal_game.leaderboard", "Bảng xếp hạng tuần"),
        ("meal_game.history", "Lịch sử ăn uống"),
        ("meal_game.empty", "Chưa chọn hôm nay"),
        ("discovery.title", "Trò chơi khám phá"),
        ("discovery.trait_discovery", "Khám phá đặc điểm"),
        ("discovery.sifat_learning", "Học Sifat"),
        ("discovery.face_quiz", "Câu đố khuôn mặt"),
        ("discovery.start", "Bắt đầu trò chơi"),
        ("discovery.correct", "✓ Đúng!"),
        ("discovery.wrong", "✗ Sai"),
        ("discovery.score", "Điểm"),
        ("discovery.finish", "Trò chơi kết thúc!"),
        ("discovery.next_question", "Câu hỏi tiếp theo"),
    ],
    'pl': [
        ("gamification.title", "Grywalizacja"),
        ("gamification.coins", "Moje Monety"),
        ("gamification.leaderboard", "Tabela wyników"),
        ("gamification.badges", "Odznaki"),
        ("gamification.challenges", "Wyzwania"),
        ("gamification.missions", "Misje"),
        ("gamification.meal_game", "Gra posiłkowa"),
        ("gamification.discovery", "Gry odkryć"),
        ("coin.balance", "Saldo monet"),
        ("coin.history", "Historia transakcji"),
        ("coin.daily_quest", "Dzienne zadanie"),
        ("coin.total_earned", "Łącznie zarobione"),
        ("coin.streak", "Seria dni"),
        ("coin.claim", "Odbierz zadanie"),
        ("coin.claimed", "Odebrano dziś ✓"),
        ("coin.empty", "Brak transakcji"),
        ("coin.earned", "zarobiono"),
        ("coin.spent", "wydano"),
        ("leaderboard.title", "Tabela wyników"),
        ("leaderboard.global", "Globalny"),
        ("leaderboard.trending", "Rosnący"),
        ("leaderboard.rank", "Miejsce"),
        ("leaderboard.my_rank", "Moje miejsce"),
        ("leaderboard.empty", "Brak danych rankingu"),
        ("leaderboard.coins", "Monety"),
        ("badge.title", "Moje Odznaki"),
        ("badge.all_badges", "Wszystkie Odznaki"),
        ("badge.locked", "Zablokowane"),
        ("badge.bronze", "Brąz"),
        ("badge.silver", "Srebro"),
        ("badge.gold", "Złoto"),
        ("badge.platinum", "Platyna"),
        ("badge.progress", "Postęp"),
        ("badge.empty", "Brak odznak"),
        ("challenge.title", "Wyzwania"),
        ("challenge.join", "Dołącz"),
        ("challenge.active", "Aktywne"),
        ("challenge.empty", "Brak aktywnych wyzwań"),
        ("challenge.score", "Wynik"),
        ("meal_game.title", "Gra posiłkowa"),
        ("meal_game.week_country", "Kuchnia tego tygodnia"),
        ("meal_game.select_meal", "Wybierz posiłek"),
        ("meal_game.guess_match", "Pasuje do twojej osobowości?"),
        ("meal_game.yes", "Tak, pasuje! 🎯"),
        ("meal_game.no", "Nie pasuje 😅"),
        ("meal_game.unsure", "Nie jestem pewien 🤔"),
        ("meal_game.correct", "✓ Poprawnie!"),
        ("meal_game.wrong", "✗ Błędnie"),
        ("meal_game.earned", "monet zarobionych!"),
        ("meal_game.leaderboard", "Tygodniowy ranking"),
        ("meal_game.history", "Historia posiłków"),
        ("meal_game.empty", "Brak wyborów dzisiaj"),
        ("discovery.title", "Gry odkryć"),
        ("discovery.trait_discovery", "Odkrywanie cech"),
        ("discovery.sifat_learning", "Nauka Sifat"),
        ("discovery.face_quiz", "Quiz twarzy"),
        ("discovery.start", "Rozpocznij grę"),
        ("discovery.correct", "✓ Poprawnie!"),
        ("discovery.wrong", "✗ Błędnie"),
        ("discovery.score", "Wynik"),
        ("discovery.finish", "Koniec gry!"),
        ("discovery.next_question", "Następne pytanie"),
    ],
}

with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# The file ends with:
#   'diet.empty': 'XXXX',
#  },
# };
# So each language block's last key is 'diet.empty'.
# We use the last occurrence of "  LANG: {" to anchor into the right block,
# then find the diet.empty line within it.

LANG_ORDER = ['tr','en','de','ru','ar','es','ko','ja','zh','hi','fr','pt','bn','id','ur','it','vi','pl']

# Build insertion: for each lang, append keys after its diet.empty line
# Strategy: find "\n  LANG: {" and from there find the FIRST occurrence of "\n    'diet.empty':"
# then find the end of that line and insert new keys after.

total_insertions = 0
for lang in LANG_ORDER:
    keys = ALL_KEYS.get(lang, [])
    if not keys:
        continue

    # Build the new key lines
    new_lines = '\n' + '\n'.join(f"    '{k}': '{v}'," for k, v in keys)

    # Find this language's block start
    lang_marker = f'\n  {lang}: {{'
    lang_pos = content.find(lang_marker)
    if lang_pos == -1:
        print(f'WARNING: Language {lang} not found, skipping')
        continue

    # From lang_pos, find the diet.empty line
    diet_marker = "\n    'diet.empty':"
    diet_pos = content.find(diet_marker, lang_pos)
    if diet_pos == -1:
        print(f'WARNING: diet.empty not found for {lang}, skipping')
        continue

    # Find the end of the diet.empty line (the comma)
    line_end = content.find('\n', diet_pos + 1)
    if line_end == -1:
        print(f'WARNING: line end not found for {lang}, skipping')
        continue

    # Insert new keys after the diet.empty line
    content = content[:line_end] + new_lines + content[line_end:]
    total_insertions += len(keys)
    print(f'  {lang}: +{len(keys)} keys inserted')

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\nDone: {total_insertions} total insertions across {len(LANG_ORDER)} languages')
