"""Add coach i18n keys after gamification.hub_desc in each language block."""
import re

I18N_PATH = r'facesyma_mobile\src\utils\i18n.ts'

# 46 keys per language — insert after 'gamification.hub_desc' line in each block
KEYS = {
    'tr': [
        ("coach.hub_title", "Yaşam Koçu"),
        ("coach.hub_desc", "Kişiselleştirilmiş 32+ koçluk modülü"),
        ("coach.title", "Yaşam Koçu"),
        ("coach.subtitle", "Yüzünden kişiselleştirilmiş koçluk"),
        ("coach.analyze_btn", "Koç Analizi Başlat"),
        ("coach.analyzing", "Analiz ediliyor..."),
        ("coach.no_analysis", "Önce yüz analizi yapın"),
        ("coach.modules_title", "Koçluk Modülleri"),
        ("coach.profile_saved", "Profil kaydedildi"),
        ("coach.birth_btn", "Doğum Analizi"),
        ("coach.goals_btn", "Hedeflerim"),
        ("coach.goals_title", "Kişisel Hedefler"),
        ("coach.add_goal", "Hedef Ekle"),
        ("coach.goal_title_label", "Hedef Başlığı"),
        ("coach.goal_priority_low", "Düşük"),
        ("coach.goal_priority_medium", "Orta"),
        ("coach.goal_priority_high", "Yüksek"),
        ("coach.goal_save", "Kaydet"),
        ("coach.no_goals", "Henüz hedef yok"),
        ("coach.status_all", "Tümü"),
        ("coach.status_active", "Aktif"),
        ("coach.status_completed", "Tamamlandı"),
        ("coach.status_paused", "Beklemede"),
        ("coach.birth_title", "Doğum Analizi"),
        ("coach.birth_date_label", "Doğum Tarihi"),
        ("coach.birth_time_label", "Doğum Saati (opsiyonel)"),
        ("coach.calculate", "Hesapla"),
        ("coach.sun_sign", "Güneş Burcu"),
        ("coach.element", "Element"),
        ("coach.quality", "Nitelik"),
        ("coach.season", "Mevsim"),
        ("coach.life_path", "Yaşam Yolu Sayısı"),
        ("coach.life_meaning", "Anlam"),
        ("coach.numerology_title", "Numeroloji"),
        ("coach.mod_health", "Sağlık & Esenlik"),
        ("coach.mod_career", "Kariyer Yolu"),
        ("coach.mod_relationship", "İlişki Yönetimi"),
        ("coach.mod_stress", "Stres Yönetimi"),
        ("coach.mod_confidence", "Özgüven"),
        ("coach.mod_meditation", "Meditasyon"),
        ("coach.mod_fashion", "Giyim Tarzı"),
        ("coach.mod_book", "Kitap Tavsiyeleri"),
        ("coach.mod_film", "Film Tavsiyeleri"),
        ("coach.mod_music", "Müzik Tavsiyeleri"),
        ("coach.mod_travel", "Seyahat Tavsiyeleri"),
        ("coach.mod_astrology", "Astroloji Haritası"),
    ],
    'en': [
        ("coach.hub_title", "Life Coach"),
        ("coach.hub_desc", "Personalized 32+ coaching modules"),
        ("coach.title", "Life Coach"),
        ("coach.subtitle", "Personalized coaching from your face"),
        ("coach.analyze_btn", "Start Coach Analysis"),
        ("coach.analyzing", "Analyzing..."),
        ("coach.no_analysis", "Run a face analysis first"),
        ("coach.modules_title", "Coaching Modules"),
        ("coach.profile_saved", "Profile saved"),
        ("coach.birth_btn", "Birth Analysis"),
        ("coach.goals_btn", "My Goals"),
        ("coach.goals_title", "Personal Goals"),
        ("coach.add_goal", "Add Goal"),
        ("coach.goal_title_label", "Goal Title"),
        ("coach.goal_priority_low", "Low"),
        ("coach.goal_priority_medium", "Medium"),
        ("coach.goal_priority_high", "High"),
        ("coach.goal_save", "Save"),
        ("coach.no_goals", "No goals yet"),
        ("coach.status_all", "All"),
        ("coach.status_active", "Active"),
        ("coach.status_completed", "Completed"),
        ("coach.status_paused", "Paused"),
        ("coach.birth_title", "Birth Analysis"),
        ("coach.birth_date_label", "Birth Date"),
        ("coach.birth_time_label", "Birth Time (optional)"),
        ("coach.calculate", "Calculate"),
        ("coach.sun_sign", "Sun Sign"),
        ("coach.element", "Element"),
        ("coach.quality", "Quality"),
        ("coach.season", "Season"),
        ("coach.life_path", "Life Path Number"),
        ("coach.life_meaning", "Meaning"),
        ("coach.numerology_title", "Numerology"),
        ("coach.mod_health", "Health & Wellness"),
        ("coach.mod_career", "Career Path"),
        ("coach.mod_relationship", "Relationship"),
        ("coach.mod_stress", "Stress Management"),
        ("coach.mod_confidence", "Self-Confidence"),
        ("coach.mod_meditation", "Meditation"),
        ("coach.mod_fashion", "Style & Fashion"),
        ("coach.mod_book", "Book Recommendations"),
        ("coach.mod_film", "Film Recommendations"),
        ("coach.mod_music", "Music Recommendations"),
        ("coach.mod_travel", "Travel Recommendations"),
        ("coach.mod_astrology", "Astrology Chart"),
    ],
    'de': [
        ("coach.hub_title", "Life-Coach"),
        ("coach.hub_desc", "Personalisierte 32+ Coaching-Module"),
        ("coach.title", "Life-Coach"),
        ("coach.subtitle", "Personalisiertes Coaching aus deinem Gesicht"),
        ("coach.analyze_btn", "Coaching-Analyse starten"),
        ("coach.analyzing", "Analysiere..."),
        ("coach.no_analysis", "Führe zuerst eine Gesichtsanalyse durch"),
        ("coach.modules_title", "Coaching-Module"),
        ("coach.profile_saved", "Profil gespeichert"),
        ("coach.birth_btn", "Geburtsanalyse"),
        ("coach.goals_btn", "Meine Ziele"),
        ("coach.goals_title", "Persönliche Ziele"),
        ("coach.add_goal", "Ziel hinzufügen"),
        ("coach.goal_title_label", "Ziel Titel"),
        ("coach.goal_priority_low", "Niedrig"),
        ("coach.goal_priority_medium", "Mittel"),
        ("coach.goal_priority_high", "Hoch"),
        ("coach.goal_save", "Speichern"),
        ("coach.no_goals", "Noch keine Ziele"),
        ("coach.status_all", "Alle"),
        ("coach.status_active", "Aktiv"),
        ("coach.status_completed", "Abgeschlossen"),
        ("coach.status_paused", "Pausiert"),
        ("coach.birth_title", "Geburtsanalyse"),
        ("coach.birth_date_label", "Geburtsdatum"),
        ("coach.birth_time_label", "Geburtszeit (optional)"),
        ("coach.calculate", "Berechnen"),
        ("coach.sun_sign", "Sonnenzeichen"),
        ("coach.element", "Element"),
        ("coach.quality", "Qualität"),
        ("coach.season", "Jahreszeit"),
        ("coach.life_path", "Lebenspfadzahl"),
        ("coach.life_meaning", "Bedeutung"),
        ("coach.numerology_title", "Numerologie"),
        ("coach.mod_health", "Gesundheit & Wohlbefinden"),
        ("coach.mod_career", "Karriereweg"),
        ("coach.mod_relationship", "Beziehung"),
        ("coach.mod_stress", "Stressmanagement"),
        ("coach.mod_confidence", "Selbstvertrauen"),
        ("coach.mod_meditation", "Meditation"),
        ("coach.mod_fashion", "Stil & Mode"),
        ("coach.mod_book", "Buchempfehlungen"),
        ("coach.mod_film", "Filmempfehlungen"),
        ("coach.mod_music", "Musikempfehlungen"),
        ("coach.mod_travel", "Reiseempfehlungen"),
        ("coach.mod_astrology", "Astrologiekarte"),
    ],
    'ru': [
        ("coach.hub_title", "Жизненный коуч"),
        ("coach.hub_desc", "Персонализированные 32+ модуля коучинга"),
        ("coach.title", "Жизненный коуч"),
        ("coach.subtitle", "Персонализированный коучинг по вашему лицу"),
        ("coach.analyze_btn", "Начать анализ коуча"),
        ("coach.analyzing", "Анализирую..."),
        ("coach.no_analysis", "Сначала выполните анализ лица"),
        ("coach.modules_title", "Модули коучинга"),
        ("coach.profile_saved", "Профиль сохранён"),
        ("coach.birth_btn", "Анализ рождения"),
        ("coach.goals_btn", "Мои цели"),
        ("coach.goals_title", "Личные цели"),
        ("coach.add_goal", "Добавить цель"),
        ("coach.goal_title_label", "Название цели"),
        ("coach.goal_priority_low", "Низкий"),
        ("coach.goal_priority_medium", "Средний"),
        ("coach.goal_priority_high", "Высокий"),
        ("coach.goal_save", "Сохранить"),
        ("coach.no_goals", "Целей пока нет"),
        ("coach.status_all", "Все"),
        ("coach.status_active", "Активные"),
        ("coach.status_completed", "Завершённые"),
        ("coach.status_paused", "Приостановленные"),
        ("coach.birth_title", "Анализ рождения"),
        ("coach.birth_date_label", "Дата рождения"),
        ("coach.birth_time_label", "Время рождения (необязательно)"),
        ("coach.calculate", "Вычислить"),
        ("coach.sun_sign", "Знак Солнца"),
        ("coach.element", "Элемент"),
        ("coach.quality", "Качество"),
        ("coach.season", "Сезон"),
        ("coach.life_path", "Число жизненного пути"),
        ("coach.life_meaning", "Значение"),
        ("coach.numerology_title", "Нумерология"),
        ("coach.mod_health", "Здоровье и благополучие"),
        ("coach.mod_career", "Карьерный путь"),
        ("coach.mod_relationship", "Отношения"),
        ("coach.mod_stress", "Управление стрессом"),
        ("coach.mod_confidence", "Уверенность в себе"),
        ("coach.mod_meditation", "Медитация"),
        ("coach.mod_fashion", "Стиль и мода"),
        ("coach.mod_book", "Рекомендации книг"),
        ("coach.mod_film", "Рекомендации фильмов"),
        ("coach.mod_music", "Рекомендации музыки"),
        ("coach.mod_travel", "Рекомендации путешествий"),
        ("coach.mod_astrology", "Астрологическая карта"),
    ],
    'ar': [
        ("coach.hub_title", "مدرب الحياة"),
        ("coach.hub_desc", "أكثر من 32 وحدة تدريب مخصصة"),
        ("coach.title", "مدرب الحياة"),
        ("coach.subtitle", "تدريب مخصص من وجهك"),
        ("coach.analyze_btn", "بدء تحليل المدرب"),
        ("coach.analyzing", "جار التحليل..."),
        ("coach.no_analysis", "قم بتحليل الوجه أولاً"),
        ("coach.modules_title", "وحدات التدريب"),
        ("coach.profile_saved", "تم حفظ الملف الشخصي"),
        ("coach.birth_btn", "تحليل الولادة"),
        ("coach.goals_btn", "أهدافي"),
        ("coach.goals_title", "الأهداف الشخصية"),
        ("coach.add_goal", "إضافة هدف"),
        ("coach.goal_title_label", "عنوان الهدف"),
        ("coach.goal_priority_low", "منخفض"),
        ("coach.goal_priority_medium", "متوسط"),
        ("coach.goal_priority_high", "مرتفع"),
        ("coach.goal_save", "حفظ"),
        ("coach.no_goals", "لا أهداف حتى الآن"),
        ("coach.status_all", "الكل"),
        ("coach.status_active", "نشط"),
        ("coach.status_completed", "مكتمل"),
        ("coach.status_paused", "متوقف"),
        ("coach.birth_title", "تحليل الولادة"),
        ("coach.birth_date_label", "تاريخ الميلاد"),
        ("coach.birth_time_label", "وقت الولادة (اختياري)"),
        ("coach.calculate", "احسب"),
        ("coach.sun_sign", "برج الشمس"),
        ("coach.element", "العنصر"),
        ("coach.quality", "الجودة"),
        ("coach.season", "الفصل"),
        ("coach.life_path", "رقم مسار الحياة"),
        ("coach.life_meaning", "المعنى"),
        ("coach.numerology_title", "علم الأعداد"),
        ("coach.mod_health", "الصحة والعافية"),
        ("coach.mod_career", "المسار المهني"),
        ("coach.mod_relationship", "العلاقات"),
        ("coach.mod_stress", "إدارة التوتر"),
        ("coach.mod_confidence", "الثقة بالنفس"),
        ("coach.mod_meditation", "التأمل"),
        ("coach.mod_fashion", "الأسلوب والموضة"),
        ("coach.mod_book", "توصيات الكتب"),
        ("coach.mod_film", "توصيات الأفلام"),
        ("coach.mod_music", "توصيات الموسيقى"),
        ("coach.mod_travel", "توصيات السفر"),
        ("coach.mod_astrology", "خريطة الأبراج"),
    ],
    'es': [
        ("coach.hub_title", "Coach de Vida"),
        ("coach.hub_desc", "Más de 32 módulos de coaching personalizados"),
        ("coach.title", "Coach de Vida"),
        ("coach.subtitle", "Coaching personalizado a partir de tu rostro"),
        ("coach.analyze_btn", "Iniciar Análisis de Coach"),
        ("coach.analyzing", "Analizando..."),
        ("coach.no_analysis", "Primero realiza un análisis facial"),
        ("coach.modules_title", "Módulos de Coaching"),
        ("coach.profile_saved", "Perfil guardado"),
        ("coach.birth_btn", "Análisis de Nacimiento"),
        ("coach.goals_btn", "Mis Objetivos"),
        ("coach.goals_title", "Objetivos Personales"),
        ("coach.add_goal", "Agregar Objetivo"),
        ("coach.goal_title_label", "Título del Objetivo"),
        ("coach.goal_priority_low", "Bajo"),
        ("coach.goal_priority_medium", "Medio"),
        ("coach.goal_priority_high", "Alto"),
        ("coach.goal_save", "Guardar"),
        ("coach.no_goals", "Sin objetivos aún"),
        ("coach.status_all", "Todos"),
        ("coach.status_active", "Activo"),
        ("coach.status_completed", "Completado"),
        ("coach.status_paused", "Pausado"),
        ("coach.birth_title", "Análisis de Nacimiento"),
        ("coach.birth_date_label", "Fecha de Nacimiento"),
        ("coach.birth_time_label", "Hora de Nacimiento (opcional)"),
        ("coach.calculate", "Calcular"),
        ("coach.sun_sign", "Signo Solar"),
        ("coach.element", "Elemento"),
        ("coach.quality", "Cualidad"),
        ("coach.season", "Estación"),
        ("coach.life_path", "Número de Camino de Vida"),
        ("coach.life_meaning", "Significado"),
        ("coach.numerology_title", "Numerología"),
        ("coach.mod_health", "Salud y Bienestar"),
        ("coach.mod_career", "Camino Profesional"),
        ("coach.mod_relationship", "Relaciones"),
        ("coach.mod_stress", "Gestión del Estrés"),
        ("coach.mod_confidence", "Autoconfianza"),
        ("coach.mod_meditation", "Meditación"),
        ("coach.mod_fashion", "Estilo y Moda"),
        ("coach.mod_book", "Recomendaciones de Libros"),
        ("coach.mod_film", "Recomendaciones de Películas"),
        ("coach.mod_music", "Recomendaciones de Música"),
        ("coach.mod_travel", "Recomendaciones de Viaje"),
        ("coach.mod_astrology", "Carta Astrológica"),
    ],
    'ko': [
        ("coach.hub_title", "라이프 코치"),
        ("coach.hub_desc", "32개 이상의 개인화된 코칭 모듈"),
        ("coach.title", "라이프 코치"),
        ("coach.subtitle", "얼굴에서 맞춤형 코칭"),
        ("coach.analyze_btn", "코치 분석 시작"),
        ("coach.analyzing", "분석 중..."),
        ("coach.no_analysis", "먼저 얼굴 분석을 실행하세요"),
        ("coach.modules_title", "코칭 모듈"),
        ("coach.profile_saved", "프로필 저장됨"),
        ("coach.birth_btn", "생년월일 분석"),
        ("coach.goals_btn", "나의 목표"),
        ("coach.goals_title", "개인 목표"),
        ("coach.add_goal", "목표 추가"),
        ("coach.goal_title_label", "목표 제목"),
        ("coach.goal_priority_low", "낮음"),
        ("coach.goal_priority_medium", "중간"),
        ("coach.goal_priority_high", "높음"),
        ("coach.goal_save", "저장"),
        ("coach.no_goals", "아직 목표 없음"),
        ("coach.status_all", "전체"),
        ("coach.status_active", "활성"),
        ("coach.status_completed", "완료"),
        ("coach.status_paused", "일시 중지"),
        ("coach.birth_title", "생년월일 분석"),
        ("coach.birth_date_label", "생년월일"),
        ("coach.birth_time_label", "출생 시간 (선택)"),
        ("coach.calculate", "계산"),
        ("coach.sun_sign", "태양 별자리"),
        ("coach.element", "원소"),
        ("coach.quality", "품질"),
        ("coach.season", "계절"),
        ("coach.life_path", "인생 경로 번호"),
        ("coach.life_meaning", "의미"),
        ("coach.numerology_title", "수비학"),
        ("coach.mod_health", "건강 & 웰니스"),
        ("coach.mod_career", "커리어 경로"),
        ("coach.mod_relationship", "관계"),
        ("coach.mod_stress", "스트레스 관리"),
        ("coach.mod_confidence", "자신감"),
        ("coach.mod_meditation", "명상"),
        ("coach.mod_fashion", "스타일 & 패션"),
        ("coach.mod_book", "도서 추천"),
        ("coach.mod_film", "영화 추천"),
        ("coach.mod_music", "음악 추천"),
        ("coach.mod_travel", "여행 추천"),
        ("coach.mod_astrology", "점성술 차트"),
    ],
    'ja': [
        ("coach.hub_title", "ライフコーチ"),
        ("coach.hub_desc", "32以上のパーソナライズされたコーチングモジュール"),
        ("coach.title", "ライフコーチ"),
        ("coach.subtitle", "顔からパーソナライズされたコーチング"),
        ("coach.analyze_btn", "コーチ分析を開始"),
        ("coach.analyzing", "分析中..."),
        ("coach.no_analysis", "まず顔分析を実行してください"),
        ("coach.modules_title", "コーチングモジュール"),
        ("coach.profile_saved", "プロフィールが保存されました"),
        ("coach.birth_btn", "誕生日分析"),
        ("coach.goals_btn", "私の目標"),
        ("coach.goals_title", "個人目標"),
        ("coach.add_goal", "目標を追加"),
        ("coach.goal_title_label", "目標タイトル"),
        ("coach.goal_priority_low", "低い"),
        ("coach.goal_priority_medium", "中程度"),
        ("coach.goal_priority_high", "高い"),
        ("coach.goal_save", "保存"),
        ("coach.no_goals", "まだ目標がありません"),
        ("coach.status_all", "すべて"),
        ("coach.status_active", "アクティブ"),
        ("coach.status_completed", "完了"),
        ("coach.status_paused", "一時停止"),
        ("coach.birth_title", "誕生日分析"),
        ("coach.birth_date_label", "生年月日"),
        ("coach.birth_time_label", "出生時刻（任意）"),
        ("coach.calculate", "計算"),
        ("coach.sun_sign", "太陽宮"),
        ("coach.element", "元素"),
        ("coach.quality", "性質"),
        ("coach.season", "季節"),
        ("coach.life_path", "ライフパスナンバー"),
        ("coach.life_meaning", "意味"),
        ("coach.numerology_title", "数秘術"),
        ("coach.mod_health", "健康とウェルネス"),
        ("coach.mod_career", "キャリアパス"),
        ("coach.mod_relationship", "人間関係"),
        ("coach.mod_stress", "ストレス管理"),
        ("coach.mod_confidence", "自己信頼"),
        ("coach.mod_meditation", "瞑想"),
        ("coach.mod_fashion", "スタイルとファッション"),
        ("coach.mod_book", "本のおすすめ"),
        ("coach.mod_film", "映画のおすすめ"),
        ("coach.mod_music", "音楽のおすすめ"),
        ("coach.mod_travel", "旅行のおすすめ"),
        ("coach.mod_astrology", "占星術チャート"),
    ],
    'zh': [
        ("coach.hub_title", "生活教练"),
        ("coach.hub_desc", "超过32个个性化教练模块"),
        ("coach.title", "生活教练"),
        ("coach.subtitle", "根据您的面部个性化教练"),
        ("coach.analyze_btn", "开始教练分析"),
        ("coach.analyzing", "分析中..."),
        ("coach.no_analysis", "先进行面部分析"),
        ("coach.modules_title", "教练模块"),
        ("coach.profile_saved", "个人资料已保存"),
        ("coach.birth_btn", "生日分析"),
        ("coach.goals_btn", "我的目标"),
        ("coach.goals_title", "个人目标"),
        ("coach.add_goal", "添加目标"),
        ("coach.goal_title_label", "目标标题"),
        ("coach.goal_priority_low", "低"),
        ("coach.goal_priority_medium", "中"),
        ("coach.goal_priority_high", "高"),
        ("coach.goal_save", "保存"),
        ("coach.no_goals", "暂无目标"),
        ("coach.status_all", "全部"),
        ("coach.status_active", "活跃"),
        ("coach.status_completed", "已完成"),
        ("coach.status_paused", "已暂停"),
        ("coach.birth_title", "生日分析"),
        ("coach.birth_date_label", "出生日期"),
        ("coach.birth_time_label", "出生时间（可选）"),
        ("coach.calculate", "计算"),
        ("coach.sun_sign", "太阳星座"),
        ("coach.element", "元素"),
        ("coach.quality", "品质"),
        ("coach.season", "季节"),
        ("coach.life_path", "生命路径数"),
        ("coach.life_meaning", "含义"),
        ("coach.numerology_title", "数字学"),
        ("coach.mod_health", "健康与养生"),
        ("coach.mod_career", "职业路径"),
        ("coach.mod_relationship", "人际关系"),
        ("coach.mod_stress", "压力管理"),
        ("coach.mod_confidence", "自信心"),
        ("coach.mod_meditation", "冥想"),
        ("coach.mod_fashion", "风格与时尚"),
        ("coach.mod_book", "书籍推荐"),
        ("coach.mod_film", "影视推荐"),
        ("coach.mod_music", "音乐推荐"),
        ("coach.mod_travel", "旅游推荐"),
        ("coach.mod_astrology", "星座图"),
    ],
    'hi': [
        ("coach.hub_title", "जीवन कोच"),
        ("coach.hub_desc", "32+ व्यक्तिगत कोचिंग मॉड्यूल"),
        ("coach.title", "जीवन कोच"),
        ("coach.subtitle", "आपके चेहरे से व्यक्तिगत कोचिंग"),
        ("coach.analyze_btn", "कोच विश्लेषण शुरू करें"),
        ("coach.analyzing", "विश्लेषण हो रहा है..."),
        ("coach.no_analysis", "पहले चेहरा विश्लेषण करें"),
        ("coach.modules_title", "कोचिंग मॉड्यूल"),
        ("coach.profile_saved", "प्रोफाइल सहेजी गई"),
        ("coach.birth_btn", "जन्म विश्लेषण"),
        ("coach.goals_btn", "मेरे लक्ष्य"),
        ("coach.goals_title", "व्यक्तिगत लक्ष्य"),
        ("coach.add_goal", "लक्ष्य जोड़ें"),
        ("coach.goal_title_label", "लक्ष्य शीर्षक"),
        ("coach.goal_priority_low", "कम"),
        ("coach.goal_priority_medium", "मध्यम"),
        ("coach.goal_priority_high", "उच्च"),
        ("coach.goal_save", "सहेजें"),
        ("coach.no_goals", "अभी कोई लक्ष्य नहीं"),
        ("coach.status_all", "सभी"),
        ("coach.status_active", "सक्रिय"),
        ("coach.status_completed", "पूर्ण"),
        ("coach.status_paused", "रोका गया"),
        ("coach.birth_title", "जन्म विश्लेषण"),
        ("coach.birth_date_label", "जन्म तिथि"),
        ("coach.birth_time_label", "जन्म समय (वैकल्पिक)"),
        ("coach.calculate", "गणना करें"),
        ("coach.sun_sign", "सूर्य राशि"),
        ("coach.element", "तत्व"),
        ("coach.quality", "गुण"),
        ("coach.season", "ऋतु"),
        ("coach.life_path", "जीवन पथ संख्या"),
        ("coach.life_meaning", "अर्थ"),
        ("coach.numerology_title", "अंक ज्योतिष"),
        ("coach.mod_health", "स्वास्थ्य और कल्याण"),
        ("coach.mod_career", "करियर पथ"),
        ("coach.mod_relationship", "रिश्ते"),
        ("coach.mod_stress", "तनाव प्रबंधन"),
        ("coach.mod_confidence", "आत्मविश्वास"),
        ("coach.mod_meditation", "ध्यान"),
        ("coach.mod_fashion", "शैली और फैशन"),
        ("coach.mod_book", "पुस्तक सिफारिशें"),
        ("coach.mod_film", "फिल्म सिफारिशें"),
        ("coach.mod_music", "संगीत सिफारिशें"),
        ("coach.mod_travel", "यात्रा सिफारिशें"),
        ("coach.mod_astrology", "ज्योतिष चार्ट"),
    ],
    'fr': [
        ("coach.hub_title", "Coach de Vie"),
        ("coach.hub_desc", "Plus de 32 modules de coaching personnalisés"),
        ("coach.title", "Coach de Vie"),
        ("coach.subtitle", "Coaching personnalisé à partir de votre visage"),
        ("coach.analyze_btn", "Démarrer l\\'analyse de coaching"),
        ("coach.analyzing", "Analyse en cours..."),
        ("coach.no_analysis", "Effectuez d\\'abord une analyse faciale"),
        ("coach.modules_title", "Modules de Coaching"),
        ("coach.profile_saved", "Profil sauvegardé"),
        ("coach.birth_btn", "Analyse de Naissance"),
        ("coach.goals_btn", "Mes Objectifs"),
        ("coach.goals_title", "Objectifs Personnels"),
        ("coach.add_goal", "Ajouter un Objectif"),
        ("coach.goal_title_label", "Titre de l\\'Objectif"),
        ("coach.goal_priority_low", "Faible"),
        ("coach.goal_priority_medium", "Moyen"),
        ("coach.goal_priority_high", "Élevé"),
        ("coach.goal_save", "Enregistrer"),
        ("coach.no_goals", "Aucun objectif encore"),
        ("coach.status_all", "Tous"),
        ("coach.status_active", "Actif"),
        ("coach.status_completed", "Terminé"),
        ("coach.status_paused", "En pause"),
        ("coach.birth_title", "Analyse de Naissance"),
        ("coach.birth_date_label", "Date de Naissance"),
        ("coach.birth_time_label", "Heure de Naissance (optionnel)"),
        ("coach.calculate", "Calculer"),
        ("coach.sun_sign", "Signe Solaire"),
        ("coach.element", "Élément"),
        ("coach.quality", "Qualité"),
        ("coach.season", "Saison"),
        ("coach.life_path", "Nombre de Chemin de Vie"),
        ("coach.life_meaning", "Signification"),
        ("coach.numerology_title", "Numérologie"),
        ("coach.mod_health", "Santé et Bien-être"),
        ("coach.mod_career", "Chemin de Carrière"),
        ("coach.mod_relationship", "Relations"),
        ("coach.mod_stress", "Gestion du Stress"),
        ("coach.mod_confidence", "Confiance en Soi"),
        ("coach.mod_meditation", "Méditation"),
        ("coach.mod_fashion", "Style et Mode"),
        ("coach.mod_book", "Recommandations de Livres"),
        ("coach.mod_film", "Recommandations de Films"),
        ("coach.mod_music", "Recommandations Musicales"),
        ("coach.mod_travel", "Recommandations de Voyage"),
        ("coach.mod_astrology", "Carte Astrologique"),
    ],
    'pt': [
        ("coach.hub_title", "Coach de Vida"),
        ("coach.hub_desc", "Mais de 32 módulos de coaching personalizados"),
        ("coach.title", "Coach de Vida"),
        ("coach.subtitle", "Coaching personalizado a partir do seu rosto"),
        ("coach.analyze_btn", "Iniciar Análise de Coaching"),
        ("coach.analyzing", "Analisando..."),
        ("coach.no_analysis", "Primeiro faça uma análise facial"),
        ("coach.modules_title", "Módulos de Coaching"),
        ("coach.profile_saved", "Perfil salvo"),
        ("coach.birth_btn", "Análise de Nascimento"),
        ("coach.goals_btn", "Meus Objetivos"),
        ("coach.goals_title", "Objetivos Pessoais"),
        ("coach.add_goal", "Adicionar Objetivo"),
        ("coach.goal_title_label", "Título do Objetivo"),
        ("coach.goal_priority_low", "Baixo"),
        ("coach.goal_priority_medium", "Médio"),
        ("coach.goal_priority_high", "Alto"),
        ("coach.goal_save", "Salvar"),
        ("coach.no_goals", "Sem objetivos ainda"),
        ("coach.status_all", "Todos"),
        ("coach.status_active", "Ativo"),
        ("coach.status_completed", "Concluído"),
        ("coach.status_paused", "Pausado"),
        ("coach.birth_title", "Análise de Nascimento"),
        ("coach.birth_date_label", "Data de Nascimento"),
        ("coach.birth_time_label", "Hora de Nascimento (opcional)"),
        ("coach.calculate", "Calcular"),
        ("coach.sun_sign", "Signo Solar"),
        ("coach.element", "Elemento"),
        ("coach.quality", "Qualidade"),
        ("coach.season", "Estação"),
        ("coach.life_path", "Número do Caminho de Vida"),
        ("coach.life_meaning", "Significado"),
        ("coach.numerology_title", "Numerologia"),
        ("coach.mod_health", "Saúde e Bem-estar"),
        ("coach.mod_career", "Caminho de Carreira"),
        ("coach.mod_relationship", "Relacionamentos"),
        ("coach.mod_stress", "Gestão do Estresse"),
        ("coach.mod_confidence", "Autoconfiança"),
        ("coach.mod_meditation", "Meditação"),
        ("coach.mod_fashion", "Estilo e Moda"),
        ("coach.mod_book", "Recomendações de Livros"),
        ("coach.mod_film", "Recomendações de Filmes"),
        ("coach.mod_music", "Recomendações Musicais"),
        ("coach.mod_travel", "Recomendações de Viagem"),
        ("coach.mod_astrology", "Carta Astrológica"),
    ],
    'bn': [
        ("coach.hub_title", "জীবন প্রশিক্ষক"),
        ("coach.hub_desc", "৩২+ ব্যক্তিগতকৃত কোচিং মডিউল"),
        ("coach.title", "জীবন প্রশিক্ষক"),
        ("coach.subtitle", "আপনার মুখ থেকে ব্যক্তিগতকৃত কোচিং"),
        ("coach.analyze_btn", "কোচ বিশ্লেষণ শুরু করুন"),
        ("coach.analyzing", "বিশ্লেষণ হচ্ছে..."),
        ("coach.no_analysis", "প্রথমে মুখ বিশ্লেষণ করুন"),
        ("coach.modules_title", "কোচিং মডিউল"),
        ("coach.profile_saved", "প্রোফাইল সংরক্ষিত"),
        ("coach.birth_btn", "জন্ম বিশ্লেষণ"),
        ("coach.goals_btn", "আমার লক্ষ্য"),
        ("coach.goals_title", "ব্যক্তিগত লক্ষ্য"),
        ("coach.add_goal", "লক্ষ্য যোগ করুন"),
        ("coach.goal_title_label", "লক্ষ্যের শিরোনাম"),
        ("coach.goal_priority_low", "কম"),
        ("coach.goal_priority_medium", "মধ্যম"),
        ("coach.goal_priority_high", "উচ্চ"),
        ("coach.goal_save", "সংরক্ষণ করুন"),
        ("coach.no_goals", "এখনও কোনো লক্ষ্য নেই"),
        ("coach.status_all", "সব"),
        ("coach.status_active", "সক্রিয়"),
        ("coach.status_completed", "সম্পন্ন"),
        ("coach.status_paused", "বিরতিপ্রাপ্ত"),
        ("coach.birth_title", "জন্ম বিশ্লেষণ"),
        ("coach.birth_date_label", "জন্ম তারিখ"),
        ("coach.birth_time_label", "জন্ম সময় (ঐচ্ছিক)"),
        ("coach.calculate", "গণনা করুন"),
        ("coach.sun_sign", "সূর্য রাশি"),
        ("coach.element", "মৌল"),
        ("coach.quality", "গুণ"),
        ("coach.season", "ঋতু"),
        ("coach.life_path", "জীবন পথ সংখ্যা"),
        ("coach.life_meaning", "অর্থ"),
        ("coach.numerology_title", "সংখ্যাতত্ত্ব"),
        ("coach.mod_health", "স্বাস্থ্য ও সুস্থতা"),
        ("coach.mod_career", "ক্যারিয়ার পথ"),
        ("coach.mod_relationship", "সম্পর্ক"),
        ("coach.mod_stress", "চাপ ব্যবস্থাপনা"),
        ("coach.mod_confidence", "আত্মবিশ্বাস"),
        ("coach.mod_meditation", "ধ্যান"),
        ("coach.mod_fashion", "স্টাইল ও ফ্যাশন"),
        ("coach.mod_book", "বই সুপারিশ"),
        ("coach.mod_film", "চলচ্চিত্র সুপারিশ"),
        ("coach.mod_music", "সঙ্গীত সুপারিশ"),
        ("coach.mod_travel", "ভ্রমণ সুপারিশ"),
        ("coach.mod_astrology", "জ্যোতিষ চার্ট"),
    ],
    'id': [
        ("coach.hub_title", "Pelatih Kehidupan"),
        ("coach.hub_desc", "Lebih dari 32 modul pelatihan yang dipersonalisasi"),
        ("coach.title", "Pelatih Kehidupan"),
        ("coach.subtitle", "Pelatihan yang dipersonalisasi dari wajah Anda"),
        ("coach.analyze_btn", "Mulai Analisis Pelatih"),
        ("coach.analyzing", "Menganalisis..."),
        ("coach.no_analysis", "Lakukan analisis wajah terlebih dahulu"),
        ("coach.modules_title", "Modul Pelatihan"),
        ("coach.profile_saved", "Profil disimpan"),
        ("coach.birth_btn", "Analisis Kelahiran"),
        ("coach.goals_btn", "Tujuan Saya"),
        ("coach.goals_title", "Tujuan Pribadi"),
        ("coach.add_goal", "Tambah Tujuan"),
        ("coach.goal_title_label", "Judul Tujuan"),
        ("coach.goal_priority_low", "Rendah"),
        ("coach.goal_priority_medium", "Sedang"),
        ("coach.goal_priority_high", "Tinggi"),
        ("coach.goal_save", "Simpan"),
        ("coach.no_goals", "Belum ada tujuan"),
        ("coach.status_all", "Semua"),
        ("coach.status_active", "Aktif"),
        ("coach.status_completed", "Selesai"),
        ("coach.status_paused", "Dijeda"),
        ("coach.birth_title", "Analisis Kelahiran"),
        ("coach.birth_date_label", "Tanggal Lahir"),
        ("coach.birth_time_label", "Waktu Lahir (opsional)"),
        ("coach.calculate", "Hitung"),
        ("coach.sun_sign", "Tanda Matahari"),
        ("coach.element", "Elemen"),
        ("coach.quality", "Kualitas"),
        ("coach.season", "Musim"),
        ("coach.life_path", "Angka Jalur Kehidupan"),
        ("coach.life_meaning", "Arti"),
        ("coach.numerology_title", "Numerologi"),
        ("coach.mod_health", "Kesehatan & Kesejahteraan"),
        ("coach.mod_career", "Jalur Karir"),
        ("coach.mod_relationship", "Hubungan"),
        ("coach.mod_stress", "Manajemen Stres"),
        ("coach.mod_confidence", "Kepercayaan Diri"),
        ("coach.mod_meditation", "Meditasi"),
        ("coach.mod_fashion", "Gaya & Mode"),
        ("coach.mod_book", "Rekomendasi Buku"),
        ("coach.mod_film", "Rekomendasi Film"),
        ("coach.mod_music", "Rekomendasi Musik"),
        ("coach.mod_travel", "Rekomendasi Perjalanan"),
        ("coach.mod_astrology", "Peta Astrologi"),
    ],
    'ur': [
        ("coach.hub_title", "زندگی کا کوچ"),
        ("coach.hub_desc", "32+ ذاتی کوچنگ ماڈیولز"),
        ("coach.title", "زندگی کا کوچ"),
        ("coach.subtitle", "آپ کے چہرے سے ذاتی کوچنگ"),
        ("coach.analyze_btn", "کوچ تجزیہ شروع کریں"),
        ("coach.analyzing", "تجزیہ ہو رہا ہے..."),
        ("coach.no_analysis", "پہلے چہرے کا تجزیہ کریں"),
        ("coach.modules_title", "کوچنگ ماڈیولز"),
        ("coach.profile_saved", "پروفائل محفوظ ہو گئی"),
        ("coach.birth_btn", "پیدائش تجزیہ"),
        ("coach.goals_btn", "میرے اہداف"),
        ("coach.goals_title", "ذاتی اہداف"),
        ("coach.add_goal", "ہدف شامل کریں"),
        ("coach.goal_title_label", "ہدف کا عنوان"),
        ("coach.goal_priority_low", "کم"),
        ("coach.goal_priority_medium", "درمیانہ"),
        ("coach.goal_priority_high", "زیادہ"),
        ("coach.goal_save", "محفوظ کریں"),
        ("coach.no_goals", "ابھی کوئی ہدف نہیں"),
        ("coach.status_all", "سب"),
        ("coach.status_active", "فعال"),
        ("coach.status_completed", "مکمل"),
        ("coach.status_paused", "رکا ہوا"),
        ("coach.birth_title", "پیدائش تجزیہ"),
        ("coach.birth_date_label", "تاریخ پیدائش"),
        ("coach.birth_time_label", "وقت پیدائش (اختیاری)"),
        ("coach.calculate", "حساب کریں"),
        ("coach.sun_sign", "سورج کی علامت"),
        ("coach.element", "عنصر"),
        ("coach.quality", "معیار"),
        ("coach.season", "موسم"),
        ("coach.life_path", "زندگی کا راستہ نمبر"),
        ("coach.life_meaning", "معنی"),
        ("coach.numerology_title", "نیومرولوجی"),
        ("coach.mod_health", "صحت اور تندرستی"),
        ("coach.mod_career", "کیریئر کا راستہ"),
        ("coach.mod_relationship", "تعلقات"),
        ("coach.mod_stress", "تناؤ کا انتظام"),
        ("coach.mod_confidence", "خود اعتمادی"),
        ("coach.mod_meditation", "مراقبہ"),
        ("coach.mod_fashion", "طرز اور فیشن"),
        ("coach.mod_book", "کتاب کی سفارشات"),
        ("coach.mod_film", "فلم کی سفارشات"),
        ("coach.mod_music", "موسیقی کی سفارشات"),
        ("coach.mod_travel", "سفر کی سفارشات"),
        ("coach.mod_astrology", "علم نجوم چارٹ"),
    ],
    'it': [
        ("coach.hub_title", "Life Coach"),
        ("coach.hub_desc", "Più di 32 moduli di coaching personalizzati"),
        ("coach.title", "Life Coach"),
        ("coach.subtitle", "Coaching personalizzato dal tuo viso"),
        ("coach.analyze_btn", "Avvia Analisi Coach"),
        ("coach.analyzing", "Analisi in corso..."),
        ("coach.no_analysis", "Prima esegui un\\'analisi facciale"),
        ("coach.modules_title", "Moduli di Coaching"),
        ("coach.profile_saved", "Profilo salvato"),
        ("coach.birth_btn", "Analisi Nascita"),
        ("coach.goals_btn", "I Miei Obiettivi"),
        ("coach.goals_title", "Obiettivi Personali"),
        ("coach.add_goal", "Aggiungi Obiettivo"),
        ("coach.goal_title_label", "Titolo Obiettivo"),
        ("coach.goal_priority_low", "Basso"),
        ("coach.goal_priority_medium", "Medio"),
        ("coach.goal_priority_high", "Alto"),
        ("coach.goal_save", "Salva"),
        ("coach.no_goals", "Nessun obiettivo ancora"),
        ("coach.status_all", "Tutti"),
        ("coach.status_active", "Attivo"),
        ("coach.status_completed", "Completato"),
        ("coach.status_paused", "In pausa"),
        ("coach.birth_title", "Analisi Nascita"),
        ("coach.birth_date_label", "Data di Nascita"),
        ("coach.birth_time_label", "Ora di Nascita (opzionale)"),
        ("coach.calculate", "Calcola"),
        ("coach.sun_sign", "Segno Solare"),
        ("coach.element", "Elemento"),
        ("coach.quality", "Qualità"),
        ("coach.season", "Stagione"),
        ("coach.life_path", "Numero del Percorso di Vita"),
        ("coach.life_meaning", "Significato"),
        ("coach.numerology_title", "Numerologia"),
        ("coach.mod_health", "Salute e Benessere"),
        ("coach.mod_career", "Percorso di Carriera"),
        ("coach.mod_relationship", "Relazioni"),
        ("coach.mod_stress", "Gestione dello Stress"),
        ("coach.mod_confidence", "Fiducia in Sé"),
        ("coach.mod_meditation", "Meditazione"),
        ("coach.mod_fashion", "Stile e Moda"),
        ("coach.mod_book", "Consigli sui Libri"),
        ("coach.mod_film", "Consigli sui Film"),
        ("coach.mod_music", "Consigli Musicali"),
        ("coach.mod_travel", "Consigli di Viaggio"),
        ("coach.mod_astrology", "Carta Astrologica"),
    ],
    'vi': [
        ("coach.hub_title", "Huấn Luyện Viên Cuộc Sống"),
        ("coach.hub_desc", "Hơn 32 mô-đun huấn luyện cá nhân hóa"),
        ("coach.title", "Huấn Luyện Viên Cuộc Sống"),
        ("coach.subtitle", "Huấn luyện cá nhân hóa từ khuôn mặt của bạn"),
        ("coach.analyze_btn", "Bắt đầu Phân tích Huấn luyện"),
        ("coach.analyzing", "Đang phân tích..."),
        ("coach.no_analysis", "Trước tiên hãy phân tích khuôn mặt"),
        ("coach.modules_title", "Mô-đun Huấn luyện"),
        ("coach.profile_saved", "Hồ sơ đã được lưu"),
        ("coach.birth_btn", "Phân tích Ngày sinh"),
        ("coach.goals_btn", "Mục tiêu của tôi"),
        ("coach.goals_title", "Mục tiêu Cá nhân"),
        ("coach.add_goal", "Thêm Mục tiêu"),
        ("coach.goal_title_label", "Tiêu đề Mục tiêu"),
        ("coach.goal_priority_low", "Thấp"),
        ("coach.goal_priority_medium", "Trung bình"),
        ("coach.goal_priority_high", "Cao"),
        ("coach.goal_save", "Lưu"),
        ("coach.no_goals", "Chưa có mục tiêu"),
        ("coach.status_all", "Tất cả"),
        ("coach.status_active", "Hoạt động"),
        ("coach.status_completed", "Hoàn thành"),
        ("coach.status_paused", "Tạm dừng"),
        ("coach.birth_title", "Phân tích Ngày sinh"),
        ("coach.birth_date_label", "Ngày sinh"),
        ("coach.birth_time_label", "Giờ sinh (tùy chọn)"),
        ("coach.calculate", "Tính toán"),
        ("coach.sun_sign", "Cung Mặt trời"),
        ("coach.element", "Nguyên tố"),
        ("coach.quality", "Chất lượng"),
        ("coach.season", "Mùa"),
        ("coach.life_path", "Số Đường Đời"),
        ("coach.life_meaning", "Ý nghĩa"),
        ("coach.numerology_title", "Số học"),
        ("coach.mod_health", "Sức khỏe & Thể trạng"),
        ("coach.mod_career", "Con đường Sự nghiệp"),
        ("coach.mod_relationship", "Các Mối quan hệ"),
        ("coach.mod_stress", "Quản lý Stress"),
        ("coach.mod_confidence", "Tự tin"),
        ("coach.mod_meditation", "Thiền định"),
        ("coach.mod_fashion", "Phong cách & Thời trang"),
        ("coach.mod_book", "Gợi ý Sách"),
        ("coach.mod_film", "Gợi ý Phim"),
        ("coach.mod_music", "Gợi ý Âm nhạc"),
        ("coach.mod_travel", "Gợi ý Du lịch"),
        ("coach.mod_astrology", "Biểu đồ Chiêm tinh"),
    ],
    'pl': [
        ("coach.hub_title", "Coach Życiowy"),
        ("coach.hub_desc", "Ponad 32 spersonalizowane moduły coachingowe"),
        ("coach.title", "Coach Życiowy"),
        ("coach.subtitle", "Spersonalizowany coaching oparty na Twoim twarzy"),
        ("coach.analyze_btn", "Rozpocznij Analizę Coachingową"),
        ("coach.analyzing", "Analizowanie..."),
        ("coach.no_analysis", "Najpierw wykonaj analizę twarzy"),
        ("coach.modules_title", "Moduły Coachingowe"),
        ("coach.profile_saved", "Profil zapisany"),
        ("coach.birth_btn", "Analiza Urodzin"),
        ("coach.goals_btn", "Moje Cele"),
        ("coach.goals_title", "Cele Osobiste"),
        ("coach.add_goal", "Dodaj Cel"),
        ("coach.goal_title_label", "Tytuł Celu"),
        ("coach.goal_priority_low", "Niski"),
        ("coach.goal_priority_medium", "Średni"),
        ("coach.goal_priority_high", "Wysoki"),
        ("coach.goal_save", "Zapisz"),
        ("coach.no_goals", "Brak celów"),
        ("coach.status_all", "Wszystkie"),
        ("coach.status_active", "Aktywne"),
        ("coach.status_completed", "Zakończone"),
        ("coach.status_paused", "Wstrzymane"),
        ("coach.birth_title", "Analiza Urodzin"),
        ("coach.birth_date_label", "Data Urodzenia"),
        ("coach.birth_time_label", "Godzina Urodzenia (opcjonalnie)"),
        ("coach.calculate", "Oblicz"),
        ("coach.sun_sign", "Znak Słońca"),
        ("coach.element", "Żywioł"),
        ("coach.quality", "Jakość"),
        ("coach.season", "Pora roku"),
        ("coach.life_path", "Liczba Ścieżki Życia"),
        ("coach.life_meaning", "Znaczenie"),
        ("coach.numerology_title", "Numerologia"),
        ("coach.mod_health", "Zdrowie i Samopoczucie"),
        ("coach.mod_career", "Ścieżka Kariery"),
        ("coach.mod_relationship", "Relacje"),
        ("coach.mod_stress", "Zarządzanie Stresem"),
        ("coach.mod_confidence", "Pewność Siebie"),
        ("coach.mod_meditation", "Medytacja"),
        ("coach.mod_fashion", "Styl i Moda"),
        ("coach.mod_book", "Rekomendacje Książek"),
        ("coach.mod_film", "Rekomendacje Filmów"),
        ("coach.mod_music", "Rekomendacje Muzyczne"),
        ("coach.mod_travel", "Rekomendacje Podróżnicze"),
        ("coach.mod_astrology", "Mapa Astrologiczna"),
    ],
}

# Language order as they appear in i18n.ts
LANG_ORDER = ['tr', 'en', 'de', 'ru', 'ar', 'es', 'ko', 'ja', 'zh', 'hi', 'fr', 'pt', 'bn', 'id', 'ur', 'it', 'vi', 'pl']

with open(I18N_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

lines = content.split('\n')

# For each language find the gamification.hub_desc line and insert after it
total_inserted = 0
offset = 0  # line index shift as we insert

for lang in LANG_ORDER:
    if lang not in KEYS:
        continue
    new_keys = KEYS[lang]

    # Find the gamification.hub_desc line for this language (first occurrence after offset)
    target_pattern = "'gamification.hub_desc'"
    found_idx = None
    search_start = offset
    for idx in range(search_start, len(lines)):
        if target_pattern in lines[idx]:
            found_idx = idx
            break

    if found_idx is None:
        print(f"  {lang}: gamification.hub_desc not found — skipping")
        continue

    # Build insertion lines
    insert_lines = []
    for key, value in new_keys:
        insert_lines.append(f"    '{key}': '{value}',")

    # Insert after found_idx
    lines = lines[:found_idx + 1] + insert_lines + lines[found_idx + 1:]
    total_inserted += len(insert_lines)
    print(f"  {lang}: {len(insert_lines)} keys inserted after line {found_idx + 1}")

    # Update offset so next lang search starts after current insertion
    offset = found_idx + len(insert_lines) + 1

with open(I18N_PATH, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'\nDone: {total_inserted} lines inserted total')
