"""Add missing gamification i18n keys — round 2."""
import re

EXTRA_KEYS = {
    'tr': {
        'gamification.features': 'Özellikler',
        'gamification.missions_desc': 'Toplu görevlere katıl',
        'gamification.hub_title': 'Gamification Merkezi',
        'gamification.hub_desc': 'Coin kazan, sıralama yüksel, rozetler topla',
        'gamification.contribute': 'Katkıda Bulun',
        'gamification.mission_complete': 'Görev Tamamlandı',
        'gamification.no_missions': 'Aktif görev yok',
        'leaderboard.your_rank': 'Sıran',
        'leaderboard.rank_change': 'sıra değişimi',
        'leaderboard.days': 'gün',
        'badge.earned': 'Kazanıldı',
        'badge.total': 'Toplam',
        'badge.coins': 'Coin Ödülü',
        'badge.all': 'Tümü',
        'challenge.create': 'Meydan Okuma Oluştur',
        'challenge.abandon': 'Çekil',
        'challenge.abandon_confirm': 'Meydan okumadan çekilmek istediğine emin misin?',
        'challenge.participants': 'Katılımcılar',
        'challenge.ends': 'Bitiş',
        'meal_game.weekly_country': 'Bu haftanın ülkesi',
        'meal_game.guess_sifat': 'Sıfat Tahmin Et',
        'meal_game.guess_prompt': 'Bu yemek hangi kişilik sıfatıyla ilişkilendirilir?',
        'meal_game.correct_sifat': 'Doğru sıfat',
        'discovery.select_type': 'Oyun türü seç',
        'discovery.win_reward': 'kazanma ödülü',
        'discovery.result': 'Sonuç',
        'discovery.accuracy': 'Doğruluk',
        'discovery.play_again': 'Tekrar Oyna',
        'discovery.abandon': 'Oyunu Bırak',
        'discovery.abandon_confirm': 'Oyunu bırakmak istediğine emin misin?',
    },
    'en': {
        'gamification.features': 'Features',
        'gamification.missions_desc': 'Join community missions',
        'gamification.hub_title': 'Gamification Hub',
        'gamification.hub_desc': 'Earn coins, climb the leaderboard, collect badges',
        'gamification.contribute': 'Contribute',
        'gamification.mission_complete': 'Mission Complete',
        'gamification.no_missions': 'No active missions',
        'leaderboard.your_rank': 'Your Rank',
        'leaderboard.rank_change': 'rank change',
        'leaderboard.days': 'days',
        'badge.earned': 'Earned',
        'badge.total': 'Total',
        'badge.coins': 'Coin Reward',
        'badge.all': 'All',
        'challenge.create': 'Create Challenge',
        'challenge.abandon': 'Abandon',
        'challenge.abandon_confirm': 'Are you sure you want to abandon this challenge?',
        'challenge.participants': 'Participants',
        'challenge.ends': 'Ends',
        'meal_game.weekly_country': "This week's country",
        'meal_game.guess_sifat': 'Guess the Trait',
        'meal_game.guess_prompt': 'Which personality trait is associated with this meal?',
        'meal_game.correct_sifat': 'Correct trait',
        'discovery.select_type': 'Select a game type',
        'discovery.win_reward': 'win reward',
        'discovery.result': 'Result',
        'discovery.accuracy': 'Accuracy',
        'discovery.play_again': 'Play Again',
        'discovery.abandon': 'Abandon Game',
        'discovery.abandon_confirm': 'Are you sure you want to abandon this game?',
    },
    'de': {
        'gamification.features': 'Funktionen',
        'gamification.missions_desc': 'Community-Missionen beitreten',
        'gamification.hub_title': 'Gamification-Hub',
        'gamification.hub_desc': 'Münzen verdienen, Rangliste erklimmen, Abzeichen sammeln',
        'gamification.contribute': 'Beitragen',
        'gamification.mission_complete': 'Mission abgeschlossen',
        'gamification.no_missions': 'Keine aktiven Missionen',
        'leaderboard.your_rank': 'Dein Rang',
        'leaderboard.rank_change': 'Rangänderung',
        'leaderboard.days': 'Tage',
        'badge.earned': 'Verdient',
        'badge.total': 'Gesamt',
        'badge.coins': 'Münzbelohnung',
        'badge.all': 'Alle',
        'challenge.create': 'Challenge erstellen',
        'challenge.abandon': 'Aufgeben',
        'challenge.abandon_confirm': 'Möchtest du diese Challenge wirklich aufgeben?',
        'challenge.participants': 'Teilnehmer',
        'challenge.ends': 'Endet',
        'meal_game.weekly_country': 'Land der Woche',
        'meal_game.guess_sifat': 'Eigenschaft erraten',
        'meal_game.guess_prompt': 'Welche Persönlichkeitseigenschaft ist mit diesem Gericht verbunden?',
        'meal_game.correct_sifat': 'Richtige Eigenschaft',
        'discovery.select_type': 'Spieltyp auswählen',
        'discovery.win_reward': 'Siegprämie',
        'discovery.result': 'Ergebnis',
        'discovery.accuracy': 'Genauigkeit',
        'discovery.play_again': 'Nochmal spielen',
        'discovery.abandon': 'Spiel abbrechen',
        'discovery.abandon_confirm': 'Möchtest du dieses Spiel wirklich abbrechen?',
    },
    'ru': {
        'gamification.features': 'Функции',
        'gamification.missions_desc': 'Участвуйте в общественных миссиях',
        'gamification.hub_title': 'Геймификация',
        'gamification.hub_desc': 'Зарабатывайте монеты, поднимайтесь в рейтинге, собирайте значки',
        'gamification.contribute': 'Внести вклад',
        'gamification.mission_complete': 'Миссия выполнена',
        'gamification.no_missions': 'Активных миссий нет',
        'leaderboard.your_rank': 'Ваш ранг',
        'leaderboard.rank_change': 'изменение ранга',
        'leaderboard.days': 'дней',
        'badge.earned': 'Заработано',
        'badge.total': 'Всего',
        'badge.coins': 'Монетная награда',
        'badge.all': 'Все',
        'challenge.create': 'Создать вызов',
        'challenge.abandon': 'Отказаться',
        'challenge.abandon_confirm': 'Вы уверены, что хотите отказаться от этого вызова?',
        'challenge.participants': 'Участники',
        'challenge.ends': 'Заканчивается',
        'meal_game.weekly_country': 'Страна этой недели',
        'meal_game.guess_sifat': 'Угадай черту',
        'meal_game.guess_prompt': 'Какая черта личности связана с этим блюдом?',
        'meal_game.correct_sifat': 'Правильная черта',
        'discovery.select_type': 'Выберите тип игры',
        'discovery.win_reward': 'награда за победу',
        'discovery.result': 'Результат',
        'discovery.accuracy': 'Точность',
        'discovery.play_again': 'Играть снова',
        'discovery.abandon': 'Покинуть игру',
        'discovery.abandon_confirm': 'Вы уверены, что хотите покинуть эту игру?',
    },
    'ar': {
        'gamification.features': 'المميزات',
        'gamification.missions_desc': 'انضم إلى مهام المجتمع',
        'gamification.hub_title': 'مركز الألعاب',
        'gamification.hub_desc': 'اكسب العملات، ارتقِ في الترتيب، اجمع الشارات',
        'gamification.contribute': 'ساهم',
        'gamification.mission_complete': 'اكتملت المهمة',
        'gamification.no_missions': 'لا توجد مهام نشطة',
        'leaderboard.your_rank': 'ترتيبك',
        'leaderboard.rank_change': 'تغيير الترتيب',
        'leaderboard.days': 'أيام',
        'badge.earned': 'مكتسبة',
        'badge.total': 'المجموع',
        'badge.coins': 'مكافأة العملات',
        'badge.all': 'الكل',
        'challenge.create': 'إنشاء تحدي',
        'challenge.abandon': 'التخلي',
        'challenge.abandon_confirm': 'هل أنت متأكد من أنك تريد التخلي عن هذا التحدي؟',
        'challenge.participants': 'المشاركون',
        'challenge.ends': 'ينتهي',
        'meal_game.weekly_country': 'دولة الأسبوع',
        'meal_game.guess_sifat': 'خمّن الصفة',
        'meal_game.guess_prompt': 'ما هي سمة الشخصية المرتبطة بهذه الوجبة؟',
        'meal_game.correct_sifat': 'الصفة الصحيحة',
        'discovery.select_type': 'اختر نوع اللعبة',
        'discovery.win_reward': 'مكافأة الفوز',
        'discovery.result': 'النتيجة',
        'discovery.accuracy': 'الدقة',
        'discovery.play_again': 'العب مرة أخرى',
        'discovery.abandon': 'تخلَّ عن اللعبة',
        'discovery.abandon_confirm': 'هل أنت متأكد من أنك تريد التخلي عن هذه اللعبة؟',
    },
    'es': {
        'gamification.features': 'Características',
        'gamification.missions_desc': 'Únete a misiones comunitarias',
        'gamification.hub_title': 'Centro de Gamificación',
        'gamification.hub_desc': 'Gana monedas, sube en el ranking, colecciona insignias',
        'gamification.contribute': 'Contribuir',
        'gamification.mission_complete': 'Misión completada',
        'gamification.no_missions': 'No hay misiones activas',
        'leaderboard.your_rank': 'Tu posición',
        'leaderboard.rank_change': 'cambio de posición',
        'leaderboard.days': 'días',
        'badge.earned': 'Obtenidas',
        'badge.total': 'Total',
        'badge.coins': 'Recompensa en monedas',
        'badge.all': 'Todas',
        'challenge.create': 'Crear desafío',
        'challenge.abandon': 'Abandonar',
        'challenge.abandon_confirm': '¿Estás seguro de que quieres abandonar este desafío?',
        'challenge.participants': 'Participantes',
        'challenge.ends': 'Termina',
        'meal_game.weekly_country': 'País de la semana',
        'meal_game.guess_sifat': 'Adivina el rasgo',
        'meal_game.guess_prompt': '¿Qué rasgo de personalidad está asociado con esta comida?',
        'meal_game.correct_sifat': 'Rasgo correcto',
        'discovery.select_type': 'Selecciona un tipo de juego',
        'discovery.win_reward': 'recompensa por ganar',
        'discovery.result': 'Resultado',
        'discovery.accuracy': 'Precisión',
        'discovery.play_again': 'Jugar de nuevo',
        'discovery.abandon': 'Abandonar juego',
        'discovery.abandon_confirm': '¿Estás seguro de que quieres abandonar este juego?',
    },
    'ko': {
        'gamification.features': '기능',
        'gamification.missions_desc': '커뮤니티 미션 참여',
        'gamification.hub_title': '게임화 허브',
        'gamification.hub_desc': '코인 획득, 순위 상승, 배지 수집',
        'gamification.contribute': '기여하기',
        'gamification.mission_complete': '미션 완료',
        'gamification.no_missions': '활성 미션 없음',
        'leaderboard.your_rank': '내 순위',
        'leaderboard.rank_change': '순위 변동',
        'leaderboard.days': '일',
        'badge.earned': '획득',
        'badge.total': '전체',
        'badge.coins': '코인 보상',
        'badge.all': '전체',
        'challenge.create': '도전 만들기',
        'challenge.abandon': '포기',
        'challenge.abandon_confirm': '이 도전을 포기하시겠습니까?',
        'challenge.participants': '참가자',
        'challenge.ends': '종료',
        'meal_game.weekly_country': '이번 주 국가',
        'meal_game.guess_sifat': '특성 맞추기',
        'meal_game.guess_prompt': '이 음식과 관련된 성격 특성은 무엇인가요?',
        'meal_game.correct_sifat': '정답 특성',
        'discovery.select_type': '게임 유형 선택',
        'discovery.win_reward': '승리 보상',
        'discovery.result': '결과',
        'discovery.accuracy': '정확도',
        'discovery.play_again': '다시 하기',
        'discovery.abandon': '게임 포기',
        'discovery.abandon_confirm': '이 게임을 포기하시겠습니까?',
    },
    'ja': {
        'gamification.features': '機能',
        'gamification.missions_desc': 'コミュニティミッションに参加',
        'gamification.hub_title': 'ゲーミフィケーションハブ',
        'gamification.hub_desc': 'コインを稼ぎ、ランクを上げ、バッジを集める',
        'gamification.contribute': '貢献する',
        'gamification.mission_complete': 'ミッション完了',
        'gamification.no_missions': 'アクティブなミッションなし',
        'leaderboard.your_rank': 'あなたのランク',
        'leaderboard.rank_change': 'ランク変動',
        'leaderboard.days': '日',
        'badge.earned': '獲得済み',
        'badge.total': '合計',
        'badge.coins': 'コイン報酬',
        'badge.all': 'すべて',
        'challenge.create': 'チャレンジ作成',
        'challenge.abandon': '放棄',
        'challenge.abandon_confirm': 'このチャレンジを放棄しますか？',
        'challenge.participants': '参加者',
        'challenge.ends': '終了',
        'meal_game.weekly_country': '今週の国',
        'meal_game.guess_sifat': '特性を当てる',
        'meal_game.guess_prompt': 'この食事に関連する性格特性は何ですか？',
        'meal_game.correct_sifat': '正解の特性',
        'discovery.select_type': 'ゲームタイプを選択',
        'discovery.win_reward': '勝利報酬',
        'discovery.result': '結果',
        'discovery.accuracy': '正確度',
        'discovery.play_again': 'もう一度プレイ',
        'discovery.abandon': 'ゲームを放棄',
        'discovery.abandon_confirm': 'このゲームを放棄しますか？',
    },
    'zh': {
        'gamification.features': '功能',
        'gamification.missions_desc': '加入社区任务',
        'gamification.hub_title': '游戏化中心',
        'gamification.hub_desc': '赚取金币，提升排名，收集徽章',
        'gamification.contribute': '贡献',
        'gamification.mission_complete': '任务完成',
        'gamification.no_missions': '没有活跃任务',
        'leaderboard.your_rank': '您的排名',
        'leaderboard.rank_change': '排名变化',
        'leaderboard.days': '天',
        'badge.earned': '已获得',
        'badge.total': '总计',
        'badge.coins': '金币奖励',
        'badge.all': '全部',
        'challenge.create': '创建挑战',
        'challenge.abandon': '放弃',
        'challenge.abandon_confirm': '您确定要放弃这个挑战吗？',
        'challenge.participants': '参与者',
        'challenge.ends': '结束',
        'meal_game.weekly_country': '本周国家',
        'meal_game.guess_sifat': '猜测特质',
        'meal_game.guess_prompt': '这道菜与哪种人格特质相关？',
        'meal_game.correct_sifat': '正确特质',
        'discovery.select_type': '选择游戏类型',
        'discovery.win_reward': '获胜奖励',
        'discovery.result': '结果',
        'discovery.accuracy': '准确率',
        'discovery.play_again': '再玩一次',
        'discovery.abandon': '放弃游戏',
        'discovery.abandon_confirm': '您确定要放弃这个游戏吗？',
    },
    'hi': {
        'gamification.features': 'विशेषताएं',
        'gamification.missions_desc': 'सामुदायिक मिशन में शामिल हों',
        'gamification.hub_title': 'गेमिफिकेशन हब',
        'gamification.hub_desc': 'सिक्के कमाएं, रैंकिंग में चढ़ें, बैज इकट्ठा करें',
        'gamification.contribute': 'योगदान करें',
        'gamification.mission_complete': 'मिशन पूर्ण',
        'gamification.no_missions': 'कोई सक्रिय मिशन नहीं',
        'leaderboard.your_rank': 'आपकी रैंक',
        'leaderboard.rank_change': 'रैंक परिवर्तन',
        'leaderboard.days': 'दिन',
        'badge.earned': 'अर्जित',
        'badge.total': 'कुल',
        'badge.coins': 'सिक्का पुरस्कार',
        'badge.all': 'सभी',
        'challenge.create': 'चुनौती बनाएं',
        'challenge.abandon': 'छोड़ें',
        'challenge.abandon_confirm': 'क्या आप वाकई इस चुनौती को छोड़ना चाहते हैं?',
        'challenge.participants': 'प्रतिभागी',
        'challenge.ends': 'समाप्त',
        'meal_game.weekly_country': 'इस सप्ताह का देश',
        'meal_game.guess_sifat': 'विशेषता अनुमान लगाएं',
        'meal_game.guess_prompt': 'इस भोजन से कौन सी व्यक्तित्व विशेषता जुड़ी है?',
        'meal_game.correct_sifat': 'सही विशेषता',
        'discovery.select_type': 'गेम प्रकार चुनें',
        'discovery.win_reward': 'जीत पुरस्कार',
        'discovery.result': 'परिणाम',
        'discovery.accuracy': 'सटीकता',
        'discovery.play_again': 'फिर से खेलें',
        'discovery.abandon': 'गेम छोड़ें',
        'discovery.abandon_confirm': 'क्या आप वाकई यह गेम छोड़ना चाहते हैं?',
    },
    'fr': {
        'gamification.features': 'Fonctionnalités',
        'gamification.missions_desc': 'Rejoindre les missions communautaires',
        'gamification.hub_title': 'Hub de Gamification',
        'gamification.hub_desc': "Gagnez des pièces, montez dans le classement, collectez des badges",
        'gamification.contribute': 'Contribuer',
        'gamification.mission_complete': 'Mission accomplie',
        'gamification.no_missions': 'Aucune mission active',
        'leaderboard.your_rank': 'Votre rang',
        'leaderboard.rank_change': 'changement de rang',
        'leaderboard.days': 'jours',
        'badge.earned': 'Gagnés',
        'badge.total': 'Total',
        'badge.coins': 'Récompense en pièces',
        'badge.all': 'Tous',
        'challenge.create': 'Créer un défi',
        'challenge.abandon': 'Abandonner',
        'challenge.abandon_confirm': 'Êtes-vous sûr de vouloir abandonner ce défi?',
        'challenge.participants': 'Participants',
        'challenge.ends': 'Se termine',
        'meal_game.weekly_country': 'Pays de la semaine',
        'meal_game.guess_sifat': 'Deviner le trait',
        'meal_game.guess_prompt': 'Quel trait de personnalité est associé à ce repas?',
        'meal_game.correct_sifat': 'Trait correct',
        'discovery.select_type': 'Sélectionner un type de jeu',
        'discovery.win_reward': 'récompense de victoire',
        'discovery.result': 'Résultat',
        'discovery.accuracy': 'Précision',
        'discovery.play_again': 'Rejouer',
        'discovery.abandon': 'Quitter le jeu',
        'discovery.abandon_confirm': 'Êtes-vous sûr de vouloir quitter ce jeu?',
    },
    'pt': {
        'gamification.features': 'Recursos',
        'gamification.missions_desc': 'Participe de missões comunitárias',
        'gamification.hub_title': 'Hub de Gamificação',
        'gamification.hub_desc': 'Ganhe moedas, suba no ranking, colecione distintivos',
        'gamification.contribute': 'Contribuir',
        'gamification.mission_complete': 'Missão concluída',
        'gamification.no_missions': 'Sem missões ativas',
        'leaderboard.your_rank': 'Sua posição',
        'leaderboard.rank_change': 'mudança de posição',
        'leaderboard.days': 'dias',
        'badge.earned': 'Ganhos',
        'badge.total': 'Total',
        'badge.coins': 'Recompensa em moedas',
        'badge.all': 'Todos',
        'challenge.create': 'Criar desafio',
        'challenge.abandon': 'Abandonar',
        'challenge.abandon_confirm': 'Tem certeza de que deseja abandonar este desafio?',
        'challenge.participants': 'Participantes',
        'challenge.ends': 'Termina',
        'meal_game.weekly_country': 'País da semana',
        'meal_game.guess_sifat': 'Adivinhar o traço',
        'meal_game.guess_prompt': 'Qual traço de personalidade está associado a esta refeição?',
        'meal_game.correct_sifat': 'Traço correto',
        'discovery.select_type': 'Selecione um tipo de jogo',
        'discovery.win_reward': 'recompensa por vencer',
        'discovery.result': 'Resultado',
        'discovery.accuracy': 'Precisão',
        'discovery.play_again': 'Jogar novamente',
        'discovery.abandon': 'Abandonar jogo',
        'discovery.abandon_confirm': 'Tem certeza de que deseja abandonar este jogo?',
    },
    'bn': {
        'gamification.features': 'বৈশিষ্ট্য',
        'gamification.missions_desc': 'কমিউনিটি মিশনে যোগ দিন',
        'gamification.hub_title': 'গেমিফিকেশন হাব',
        'gamification.hub_desc': 'কয়েন উপার্জন করুন, র‌্যাংকিং বাড়ান, ব্যাজ সংগ্রহ করুন',
        'gamification.contribute': 'অবদান রাখুন',
        'gamification.mission_complete': 'মিশন সম্পন্ন',
        'gamification.no_missions': 'কোনো সক্রিয় মিশন নেই',
        'leaderboard.your_rank': 'আপনার র‌্যাংক',
        'leaderboard.rank_change': 'র‌্যাংক পরিবর্তন',
        'leaderboard.days': 'দিন',
        'badge.earned': 'অর্জিত',
        'badge.total': 'মোট',
        'badge.coins': 'কয়েন পুরস্কার',
        'badge.all': 'সব',
        'challenge.create': 'চ্যালেঞ্জ তৈরি করুন',
        'challenge.abandon': 'ছেড়ে দিন',
        'challenge.abandon_confirm': 'আপনি কি সত্যিই এই চ্যালেঞ্জ ছেড়ে দিতে চান?',
        'challenge.participants': 'অংশগ্রহণকারীরা',
        'challenge.ends': 'শেষ হয়',
        'meal_game.weekly_country': 'এই সপ্তাহের দেশ',
        'meal_game.guess_sifat': 'বৈশিষ্ট্য অনুমান করুন',
        'meal_game.guess_prompt': 'এই খাবারের সাথে কোন ব্যক্তিত্বের বৈশিষ্ট্য জড়িত?',
        'meal_game.correct_sifat': 'সঠিক বৈশিষ্ট্য',
        'discovery.select_type': 'গেমের ধরন বেছে নিন',
        'discovery.win_reward': 'জয়ের পুরস্কার',
        'discovery.result': 'ফলাফল',
        'discovery.accuracy': 'নির্ভুলতা',
        'discovery.play_again': 'আবার খেলুন',
        'discovery.abandon': 'গেম ছেড়ে দিন',
        'discovery.abandon_confirm': 'আপনি কি সত্যিই এই গেম ছেড়ে দিতে চান?',
    },
    'id': {
        'gamification.features': 'Fitur',
        'gamification.missions_desc': 'Bergabung dengan misi komunitas',
        'gamification.hub_title': 'Hub Gamifikasi',
        'gamification.hub_desc': 'Dapatkan koin, naiki peringkat, kumpulkan lencana',
        'gamification.contribute': 'Berkontribusi',
        'gamification.mission_complete': 'Misi selesai',
        'gamification.no_missions': 'Tidak ada misi aktif',
        'leaderboard.your_rank': 'Peringkat Anda',
        'leaderboard.rank_change': 'perubahan peringkat',
        'leaderboard.days': 'hari',
        'badge.earned': 'Diperoleh',
        'badge.total': 'Total',
        'badge.coins': 'Hadiah koin',
        'badge.all': 'Semua',
        'challenge.create': 'Buat tantangan',
        'challenge.abandon': 'Mundur',
        'challenge.abandon_confirm': 'Apakah Anda yakin ingin mundur dari tantangan ini?',
        'challenge.participants': 'Peserta',
        'challenge.ends': 'Berakhir',
        'meal_game.weekly_country': 'Negara minggu ini',
        'meal_game.guess_sifat': 'Tebak sifat',
        'meal_game.guess_prompt': 'Sifat kepribadian apa yang terkait dengan makanan ini?',
        'meal_game.correct_sifat': 'Sifat yang benar',
        'discovery.select_type': 'Pilih jenis permainan',
        'discovery.win_reward': 'hadiah menang',
        'discovery.result': 'Hasil',
        'discovery.accuracy': 'Akurasi',
        'discovery.play_again': 'Main lagi',
        'discovery.abandon': 'Tinggalkan permainan',
        'discovery.abandon_confirm': 'Apakah Anda yakin ingin meninggalkan permainan ini?',
    },
    'ur': {
        'gamification.features': 'خصوصیات',
        'gamification.missions_desc': 'کمیونٹی مشنز میں شامل ہوں',
        'gamification.hub_title': 'گیمیفیکیشن ہب',
        'gamification.hub_desc': 'کوائن کمائیں، رینکنگ بڑھائیں، بیجز اکٹھے کریں',
        'gamification.contribute': 'حصہ ڈالیں',
        'gamification.mission_complete': 'مشن مکمل',
        'gamification.no_missions': 'کوئی فعال مشن نہیں',
        'leaderboard.your_rank': 'آپ کی رینک',
        'leaderboard.rank_change': 'رینک تبدیلی',
        'leaderboard.days': 'دن',
        'badge.earned': 'حاصل کردہ',
        'badge.total': 'کل',
        'badge.coins': 'کوائن انعام',
        'badge.all': 'سب',
        'challenge.create': 'چیلنج بنائیں',
        'challenge.abandon': 'چھوڑیں',
        'challenge.abandon_confirm': 'کیا آپ واقعی اس چیلنج کو چھوڑنا چاہتے ہیں؟',
        'challenge.participants': 'شرکاء',
        'challenge.ends': 'ختم ہوتا ہے',
        'meal_game.weekly_country': 'اس ہفتے کا ملک',
        'meal_game.guess_sifat': 'صفت کا اندازہ لگائیں',
        'meal_game.guess_prompt': 'اس کھانے سے کون سی شخصیت کی صفت جڑی ہے؟',
        'meal_game.correct_sifat': 'درست صفت',
        'discovery.select_type': 'گیم کی قسم منتخب کریں',
        'discovery.win_reward': 'جیتنے کا انعام',
        'discovery.result': 'نتیجہ',
        'discovery.accuracy': 'درستگی',
        'discovery.play_again': 'دوبارہ کھیلیں',
        'discovery.abandon': 'گیم چھوڑیں',
        'discovery.abandon_confirm': 'کیا آپ واقعی یہ گیم چھوڑنا چاہتے ہیں؟',
    },
    'it': {
        'gamification.features': 'Funzionalità',
        'gamification.missions_desc': 'Partecipa alle missioni della comunità',
        'gamification.hub_title': 'Hub Gamification',
        'gamification.hub_desc': 'Guadagna monete, scala la classifica, raccogli badge',
        'gamification.contribute': 'Contribuisci',
        'gamification.mission_complete': 'Missione completata',
        'gamification.no_missions': 'Nessuna missione attiva',
        'leaderboard.your_rank': 'Il tuo rango',
        'leaderboard.rank_change': 'cambio di rango',
        'leaderboard.days': 'giorni',
        'badge.earned': 'Guadagnati',
        'badge.total': 'Totale',
        'badge.coins': 'Ricompensa in monete',
        'badge.all': 'Tutti',
        'challenge.create': 'Crea sfida',
        'challenge.abandon': 'Abbandona',
        'challenge.abandon_confirm': 'Sei sicuro di voler abbandonare questa sfida?',
        'challenge.participants': 'Partecipanti',
        'challenge.ends': 'Termina',
        'meal_game.weekly_country': 'Paese della settimana',
        'meal_game.guess_sifat': 'Indovina il tratto',
        'meal_game.guess_prompt': 'Quale tratto della personalità è associato a questo pasto?',
        'meal_game.correct_sifat': 'Tratto corretto',
        'discovery.select_type': 'Seleziona un tipo di gioco',
        'discovery.win_reward': 'ricompensa per la vittoria',
        'discovery.result': 'Risultato',
        'discovery.accuracy': 'Precisione',
        'discovery.play_again': 'Gioca ancora',
        'discovery.abandon': 'Abbandona il gioco',
        'discovery.abandon_confirm': 'Sei sicuro di voler abbandonare questo gioco?',
    },
    'vi': {
        'gamification.features': 'Tính năng',
        'gamification.missions_desc': 'Tham gia nhiệm vụ cộng đồng',
        'gamification.hub_title': 'Trung tâm Gamification',
        'gamification.hub_desc': 'Kiếm xu, leo bảng xếp hạng, sưu tập huy hiệu',
        'gamification.contribute': 'Đóng góp',
        'gamification.mission_complete': 'Nhiệm vụ hoàn thành',
        'gamification.no_missions': 'Không có nhiệm vụ đang hoạt động',
        'leaderboard.your_rank': 'Xếp hạng của bạn',
        'leaderboard.rank_change': 'thay đổi xếp hạng',
        'leaderboard.days': 'ngày',
        'badge.earned': 'Đã đạt',
        'badge.total': 'Tổng',
        'badge.coins': 'Phần thưởng xu',
        'badge.all': 'Tất cả',
        'challenge.create': 'Tạo thách thức',
        'challenge.abandon': 'Từ bỏ',
        'challenge.abandon_confirm': 'Bạn có chắc muốn từ bỏ thách thức này không?',
        'challenge.participants': 'Người tham gia',
        'challenge.ends': 'Kết thúc',
        'meal_game.weekly_country': 'Quốc gia tuần này',
        'meal_game.guess_sifat': 'Đoán đặc điểm',
        'meal_game.guess_prompt': 'Đặc điểm tính cách nào liên quan đến bữa ăn này?',
        'meal_game.correct_sifat': 'Đặc điểm đúng',
        'discovery.select_type': 'Chọn loại trò chơi',
        'discovery.win_reward': 'phần thưởng chiến thắng',
        'discovery.result': 'Kết quả',
        'discovery.accuracy': 'Độ chính xác',
        'discovery.play_again': 'Chơi lại',
        'discovery.abandon': 'Bỏ trò chơi',
        'discovery.abandon_confirm': 'Bạn có chắc muốn bỏ trò chơi này không?',
    },
    'pl': {
        'gamification.features': 'Funkcje',
        'gamification.missions_desc': 'Dołącz do misji społeczności',
        'gamification.hub_title': 'Hub Grywalizacji',
        'gamification.hub_desc': 'Zdobywaj monety, wspinaj się w rankingu, zbieraj odznaki',
        'gamification.contribute': 'Przyczynić się',
        'gamification.mission_complete': 'Misja ukończona',
        'gamification.no_missions': 'Brak aktywnych misji',
        'leaderboard.your_rank': 'Twoja pozycja',
        'leaderboard.rank_change': 'zmiana pozycji',
        'leaderboard.days': 'dni',
        'badge.earned': 'Zdobyte',
        'badge.total': 'Łącznie',
        'badge.coins': 'Nagroda monet',
        'badge.all': 'Wszystkie',
        'challenge.create': 'Utwórz wyzwanie',
        'challenge.abandon': 'Porzuć',
        'challenge.abandon_confirm': 'Czy na pewno chcesz porzucić to wyzwanie?',
        'challenge.participants': 'Uczestnicy',
        'challenge.ends': 'Kończy się',
        'meal_game.weekly_country': 'Kraj tygodnia',
        'meal_game.guess_sifat': 'Zgadnij cechę',
        'meal_game.guess_prompt': 'Jaka cecha osobowości jest związana z tym posiłkiem?',
        'meal_game.correct_sifat': 'Poprawna cecha',
        'discovery.select_type': 'Wybierz typ gry',
        'discovery.win_reward': 'nagroda za wygraną',
        'discovery.result': 'Wynik',
        'discovery.accuracy': 'Dokładność',
        'discovery.play_again': 'Zagraj ponownie',
        'discovery.abandon': 'Porzuć grę',
        'discovery.abandon_confirm': 'Czy na pewno chcesz porzucić tę grę?',
    },
}

I18N_PATH = r'facesyma_mobile\src\utils\i18n.ts'

with open(I18N_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

total_inserted = 0
for lang, keys in EXTRA_KEYS.items():
    # Find the diet.empty line for this language block
    # Strategy: find "\n  LANG: {" then find "\n    'diet.empty':" within it
    lang_marker = f'\n  {lang}: {{'
    lang_pos = content.find(lang_marker)
    if lang_pos == -1:
        print(f'  {lang}: language block NOT FOUND, skipping')
        continue

    # Find diet.empty after lang_pos
    diet_marker = "\n    'diet.empty':"
    diet_pos = content.find(diet_marker, lang_pos)
    if diet_pos == -1:
        print(f'  {lang}: diet.empty NOT FOUND, skipping')
        continue

    # Find end of the diet.empty line
    line_end = content.find('\n', diet_pos + 1)
    if line_end == -1:
        print(f'  {lang}: could not find line end, skipping')
        continue

    # Build insertion string — only insert keys not already present
    lines_to_insert = []
    block_end = content.find('\n  },', lang_pos)
    if block_end == -1:
        block_end = lang_pos + 5000  # fallback

    block_text = content[lang_pos:block_end]
    for k, v in keys.items():
        if f"'{k}':" in block_text:
            continue  # already present
        escaped = v.replace("'", "\\'")
        lines_to_insert.append(f"    '{k}': '{escaped}',")

    if not lines_to_insert:
        print(f'  {lang}: all keys already present')
        continue

    insertion = '\n' + '\n'.join(lines_to_insert)
    content = content[:line_end] + insertion + content[line_end:]
    print(f'  {lang}: +{len(lines_to_insert)} keys inserted')
    total_inserted += len(lines_to_insert)

with open(I18N_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\nDone: {total_inserted} total insertions across {len(EXTRA_KEYS)} languages')
