"""
art_pool_data.py
================
52 iconic artworks — TR+EN seed data for the art_pool MongoDB collection.

Fields:
  id            unique string key
  has_portrait  bool — True if the work contains a face (enables geo scoring)
  emoji         display emoji
  geo           jaw_width / face_len_ratio / eye_distance  (portrait only)
  clusters      personality cluster weights 0-1
  image_url     Wikimedia Commons public-domain thumbnail
  title_tr/en   artwork title
  artist_tr/en  artist name
  year          creation date string
  museum_tr/en  holding institution
  style_tr/en   art movement / style
  reason_tr/en  1-2 sentence "why this artwork matches you"
"""

ART_POOL = [

    # ── RENAISSANCE ───────────────────────────────────────────────────────────
    {
        "id": "artwork_mona_lisa",
        "has_portrait": True,
        "emoji": "🖼",
        "geo": {"jaw_width": 0.82, "face_len_ratio": 1.48, "eye_distance": 0.90},
        "clusters": {"intelligence": 0.95, "mystery": 0.85, "creativity": 0.70, "discipline": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/402px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
        "title_tr": "Mona Lisa", "title_en": "Mona Lisa",
        "artist_tr": "Leonardo da Vinci", "artist_en": "Leonardo da Vinci",
        "year": "1503–1519",
        "museum_tr": "Louvre Müzesi, Paris", "museum_en": "Louvre Museum, Paris",
        "style_tr": "Rönesans Portresi", "style_en": "Renaissance Portrait",
        "reason_tr": "Gizemli bakışlar ve sonsuz bir derinlik taşıyan yüzünüz bu başyapıtla buluşuyor.",
        "reason_en": "Your face carries a mysterious gaze and infinite depth that mirrors this masterpiece.",
    },
    {
        "id": "artwork_birth_of_venus",
        "has_portrait": True,
        "emoji": "🌊",
        "geo": {"jaw_width": 0.78, "face_len_ratio": 1.52, "eye_distance": 0.86},
        "clusters": {"creativity": 0.90, "empathy": 0.80, "social": 0.70, "charisma": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sandro_Botticelli_046.jpg/800px-Sandro_Botticelli_046.jpg",
        "title_tr": "Venüs'ün Doğuşu", "title_en": "The Birth of Venus",
        "artist_tr": "Sandro Botticelli", "artist_en": "Sandro Botticelli",
        "year": "1484–1486",
        "museum_tr": "Uffizi Galerisi, Floransa", "museum_en": "Uffizi Gallery, Florence",
        "style_tr": "Rönesans İdeali", "style_en": "Renaissance Ideal",
        "reason_tr": "Doğal zarafet ve karizmanız Botticelli'nin ilahi güzellik idealini yansıtıyor.",
        "reason_en": "Your natural grace and charisma reflect Botticelli's divine ideal of beauty.",
    },
    {
        "id": "artwork_sistine_creation",
        "has_portrait": False,
        "emoji": "✨",
        "geo": {},
        "clusters": {"creativity": 0.95, "intelligence": 0.85, "strength": 0.80, "leadership": 0.90},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/800px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg",
        "title_tr": "Âdem'in Yaratılışı", "title_en": "The Creation of Adam",
        "artist_tr": "Michelangelo", "artist_en": "Michelangelo",
        "year": "1508–1512",
        "museum_tr": "Sistine Şapeli, Vatikan", "museum_en": "Sistine Chapel, Vatican",
        "style_tr": "Rönesans Freskosu", "style_en": "Renaissance Fresco",
        "reason_tr": "Liderlik gücünüz ve yaratıcı zekanız sizi bu evrensel başyapıtla buluşturuyor.",
        "reason_en": "Your leadership strength and creative intelligence connect you to this universal masterpiece.",
    },
    {
        "id": "artwork_school_of_athens",
        "has_portrait": False,
        "emoji": "🏛",
        "geo": {},
        "clusters": {"intelligence": 0.95, "social": 0.80, "leadership": 0.80, "discipline": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/800px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
        "title_tr": "Atina Okulu", "title_en": "The School of Athens",
        "artist_tr": "Raffaello", "artist_en": "Raphael",
        "year": "1509–1511",
        "museum_tr": "Vatikan Müzeleri, Roma", "museum_en": "Vatican Museums, Rome",
        "style_tr": "Rönesans Freskosu", "style_en": "Renaissance Fresco",
        "reason_tr": "Analitik zekanız ve insanları bir araya getirme gücünüz bu ebedi tabloda yankı bulur.",
        "reason_en": "Your analytical intelligence and ability to unite people echo in this timeless fresco.",
    },

    # ── BAROQUE ───────────────────────────────────────────────────────────────
    {
        "id": "artwork_pearl_earring",
        "has_portrait": True,
        "emoji": "💎",
        "geo": {"jaw_width": 0.80, "face_len_ratio": 1.50, "eye_distance": 0.88},
        "clusters": {"mystery": 0.90, "empathy": 0.80, "charisma": 0.85, "creativity": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/354px-1665_Girl_with_a_Pearl_Earring.jpg",
        "title_tr": "İnci Küpeli Kız", "title_en": "Girl with a Pearl Earring",
        "artist_tr": "Johannes Vermeer", "artist_en": "Johannes Vermeer",
        "year": "1665",
        "museum_tr": "Mauritshuis, La Haye", "museum_en": "Mauritshuis, The Hague",
        "style_tr": "Hollanda Altın Çağı", "style_en": "Dutch Golden Age",
        "reason_tr": "Bakışlarınızdaki gizemli derinlik ve sezgisel güzellik bu eşsiz portreyle örtüşüyor.",
        "reason_en": "The mysterious depth in your gaze and intuitive beauty mirror this unique portrait.",
    },
    {
        "id": "artwork_night_watch",
        "has_portrait": False,
        "emoji": "🛡",
        "geo": {},
        "clusters": {"leadership": 0.90, "strength": 0.80, "social": 0.75, "discipline": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/800px-The_Night_Watch_-_HD.jpg",
        "title_tr": "Gece Devriyesi", "title_en": "The Night Watch",
        "artist_tr": "Rembrandt van Rijn", "artist_en": "Rembrandt van Rijn",
        "year": "1642",
        "museum_tr": "Rijksmuseum, Amsterdam", "museum_en": "Rijksmuseum, Amsterdam",
        "style_tr": "Barok Grup Portresi", "style_en": "Baroque Group Portrait",
        "reason_tr": "Doğal liderliğiniz ve karizmanız Rembrandt'ın ışıkla yarattığı güç sahnesinde yaşıyor.",
        "reason_en": "Your natural leadership and charisma live in Rembrandt's powerful drama of light.",
    },
    {
        "id": "artwork_rembrandt_self",
        "has_portrait": True,
        "emoji": "🎭",
        "geo": {"jaw_width": 0.88, "face_len_ratio": 1.40, "eye_distance": 0.92},
        "clusters": {"intelligence": 0.90, "mystery": 0.85, "discipline": 0.80, "empathy": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg/564px-Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg",
        "title_tr": "Otoportre", "title_en": "Self-Portrait",
        "artist_tr": "Rembrandt van Rijn", "artist_en": "Rembrandt van Rijn",
        "year": "1659",
        "museum_tr": "Ulusal Sanat Galerisi, Washington", "museum_en": "National Gallery of Art, Washington",
        "style_tr": "Barok Realizm", "style_en": "Baroque Realism",
        "reason_tr": "Derin iç dünyası ve hayatın izlerini yüzünde taşıyan bir ruh size yakışır.",
        "reason_en": "A deep inner world and a face that carries life's traces — this portrait is yours.",
    },
    {
        "id": "artwork_las_meninas",
        "has_portrait": False,
        "emoji": "👑",
        "geo": {},
        "clusters": {"intelligence": 0.85, "mystery": 0.80, "social": 0.75, "creativity": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/800px-Las_Meninas_01.jpg",
        "title_tr": "Las Meninas", "title_en": "Las Meninas",
        "artist_tr": "Diego Velázquez", "artist_en": "Diego Velázquez",
        "year": "1656",
        "museum_tr": "Prado Müzesi, Madrid", "museum_en": "Prado Museum, Madrid",
        "style_tr": "Barok Saray Resmi", "style_en": "Baroque Court Painting",
        "reason_tr": "Gizemi ve zekayı aynı anda taşımanız bu çok katmanlı başyapıtı size yakın kılıyor.",
        "reason_en": "Carrying mystery and intelligence simultaneously brings you close to this layered masterpiece.",
    },

    # ── ROMANTİZM ─────────────────────────────────────────────────────────────
    {
        "id": "artwork_liberty_leading",
        "has_portrait": False,
        "emoji": "🗽",
        "geo": {},
        "clusters": {"leadership": 0.95, "strength": 0.90, "social": 0.80, "charisma": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg/800px-Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg",
        "title_tr": "Özgürlük Halka Yol Gösteriyor", "title_en": "Liberty Leading the People",
        "artist_tr": "Eugène Delacroix", "artist_en": "Eugène Delacroix",
        "year": "1830",
        "museum_tr": "Louvre Müzesi, Paris", "museum_en": "Louvre Museum, Paris",
        "style_tr": "Romantizm", "style_en": "Romanticism",
        "reason_tr": "İnsanları harekete geçiren liderlik enerjiniz bu tarihi tuvale yansımış.",
        "reason_en": "Your energy to move people and lead change is reflected in this historic canvas.",
    },
    {
        "id": "artwork_wanderer",
        "has_portrait": False,
        "emoji": "🌫",
        "geo": {},
        "clusters": {"mystery": 0.95, "patience": 0.80, "intelligence": 0.75, "creativity": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/554px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg",
        "title_tr": "Sis Denizi Üzerindeki Gezgin", "title_en": "Wanderer above the Sea of Fog",
        "artist_tr": "Caspar David Friedrich", "artist_en": "Caspar David Friedrich",
        "year": "1818",
        "museum_tr": "Kunsthalle, Hamburg", "museum_en": "Kunsthalle Hamburg",
        "style_tr": "Alman Romantizmi", "style_en": "German Romanticism",
        "reason_tr": "Sonsuz ufuklara bakan gizemli iç dünyanız bu derin tabloda can buluyor.",
        "reason_en": "Your mysterious inner world gazing at infinite horizons comes alive in this painting.",
    },
    {
        "id": "artwork_third_of_may",
        "has_portrait": False,
        "emoji": "✊",
        "geo": {},
        "clusters": {"strength": 0.90, "empathy": 0.85, "leadership": 0.75, "social": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_in_Google_Earth.jpg/800px-El_Tres_de_Mayo%2C_by_Francisco_de_Goya%2C_from_Prado_in_Google_Earth.jpg",
        "title_tr": "3 Mayıs 1808", "title_en": "The Third of May 1808",
        "artist_tr": "Francisco Goya", "artist_en": "Francisco Goya",
        "year": "1814",
        "museum_tr": "Prado Müzesi, Madrid", "museum_en": "Prado Museum, Madrid",
        "style_tr": "Romantizm", "style_en": "Romanticism",
        "reason_tr": "Başkalarının acısını derinden hissetme yetiniz ve direnç gücünüz bu eserde yankılanır.",
        "reason_en": "Your capacity to feel others' pain deeply and your resilience echo in this work.",
    },

    # ── İZLENİMCİLİK ─────────────────────────────────────────────────────────
    {
        "id": "artwork_water_lilies",
        "has_portrait": False,
        "emoji": "🪷",
        "geo": {},
        "clusters": {"creativity": 0.90, "patience": 0.85, "empathy": 0.80, "mystery": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/800px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg",
        "title_tr": "Nilüferler", "title_en": "Water Lilies",
        "artist_tr": "Claude Monet", "artist_en": "Claude Monet",
        "year": "1906",
        "museum_tr": "Sanat Enstitüsü, Chicago", "museum_en": "Art Institute of Chicago",
        "style_tr": "İzlenimcilik", "style_en": "Impressionism",
        "reason_tr": "Dinginlik içinde taşıdığınız derin yaratıcılık ve sabır bu eserde akıp gidiyor.",
        "reason_en": "The deep creativity and patience you carry in tranquility flow through this work.",
    },
    {
        "id": "artwork_moulin_galette",
        "has_portrait": False,
        "emoji": "💃",
        "geo": {},
        "clusters": {"social": 0.95, "empathy": 0.85, "charisma": 0.80, "creativity": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg/800px-Pierre-Auguste_Renoir%2C_Le_Moulin_de_la_Galette.jpg",
        "title_tr": "Moulin de la Galette Balosu", "title_en": "Dance at Le Moulin de la Galette",
        "artist_tr": "Pierre-Auguste Renoir", "artist_en": "Pierre-Auguste Renoir",
        "year": "1876",
        "museum_tr": "Musée d'Orsay, Paris", "museum_en": "Musée d'Orsay, Paris",
        "style_tr": "İzlenimcilik", "style_en": "Impressionism",
        "reason_tr": "İnsanlarla kurduğunuz derin bağ ve sosyal karizmanız bu canlı sahneye yansımış.",
        "reason_en": "Your deep social bond with people and vibrant charisma are reflected in this lively scene.",
    },
    {
        "id": "artwork_grande_jatte",
        "has_portrait": False,
        "emoji": "☀️",
        "geo": {},
        "clusters": {"social": 0.85, "patience": 0.90, "discipline": 0.80, "creativity": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg/800px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884-86.jpg",
        "title_tr": "Grande Jatte Adası'nda Bir Pazar", "title_en": "A Sunday on La Grande Jatte",
        "artist_tr": "Georges Seurat", "artist_en": "Georges Seurat",
        "year": "1886",
        "museum_tr": "Sanat Enstitüsü, Chicago", "museum_en": "Art Institute of Chicago",
        "style_tr": "Noktacılık", "style_en": "Pointillism",
        "reason_tr": "Sabırlı ve metodolojik yaklaşımınız binlerce noktanın mükemmelliğinde kendini buluyor.",
        "reason_en": "Your patient and methodical approach finds itself in the perfection of thousands of dots.",
    },
    {
        "id": "artwork_absinthe_degas",
        "has_portrait": True,
        "emoji": "🍵",
        "geo": {"jaw_width": 0.85, "face_len_ratio": 1.42, "eye_distance": 0.91},
        "clusters": {"empathy": 0.90, "mystery": 0.80, "social": 0.65, "patience": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg/800px-Edgar_Degas_-_In_a_Caf%C3%A9_-_Google_Art_Project_2.jpg",
        "title_tr": "Kafede", "title_en": "In a Café (L'Absinthe)",
        "artist_tr": "Edgar Degas", "artist_en": "Edgar Degas",
        "year": "1876",
        "museum_tr": "Musée d'Orsay, Paris", "museum_en": "Musée d'Orsay, Paris",
        "style_tr": "İzlenimcilik", "style_en": "Impressionism",
        "reason_tr": "Gözlemci ruhunuz ve insanların iç dünyasına duyduğunuz empati bu portreyi size yakın kılıyor.",
        "reason_en": "Your observant spirit and empathy for people's inner worlds bring this portrait close to you.",
    },

    # ── POST-İZLENİMCİLİK ─────────────────────────────────────────────────────
    {
        "id": "artwork_starry_night",
        "has_portrait": False,
        "emoji": "🌌",
        "geo": {},
        "clusters": {"creativity": 0.95, "mystery": 0.90, "empathy": 0.80, "strength": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/757px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
        "title_tr": "Yıldızlı Gece", "title_en": "The Starry Night",
        "artist_tr": "Vincent van Gogh", "artist_en": "Vincent van Gogh",
        "year": "1889",
        "museum_tr": "MoMA, New York", "museum_en": "MoMA, New York",
        "style_tr": "Post-İzlenimcilik", "style_en": "Post-Impressionism",
        "reason_tr": "Fırtınalı yaratıcılığınız ve duygusal derinliğiniz bu yıldızlı gece gökyüzünde yankılanıyor.",
        "reason_en": "Your turbulent creativity and emotional depth resonate through this starry night sky.",
    },
    {
        "id": "artwork_sunflowers_vangogh",
        "has_portrait": False,
        "emoji": "🌻",
        "geo": {},
        "clusters": {"creativity": 0.90, "charisma": 0.80, "empathy": 0.75, "strength": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg/757px-Vincent_van_Gogh_-_Sunflowers_-_VGM_F458.jpg",
        "title_tr": "Ayçiçekleri", "title_en": "Sunflowers",
        "artist_tr": "Vincent van Gogh", "artist_en": "Vincent van Gogh",
        "year": "1888",
        "museum_tr": "Ulusal Galeri, Londra", "museum_en": "National Gallery, London",
        "style_tr": "Post-İzlenimcilik", "style_en": "Post-Impressionism",
        "reason_tr": "Hayata duyduğunuz coşku ve ısrarcı enerji Van Gogh'un sarı fırça darbelerinde yaşıyor.",
        "reason_en": "Your enthusiasm for life and persistent energy live in Van Gogh's yellow brushstrokes.",
    },
    {
        "id": "artwork_vangogh_self",
        "has_portrait": True,
        "emoji": "🎨",
        "geo": {"jaw_width": 0.84, "face_len_ratio": 1.45, "eye_distance": 0.89},
        "clusters": {"mystery": 0.95, "creativity": 0.90, "empathy": 0.80, "strength": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/558px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg",
        "title_tr": "Otoportre", "title_en": "Self-Portrait",
        "artist_tr": "Vincent van Gogh", "artist_en": "Vincent van Gogh",
        "year": "1889",
        "museum_tr": "Courtauld Galerisi, Londra", "museum_en": "Courtauld Gallery, London",
        "style_tr": "Post-İzlenimcilik", "style_en": "Post-Impressionism",
        "reason_tr": "Derin duygusal dünyası, içten gelen ışık ve kararlı bakış yüzünüzde de var.",
        "reason_en": "A deep emotional world, inner light, and determined gaze — these are in your face too.",
    },

    # ── EKSPRESYONİZM & SİMGECİLİK ───────────────────────────────────────────
    {
        "id": "artwork_the_scream",
        "has_portrait": True,
        "emoji": "😱",
        "geo": {"jaw_width": 0.75, "face_len_ratio": 1.65, "eye_distance": 0.82},
        "clusters": {"mystery": 0.95, "empathy": 0.90, "strength": 0.70, "creativity": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/375px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",
        "title_tr": "Çığlık", "title_en": "The Scream",
        "artist_tr": "Edvard Munch", "artist_en": "Edvard Munch",
        "year": "1893",
        "museum_tr": "Ulusal Müze, Oslo", "museum_en": "National Museum, Oslo",
        "style_tr": "Ekspresyonizm", "style_en": "Expressionism",
        "reason_tr": "İçsel fırtınalar ve varoluşsal sorular taşıyan ruhunuz bu çığlıkta ses bulur.",
        "reason_en": "Your soul carrying inner storms and existential questions finds its voice in this scream.",
    },
    {
        "id": "artwork_the_kiss_klimt",
        "has_portrait": False,
        "emoji": "💛",
        "geo": {},
        "clusters": {"empathy": 0.95, "creativity": 0.90, "mystery": 0.80, "social": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg/757px-The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg",
        "title_tr": "Öpücük", "title_en": "The Kiss",
        "artist_tr": "Gustav Klimt", "artist_en": "Gustav Klimt",
        "year": "1907–1908",
        "museum_tr": "Belvedere Galerisi, Viyana", "museum_en": "Belvedere Gallery, Vienna",
        "style_tr": "Art Nouveau / Sembolizm", "style_en": "Art Nouveau / Symbolism",
        "reason_tr": "Altın bir sıcaklıkla başkalarına bağlanan derin empatiniz Klimt'in altın çağında yaşıyor.",
        "reason_en": "Your deep empathy connecting to others with golden warmth lives in Klimt's golden age.",
    },
    {
        "id": "artwork_adele_klimt",
        "has_portrait": True,
        "emoji": "✨",
        "geo": {"jaw_width": 0.82, "face_len_ratio": 1.48, "eye_distance": 0.87},
        "clusters": {"creativity": 0.95, "charisma": 0.90, "mystery": 0.80, "empathy": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Adele_Bloch-Bauer_I_by_Gustav_Klimt.jpg/590px-Adele_Bloch-Bauer_I_by_Gustav_Klimt.jpg",
        "title_tr": "Adele Bloch-Bauer I", "title_en": "Portrait of Adele Bloch-Bauer I",
        "artist_tr": "Gustav Klimt", "artist_en": "Gustav Klimt",
        "year": "1907",
        "museum_tr": "Neue Galerie, New York", "museum_en": "Neue Galerie, New York",
        "style_tr": "Art Nouveau / Sembolizm", "style_en": "Art Nouveau / Symbolism",
        "reason_tr": "Altın bir aura içinde taşınan yaratıcılık ve karizmanız bu portrenin özünde var.",
        "reason_en": "Creativity and charisma carried within a golden aura are the essence of this portrait — and you.",
    },

    # ── SÜRREALİZM ───────────────────────────────────────────────────────────
    {
        "id": "artwork_persistence_memory",
        "has_portrait": False,
        "emoji": "⏰",
        "geo": {},
        "clusters": {"creativity": 1.00, "mystery": 0.95, "intelligence": 0.80, "discipline": 0.60},
        "image_url": "https://upload.wikimedia.org/wikipedia/en/d/dd/The_Persistence_of_Memory.jpg",
        "title_tr": "Belleğin Azmi", "title_en": "The Persistence of Memory",
        "artist_tr": "Salvador Dalí", "artist_en": "Salvador Dalí",
        "year": "1931",
        "museum_tr": "MoMA, New York", "museum_en": "MoMA, New York",
        "style_tr": "Sürrealizm", "style_en": "Surrealism",
        "reason_tr": "Alışılmışın dışında düşünen ve zamanı kendi kurallarıyla yaşayan zihninizdeki sürrealist boyut.",
        "reason_en": "The surrealist dimension in your mind that thinks outside conventions and lives by its own time.",
    },
    {
        "id": "artwork_son_of_man",
        "has_portrait": True,
        "emoji": "🍎",
        "geo": {"jaw_width": 0.83, "face_len_ratio": 1.44, "eye_distance": 0.90},
        "clusters": {"mystery": 0.95, "intelligence": 0.85, "creativity": 0.90, "discipline": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/en/e/e5/Magritte_TheSonOfMan.jpg",
        "title_tr": "İnsanın Oğlu", "title_en": "The Son of Man",
        "artist_tr": "René Magritte", "artist_en": "René Magritte",
        "year": "1964",
        "museum_tr": "Özel Koleksiyon", "museum_en": "Private Collection",
        "style_tr": "Sürrealizm", "style_en": "Surrealism",
        "reason_tr": "Görünenin ardındaki gerçeği sorgulayan zihniniz Magritte'in gizemli dünyasına ayna tutuyor.",
        "reason_en": "Your mind questioning the reality behind appearances mirrors Magritte's mysterious world.",
    },

    # ── MODERN & ÇAĞDAŞ ───────────────────────────────────────────────────────
    {
        "id": "artwork_two_fridas",
        "has_portrait": True,
        "emoji": "❤",
        "geo": {"jaw_width": 0.85, "face_len_ratio": 1.43, "eye_distance": 0.91},
        "clusters": {"strength": 0.90, "empathy": 0.90, "mystery": 0.80, "creativity": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/en/b/b7/Two_Fridas.jpg",
        "title_tr": "İki Frida", "title_en": "The Two Fridas",
        "artist_tr": "Frida Kahlo", "artist_en": "Frida Kahlo",
        "year": "1939",
        "museum_tr": "Modern Sanatlar Müzesi, Mexico City", "museum_en": "Museum of Modern Art, Mexico City",
        "style_tr": "Sürrealizm / Otobiyografik", "style_en": "Surrealism / Autobiographical",
        "reason_tr": "Acıyı güce dönüştüren ve iç dünyasını cesurca ifade eden ruhunuz bu tabloda var.",
        "reason_en": "The spirit that transforms pain into strength and bravely expresses its inner world lives here.",
    },
    {
        "id": "artwork_guernica",
        "has_portrait": False,
        "emoji": "🕊",
        "geo": {},
        "clusters": {"strength": 0.95, "empathy": 0.90, "creativity": 0.85, "leadership": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/en/7/74/PicassoGuernica.jpg",
        "title_tr": "Guernica", "title_en": "Guernica",
        "artist_tr": "Pablo Picasso", "artist_en": "Pablo Picasso",
        "year": "1937",
        "museum_tr": "Reina Sofía Müzesi, Madrid", "museum_en": "Reina Sofía Museum, Madrid",
        "style_tr": "Kübizm / Antiwar", "style_en": "Cubism / Antiwar",
        "reason_tr": "Haksızlığa karşı duran güç ve empati dolu ruhunuz bu tarihi manifestoya yankı veriyor.",
        "reason_en": "Your power that stands against injustice and empathy-filled spirit echoes this historic manifesto.",
    },

    # ── KLASİK / ANTİK ───────────────────────────────────────────────────────
    {
        "id": "artwork_venus_milo",
        "has_portrait": True,
        "emoji": "🏺",
        "geo": {"jaw_width": 0.80, "face_len_ratio": 1.48, "eye_distance": 0.88},
        "clusters": {"patience": 0.90, "discipline": 0.85, "empathy": 0.75, "charisma": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Aphrodite_of_Milos.jpg/546px-Aphrodite_of_Milos.jpg",
        "title_tr": "Milo Venüsü", "title_en": "Venus de Milo",
        "artist_tr": "Aleksandros of Antioch", "artist_en": "Alexandros of Antioch",
        "year": "M.Ö. 130–100",
        "museum_tr": "Louvre Müzesi, Paris", "museum_en": "Louvre Museum, Paris",
        "style_tr": "Helenistik Heykel", "style_en": "Hellenistic Sculpture",
        "reason_tr": "Zamansız bir denge ve doğal karizmanız antik güzellik idealine en yakın yüzdür.",
        "reason_en": "Your timeless balance and natural charisma are closest to the ancient ideal of beauty.",
    },
    {
        "id": "artwork_david_michelangelo",
        "has_portrait": True,
        "emoji": "💪",
        "geo": {"jaw_width": 0.90, "face_len_ratio": 1.42, "eye_distance": 0.93},
        "clusters": {"strength": 0.95, "leadership": 0.90, "discipline": 0.85, "charisma": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Michelangelo%27s_David_-_right_view_2.jpg/486px-Michelangelo%27s_David_-_right_view_2.jpg",
        "title_tr": "Davut", "title_en": "David",
        "artist_tr": "Michelangelo", "artist_en": "Michelangelo",
        "year": "1501–1504",
        "museum_tr": "Accademia Galerisi, Floransa", "museum_en": "Accademia Gallery, Florence",
        "style_tr": "Rönesans Heykeli", "style_en": "Renaissance Sculpture",
        "reason_tr": "Kararlı bakış ve güç dolu duruş yüzünüzde ve ruhunuzda da var.",
        "reason_en": "The determined gaze and powerful stance also live in your face and spirit.",
    },
    {
        "id": "artwork_winged_victory",
        "has_portrait": False,
        "emoji": "🏛",
        "geo": {},
        "clusters": {"strength": 0.90, "leadership": 0.85, "creativity": 0.70, "charisma": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Nike_of_Samothrake_Louvre_Ma2369_n4.jpg/488px-Nike_of_Samothrake_Louvre_Ma2369_n4.jpg",
        "title_tr": "Samothrake'nin Kanatlı Zaferi", "title_en": "Winged Victory of Samothrace",
        "artist_tr": "Bilinmiyor", "artist_en": "Unknown",
        "year": "M.Ö. 190",
        "museum_tr": "Louvre Müzesi, Paris", "museum_en": "Louvre Museum, Paris",
        "style_tr": "Helenistik Heykel", "style_en": "Hellenistic Sculpture",
        "reason_tr": "İleri atılan, durdurulamaz bir enerji ve liderlik ruhunuz bu zafer heykeline yansımış.",
        "reason_en": "Your forward-moving, unstoppable energy and leadership spirit are reflected in this victory.",
    },

    # ── JAPON SANAT ───────────────────────────────────────────────────────────
    {
        "id": "artwork_great_wave",
        "has_portrait": False,
        "emoji": "🌊",
        "geo": {},
        "clusters": {"strength": 0.90, "discipline": 0.85, "mystery": 0.80, "patience": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Great_Wave_off_Kanagawa2.jpg/800px-Great_Wave_off_Kanagawa2.jpg",
        "title_tr": "Kanagawa'daki Büyük Dalga", "title_en": "The Great Wave off Kanagawa",
        "artist_tr": "Katsushika Hokusai", "artist_en": "Katsushika Hokusai",
        "year": "1831",
        "museum_tr": "Metropolitan Müzesi, New York", "museum_en": "Metropolitan Museum, New York",
        "style_tr": "Japon Ağaç Baskı (Ukiyo-e)", "style_en": "Japanese Woodblock (Ukiyo-e)",
        "reason_tr": "Güçlü ve kontrollü enerjiniz — büyük bir dalgayı disiplinle yönetmek gibi.",
        "reason_en": "Your powerful and controlled energy — like managing a great wave with discipline.",
    },
    {
        "id": "artwork_fine_wind_hokusai",
        "has_portrait": False,
        "emoji": "⛰",
        "geo": {},
        "clusters": {"patience": 0.90, "mystery": 0.85, "discipline": 0.80, "creativity": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Red_Fuji_southern_wind_clear_morning.jpg/800px-Red_Fuji_southern_wind_clear_morning.jpg",
        "title_tr": "Güzel Rüzgar, Berrak Sabah (Kırmızı Fuji)", "title_en": "Fine Wind, Clear Morning (Red Fuji)",
        "artist_tr": "Katsushika Hokusai", "artist_en": "Katsushika Hokusai",
        "year": "1831",
        "museum_tr": "Metropolitan Müzesi, New York", "museum_en": "Metropolitan Museum of Art, New York",
        "style_tr": "Japon Ağaç Baskı (Ukiyo-e)", "style_en": "Japanese Woodblock (Ukiyo-e)",
        "reason_tr": "Zirvede sakin duran, içten ışıldayan ve zamana direnen bir karakter size yakışır.",
        "reason_en": "A character standing calmly at the summit, glowing from within, enduring through time — that's you.",
    },
    {
        "id": "artwork_irises_korin",
        "has_portrait": False,
        "emoji": "🌸",
        "geo": {},
        "clusters": {"creativity": 0.90, "patience": 0.85, "discipline": 0.80, "mystery": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Ogata_Korin_-_Irises.jpg/800px-Ogata_Korin_-_Irises.jpg",
        "title_tr": "İrisler", "title_en": "Irises",
        "artist_tr": "Ogata Kōrin", "artist_en": "Ogata Kōrin",
        "year": "1701–1705",
        "museum_tr": "Nezu Müzesi, Tokyo", "museum_en": "Nezu Museum, Tokyo",
        "style_tr": "Japon Rimpa Okulu", "style_en": "Japanese Rimpa School",
        "reason_tr": "Zarif ve özgün bir yaratıcılıkla deseni tekrarlayan ama hiç sıkıcı olmayan bir ruhunuz var.",
        "reason_en": "You have a spirit that repeats the pattern with elegant originality yet never becomes monotonous.",
    },

    # ── ÇİN SANAT ─────────────────────────────────────────────────────────────
    {
        "id": "artwork_thousand_li",
        "has_portrait": False,
        "emoji": "🏔",
        "geo": {},
        "clusters": {"patience": 0.95, "mystery": 0.85, "intelligence": 0.80, "discipline": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Wang_Ximeng._A_Thousand_Li_of_Rivers_and_Mountains._%281113%29.jpg/800px-Wang_Ximeng._A_Thousand_Li_of_Rivers_and_Mountains._%281113%29.jpg",
        "title_tr": "Bin Li Nehirler ve Dağlar", "title_en": "A Thousand Li of Rivers and Mountains",
        "artist_tr": "Wang Ximeng", "artist_en": "Wang Ximeng",
        "year": "1113",
        "museum_tr": "Saray Müzesi, Pekin", "museum_en": "Palace Museum, Beijing",
        "style_tr": "Çin Peyzaj Resmi", "style_en": "Chinese Landscape Painting",
        "reason_tr": "Geniş bir perspektiften hayata bakan derin ve sabırlı zihniniz bu efsanevi esere akıyor.",
        "reason_en": "Your deep, patient mind viewing life from a vast perspective flows into this legendary work.",
    },
    {
        "id": "artwork_qingming_festival",
        "has_portrait": False,
        "emoji": "🏮",
        "geo": {},
        "clusters": {"social": 0.90, "intelligence": 0.85, "patience": 0.80, "discipline": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Along_the_River_During_the_Qingming_Festival_%28Qing_Court_Version%29.jpg/800px-Along_the_River_During_the_Qingming_Festival_%28Qing_Court_Version%29.jpg",
        "title_tr": "Qingming Festivali'nde Nehir Boyunca", "title_en": "Along the River During Qingming Festival",
        "artist_tr": "Zhang Zeduan", "artist_en": "Zhang Zeduan",
        "year": "M.S. 1120",
        "museum_tr": "Saray Müzesi, Pekin", "museum_en": "Palace Museum, Beijing",
        "style_tr": "Çin Figüratif Resim", "style_en": "Chinese Figurative Painting",
        "reason_tr": "Her detayı gören gözünüz ve insanlarla kurduğunuz güçlü bağ bu canlı tabanda sizi karşılıyor.",
        "reason_en": "Your eye that sees every detail and the strong bond you build with people meet you in this vibrant scroll.",
    },

    # ── OSMANLI / PERS MİNYATÜRÜ ─────────────────────────────────────────────
    {
        "id": "artwork_sultan_suleiman",
        "has_portrait": True,
        "emoji": "🗡",
        "geo": {"jaw_width": 0.87, "face_len_ratio": 1.44, "eye_distance": 0.91},
        "clusters": {"leadership": 0.95, "intelligence": 0.85, "discipline": 0.85, "charisma": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Suleiman_the_Magnificent2.jpg/391px-Suleiman_the_Magnificent2.jpg",
        "title_tr": "Kanuni Sultan Süleyman Portresi", "title_en": "Portrait of Suleiman the Magnificent",
        "artist_tr": "Nigari (Haydar Reis)", "artist_en": "Nigari (Haydar Reis)",
        "year": "1560",
        "museum_tr": "Topkapı Sarayı Müzesi, İstanbul", "museum_en": "Topkapı Palace Museum, Istanbul",
        "style_tr": "Osmanlı Portre Sanatı", "style_en": "Ottoman Portrait Art",
        "reason_tr": "Güçlü liderlik, derin zeka ve disiplinli irade — bu portrenin sahiplendiği nitelikler sizindir.",
        "reason_en": "Strong leadership, deep intelligence, and disciplined will — the qualities of this portrait are yours.",
    },
    {
        "id": "artwork_leyla_majnun",
        "has_portrait": False,
        "emoji": "📖",
        "geo": {},
        "clusters": {"empathy": 0.95, "mystery": 0.90, "creativity": 0.85, "social": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Layla_and_Majnun_at_School_%28cropped%29.jpg/600px-Layla_and_Majnun_at_School_%28cropped%29.jpg",
        "title_tr": "Leyla ile Mecnun", "title_en": "Layla and Majnun",
        "artist_tr": "Bilinmiyor (Herat Okulu)", "artist_en": "Unknown (Herat School)",
        "year": "16. yüzyıl",
        "museum_tr": "British Library, Londra", "museum_en": "British Library, London",
        "style_tr": "Pers / Osmanlı Minyatürü", "style_en": "Persian / Ottoman Miniature",
        "reason_tr": "Derin duygusal bağlar kuran ve sevgiyi özünde taşıyan ruhunuz bu efsanevi hikayede yaşıyor.",
        "reason_en": "Your soul that forms deep emotional bonds and carries love within lives in this legendary story.",
    },

    # ── HINT / MOGOL SANAT ────────────────────────────────────────────────────
    {
        "id": "artwork_radha_krishna",
        "has_portrait": False,
        "emoji": "🌺",
        "geo": {},
        "clusters": {"empathy": 0.95, "creativity": 0.85, "social": 0.80, "mystery": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Radha_and_Krishna_in_the_Grove.jpg/495px-Radha_and_Krishna_in_the_Grove.jpg",
        "title_tr": "Korudaki Radha ve Krishna", "title_en": "Radha and Krishna in a Grove",
        "artist_tr": "Bilinmiyor (Kangra Okulu)", "artist_en": "Unknown (Kangra School)",
        "year": "1780",
        "museum_tr": "Victoria & Albert Müzesi, Londra", "museum_en": "Victoria & Albert Museum, London",
        "style_tr": "Hint Minyatürü (Pahari)", "style_en": "Indian Miniature (Pahari)",
        "reason_tr": "Sevgiyi yaratıcılıkla harmanlamanız ve derin bağlar kurmanız bu rengarenk eserde yankılanır.",
        "reason_en": "Your blending of love with creativity and forming deep bonds resonates in this colorful work.",
    },

    # ── BİZANS / ORTAÇAĞ ─────────────────────────────────────────────────────
    {
        "id": "artwork_christ_pantokrator",
        "has_portrait": True,
        "emoji": "✝",
        "geo": {"jaw_width": 0.85, "face_len_ratio": 1.48, "eye_distance": 0.89},
        "clusters": {"mystery": 0.95, "patience": 0.90, "intelligence": 0.80, "discipline": 0.85},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Hagia_Sophia_Christ_mosaic_crop.jpg/387px-Hagia_Sophia_Christ_mosaic_crop.jpg",
        "title_tr": "Pantokrator Mozaiği", "title_en": "Christ Pantokrator Mosaic",
        "artist_tr": "Bilinmiyor (Bizans)", "artist_en": "Unknown (Byzantine)",
        "year": "12. yüzyıl",
        "museum_tr": "Ayasofya, İstanbul", "museum_en": "Hagia Sophia, Istanbul",
        "style_tr": "Bizans Sanatı", "style_en": "Byzantine Art",
        "reason_tr": "Zamansız derin bakışlar ve hesaplı bir zekayla çevrenize hükmeden ruhunuz bu ikonada var.",
        "reason_en": "A timeless deep gaze and a calculated intelligence that commands your surroundings — this icon holds you.",
    },
    {
        "id": "artwork_annunciation_angelico",
        "has_portrait": False,
        "emoji": "🌿",
        "geo": {},
        "clusters": {"empathy": 0.95, "mystery": 0.85, "patience": 0.80, "creativity": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Fra_Angelico_-_Annunciation_%28Cell_3%29_-_WGA00539.jpg/800px-Fra_Angelico_-_Annunciation_%28Cell_3%29_-_WGA00539.jpg",
        "title_tr": "Müjde", "title_en": "The Annunciation",
        "artist_tr": "Fra Angelico", "artist_en": "Fra Angelico",
        "year": "1438–1450",
        "museum_tr": "San Marco Müzesi, Floransa", "museum_en": "San Marco Museum, Florence",
        "style_tr": "Erken Rönesans", "style_en": "Early Renaissance",
        "reason_tr": "Dingin ve derin empatiniz, sabırlı ve aydınlık ruhunuz bu nefis eseri size yansıtıyor.",
        "reason_en": "Your calm and deep empathy, patient and luminous spirit, reflect this exquisite work back to you.",
    },

    # ── HOLLANDA ALTIN ÇAĞI ───────────────────────────────────────────────────
    {
        "id": "artwork_milkmaid_vermeer",
        "has_portrait": True,
        "emoji": "🥛",
        "geo": {"jaw_width": 0.83, "face_len_ratio": 1.44, "eye_distance": 0.90},
        "clusters": {"patience": 0.90, "discipline": 0.85, "empathy": 0.80, "social": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg/552px-Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg",
        "title_tr": "Sütçü Kız", "title_en": "The Milkmaid",
        "artist_tr": "Johannes Vermeer", "artist_en": "Johannes Vermeer",
        "year": "1657–1658",
        "museum_tr": "Rijksmuseum, Amsterdam", "museum_en": "Rijksmuseum, Amsterdam",
        "style_tr": "Hollanda Altın Çağı", "style_en": "Dutch Golden Age",
        "reason_tr": "Her günün ritüelinde büyük bir değer bulan, sakin ve özenli ruhunuz bu işıkla buluşuyor.",
        "reason_en": "Your calm, careful spirit that finds great value in everyday rituals meets this light.",
    },
    {
        "id": "artwork_anatomy_lesson",
        "has_portrait": False,
        "emoji": "🔬",
        "geo": {},
        "clusters": {"intelligence": 0.95, "discipline": 0.90, "leadership": 0.75, "social": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/800px-Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg",
        "title_tr": "Dr. Tulp'un Anatomi Dersi", "title_en": "The Anatomy Lesson of Dr. Nicolaes Tulp",
        "artist_tr": "Rembrandt van Rijn", "artist_en": "Rembrandt van Rijn",
        "year": "1632",
        "museum_tr": "Mauritshuis, La Haye", "museum_en": "Mauritshuis, The Hague",
        "style_tr": "Barok", "style_en": "Baroque",
        "reason_tr": "Bilgiyi paylaşan ve analitik zekayla öğreten lider kimliğiniz bu tabloda can bulur.",
        "reason_en": "Your identity as a leader who shares knowledge and teaches with analytical intelligence comes alive here.",
    },

    # ── 19. YY PORTRE ─────────────────────────────────────────────────────────
    {
        "id": "artwork_napoleon_david",
        "has_portrait": True,
        "emoji": "🐎",
        "geo": {"jaw_width": 0.86, "face_len_ratio": 1.43, "eye_distance": 0.90},
        "clusters": {"leadership": 0.95, "charisma": 0.90, "strength": 0.85, "discipline": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Jacques-Louis_David_-_Napoleon_Crossing_the_Alps_-_Kunsthistorisches_Museum.jpg/670px-Jacques-Louis_David_-_Napoleon_Crossing_the_Alps_-_Kunsthistorisches_Museum.jpg",
        "title_tr": "Alpler'i Geçen Napolyon", "title_en": "Napoleon Crossing the Alps",
        "artist_tr": "Jacques-Louis David", "artist_en": "Jacques-Louis David",
        "year": "1801",
        "museum_tr": "Kunsthistorisches Museum, Viyana", "museum_en": "Kunsthistorisches Museum, Vienna",
        "style_tr": "Neoklasizm", "style_en": "Neoclassicism",
        "reason_tr": "Zorlu koşullarda bile kararlı ve karizmatik liderlik enerjiniz bu ikonik sahnede yaşıyor.",
        "reason_en": "Your determined and charismatic leadership energy, even in difficult conditions, lives in this iconic scene.",
    },
    {
        "id": "artwork_impression_soleil",
        "has_portrait": False,
        "emoji": "🌅",
        "geo": {},
        "clusters": {"creativity": 0.90, "mystery": 0.80, "patience": 0.75, "empathy": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/800px-Monet_-_Impression%2C_Sunrise.jpg",
        "title_tr": "Empresyon, Gün Doğuşu", "title_en": "Impression, Sunrise",
        "artist_tr": "Claude Monet", "artist_en": "Claude Monet",
        "year": "1872",
        "museum_tr": "Marmottan Monet Müzesi, Paris", "museum_en": "Marmottan Monet Museum, Paris",
        "style_tr": "İzlenimcilik", "style_en": "Impressionism",
        "reason_tr": "Her yeni başlangıcı parlak bir ışıkla karşılayan ve anlı fırsatlara açık ruhunuz bu tuvalde.",
        "reason_en": "Your spirit that greets every new beginning with bright light and is open to fleeting moments lives here.",
    },

    # ── POP ART & 20. YY ──────────────────────────────────────────────────────
    {
        "id": "artwork_marilyn_warhol",
        "has_portrait": True,
        "emoji": "💋",
        "geo": {"jaw_width": 0.82, "face_len_ratio": 1.45, "eye_distance": 0.90},
        "clusters": {"charisma": 0.95, "social": 0.90, "creativity": 0.80, "leadership": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/en/a/a8/Warhol-Marilyn.jpg",
        "title_tr": "Marilyn Monroe", "title_en": "Marilyn (Marilyn Monroe)",
        "artist_tr": "Andy Warhol", "artist_en": "Andy Warhol",
        "year": "1967",
        "museum_tr": "Çeşitli Koleksiyonlar", "museum_en": "Various Collections",
        "style_tr": "Pop Art", "style_en": "Pop Art",
        "reason_tr": "Büyüleyici karizmanız ve sosyal manyetizmanız pop kültürünün en ikonik portresinde kendini buluyor.",
        "reason_en": "Your captivating charisma and social magnetism find themselves in pop culture's most iconic portrait.",
    },

    # ── AFRİKA SANAT ──────────────────────────────────────────────────────────
    {
        "id": "artwork_benin_bronze",
        "has_portrait": True,
        "emoji": "🗿",
        "geo": {"jaw_width": 0.88, "face_len_ratio": 1.40, "eye_distance": 0.92},
        "clusters": {"leadership": 0.90, "strength": 0.85, "discipline": 0.80, "charisma": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Benin_bronze_lower_half.jpg/502px-Benin_bronze_lower_half.jpg",
        "title_tr": "Benin Bronz Levhası", "title_en": "Benin Bronze Plaque",
        "artist_tr": "Bilinmiyor (Benin Krallığı)", "artist_en": "Unknown (Kingdom of Benin)",
        "year": "16–17. yüzyıl",
        "museum_tr": "British Museum, Londra", "museum_en": "British Museum, London",
        "style_tr": "Batı Afrika Bronz Sanatı", "style_en": "West African Bronze Art",
        "reason_tr": "Güç ve otorite taşıyan, zamanı aşan bir yüz ifadesi — bu sizin izinizi burada bırakıyor.",
        "reason_en": "A face expression carrying power and authority that transcends time — this is where you leave your mark.",
    },

    # ── ORTA ASYA / İSLAM SANAT ───────────────────────────────────────────────
    {
        "id": "artwork_shahnameh",
        "has_portrait": False,
        "emoji": "⚔️",
        "geo": {},
        "clusters": {"strength": 0.95, "leadership": 0.85, "creativity": 0.80, "charisma": 0.75},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Shahnameh.jpg/480px-Shahnameh.jpg",
        "title_tr": "Şehname Minyatürü", "title_en": "Shahnameh Miniature",
        "artist_tr": "Bilinmiyor (İran)", "artist_en": "Unknown (Iranian)",
        "year": "1525",
        "museum_tr": "MFA Boston", "museum_en": "Museum of Fine Arts, Boston",
        "style_tr": "Pers Minyatürü", "style_en": "Persian Miniature",
        "reason_tr": "Efsanelere konu olan güç ve liderliğiniz bu destansı minyatürde kendinizi buluyorsunuz.",
        "reason_en": "Your legendary strength and leadership find themselves in this epic miniature painting.",
    },

    # ── EK PORTELER ───────────────────────────────────────────────────────────
    {
        "id": "artwork_lady_with_ermine",
        "has_portrait": True,
        "emoji": "🦡",
        "geo": {"jaw_width": 0.79, "face_len_ratio": 1.52, "eye_distance": 0.87},
        "clusters": {"intelligence": 0.90, "mystery": 0.85, "discipline": 0.75, "charisma": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg/578px-Lady_with_an_Ermine_-_Leonardo_da_Vinci_%28adjusted_levels%29.jpg",
        "title_tr": "Kakum Tutan Kadın", "title_en": "Lady with an Ermine",
        "artist_tr": "Leonardo da Vinci", "artist_en": "Leonardo da Vinci",
        "year": "1489–1490",
        "museum_tr": "Czartoryski Müzesi, Kraków", "museum_en": "Czartoryski Museum, Kraków",
        "style_tr": "Rönesans Portresi", "style_en": "Renaissance Portrait",
        "reason_tr": "Zeki ve gizemli duruşunuz, Leonardo'nun en az bilinen ama en derin eserinde yankılanıyor.",
        "reason_en": "Your intelligent and mysterious composure resonates in Leonardo's least known yet deepest work.",
    },
    {
        "id": "artwork_arrangement_grey_black",
        "has_portrait": True,
        "emoji": "🪑",
        "geo": {"jaw_width": 0.81, "face_len_ratio": 1.50, "eye_distance": 0.87},
        "clusters": {"patience": 0.90, "discipline": 0.85, "mystery": 0.75, "intelligence": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/800px-Whistlers_Mother_high_res.jpg",
        "title_tr": "Gri ve Siyah Düzenlemesi No. 1 (Whistler'ın Annesi)", "title_en": "Arrangement in Grey and Black No.1 (Whistler's Mother)",
        "artist_tr": "James McNeill Whistler", "artist_en": "James McNeill Whistler",
        "year": "1871",
        "museum_tr": "Musée d'Orsay, Paris", "museum_en": "Musée d'Orsay, Paris",
        "style_tr": "Tonalizm", "style_en": "Tonalism",
        "reason_tr": "Sakin ve kararlı bir duruş, derin sabır ve içinden geldiği gibi yaşama kararlılığı — siz.",
        "reason_en": "A calm and determined stance, deep patience, and resolve to live as one truly is — you.",
    },
    {
        "id": "artwork_cafe_terrace_night",
        "has_portrait": False,
        "emoji": "🌃",
        "geo": {},
        "clusters": {"creativity": 0.90, "social": 0.80, "mystery": 0.75, "empathy": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Van_Gogh_-_Terrasse_des_Caf%C3%A9s_an_der_Place_du_Forum_in_Arles%2C_abends.jpeg/640px-Van_Gogh_-_Terrasse_des_Caf%C3%A9s_an_der_Place_du_Forum_in_Arles%2C_abends.jpeg",
        "title_tr": "Gece Kafe Terası", "title_en": "Café Terrace at Night",
        "artist_tr": "Vincent van Gogh", "artist_en": "Vincent van Gogh",
        "year": "1888",
        "museum_tr": "Kröller-Müller Müzesi, Otterlo", "museum_en": "Kröller-Müller Museum, Otterlo",
        "style_tr": "Post-İzlenimcilik", "style_en": "Post-Impressionism",
        "reason_tr": "Yıldızlı gecelerde insanların arasında büyü yaratan sıcak ve yaratıcı ruhunuz bu tablodan bakıyor.",
        "reason_en": "Your warm and creative spirit that creates magic among people on starry nights gazes from this painting.",
    },
    {
        "id": "artwork_reading_le_sidaner",
        "has_portrait": True,
        "emoji": "📚",
        "geo": {"jaw_width": 0.80, "face_len_ratio": 1.47, "eye_distance": 0.88},
        "clusters": {"intelligence": 0.85, "mystery": 0.80, "patience": 0.85, "creativity": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Henri_Le_Sidaner_-_The_Table%2C_Gerberoy%2C_1910.jpg/799px-Henri_Le_Sidaner_-_The_Table%2C_Gerberoy%2C_1910.jpg",
        "title_tr": "Masa", "title_en": "The Table",
        "artist_tr": "Henri Le Sidaner", "artist_en": "Henri Le Sidaner",
        "year": "1910",
        "museum_tr": "Özel Koleksiyon", "museum_en": "Private Collection",
        "style_tr": "Post-İzlenimcilik", "style_en": "Post-Impressionism",
        "reason_tr": "Sessizlikte derin bir dünya kuran ve anlık güzellikleri fark eden ruhunuz bu ışıkta parlar.",
        "reason_en": "Your spirit that builds a deep world in silence and notices fleeting beauties shines in this light.",
    },
    {
        "id": "artwork_hay_wain_constable",
        "has_portrait": False,
        "emoji": "🌳",
        "geo": {},
        "clusters": {"patience": 0.85, "empathy": 0.80, "creativity": 0.75, "social": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/John_Constable_-_The_Hay_Wain_%281821%29.jpg/800px-John_Constable_-_The_Hay_Wain_%281821%29.jpg",
        "title_tr": "Saman Arabası", "title_en": "The Hay Wain",
        "artist_tr": "John Constable", "artist_en": "John Constable",
        "year": "1821",
        "museum_tr": "Ulusal Galeri, Londra", "museum_en": "National Gallery, London",
        "style_tr": "Romantizm / Peyzaj", "style_en": "Romanticism / Landscape",
        "reason_tr": "Doğayla uyumlu, sessiz bir güç taşıyan ve köklere bağlı ruhunuz bu İngiliz manzarasında yaşıyor.",
        "reason_en": "Your spirit carrying quiet strength in harmony with nature and rooted in its origins lives in this English landscape.",
    },
    {
        "id": "artwork_american_gothic",
        "has_portrait": True,
        "emoji": "🌽",
        "geo": {"jaw_width": 0.87, "face_len_ratio": 1.46, "eye_distance": 0.91},
        "clusters": {"discipline": 0.90, "patience": 0.85, "strength": 0.80, "leadership": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_DeVolson_Wood_-_American_Gothic.jpg/480px-Grant_DeVolson_Wood_-_American_Gothic.jpg",
        "title_tr": "Amerikan Gotiği", "title_en": "American Gothic",
        "artist_tr": "Grant Wood", "artist_en": "Grant Wood",
        "year": "1930",
        "museum_tr": "Sanat Enstitüsü, Chicago", "museum_en": "Art Institute of Chicago",
        "style_tr": "Amerikan Bölgeselciliği", "style_en": "American Regionalism",
        "reason_tr": "Kararlı, disiplinli ve köklerine sıkı bağlı güçlü bir karakter sizde ve bu ikonik portrede var.",
        "reason_en": "A determined, disciplined character firmly rooted in their values — in you and this iconic portrait.",
    },
    {
        "id": "artwork_luncheon_boating",
        "has_portrait": False,
        "emoji": "⛵",
        "geo": {},
        "clusters": {"social": 0.95, "charisma": 0.85, "creativity": 0.75, "empathy": 0.80},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg/800px-Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg",
        "title_tr": "Kayık Partisi Öğle Yemeği", "title_en": "Luncheon of the Boating Party",
        "artist_tr": "Pierre-Auguste Renoir", "artist_en": "Pierre-Auguste Renoir",
        "year": "1881",
        "museum_tr": "Phillips Koleksiyonu, Washington", "museum_en": "The Phillips Collection, Washington",
        "style_tr": "İzlenimcilik", "style_en": "Impressionism",
        "reason_tr": "İnsanları bir araya getiren, neşe yaratan sosyal karizmanız bu canlı tabloya hayat veriyor.",
        "reason_en": "Your social charisma that brings people together and creates joy breathes life into this vibrant painting.",
    },
    {
        "id": "artwork_olympia_manet",
        "has_portrait": True,
        "emoji": "🌷",
        "geo": {"jaw_width": 0.81, "face_len_ratio": 1.49, "eye_distance": 0.88},
        "clusters": {"strength": 0.85, "charisma": 0.80, "mystery": 0.75, "leadership": 0.70},
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Edouard_Manet_-_Olympia_-_Google_Art_Project_2.jpg/800px-Edouard_Manet_-_Olympia_-_Google_Art_Project_2.jpg",
        "title_tr": "Olympia", "title_en": "Olympia",
        "artist_tr": "Édouard Manet", "artist_en": "Édouard Manet",
        "year": "1863",
        "museum_tr": "Musée d'Orsay, Paris", "museum_en": "Musée d'Orsay, Paris",
        "style_tr": "Realizm / Empresyonizm Öncesi", "style_en": "Realism / Pre-Impressionism",
        "reason_tr": "Doğrudan ve cesur bakışınız, toplumsal normlara meydan okuyan güçlü bir kişiliğe işaret ediyor.",
        "reason_en": "Your direct and bold gaze points to a strong personality that challenges social norms.",
    },
]
