"""
facesyma_ai/chat_service/modules/definitions.py
================================================
All module definitions (10 modules × 18 languages).

To add a new module:
  1. Copy a module dict below
  2. Update all 18 language translations
  3. Add to ALL_MODULES at the end
"""

# ── Language codes ─────────────────────────────────────────────────────────
LANGUAGES = ["tr", "en", "de", "ru", "ar", "es", "ko", "ja", "zh", "hi", "fr", "pt", "bn", "id", "ur", "it", "vi", "pl"]

# ──────────────────────────────────────────────────────────────────────────
# MODULE 1: ASTROLOGY
# ──────────────────────────────────────────────────────────────────────────

ASTROLOGY = {
    "name": "astrology",
    "display": {
        "tr": "Astroloji Haritası",
        "en": "Astrology Chart",
        "de": "Astrologie-Diagramm",
        "ru": "Астрологическая карта",
        "ar": "خريطة فلكية",
        "es": "Carta Astrológica",
        "ko": "점성술 차트",
        "ja": "占星術チャート",
        "zh": "占星图",
        "hi": "ज्योतिष चार्ट",
        "fr": "Carte Astrologique",
        "pt": "Mapa Astrológico",
        "bn": "জ্যোতিষ চার্ট",
        "id": "Bagan Astrologi",
        "ur": "نجومی نقشہ",
        "it": "Mappa Astrologica",
        "vi": "Biểu đồ Chiêu tinh học",
        "pl": "Mapa Astrologiczna",
    },
    "trigger_keywords": {
        "tr": ["doğum", "burç", "astroloji", "harita", "horoskop", "zodyak"],
        "en": ["birth", "zodiac", "astrology", "horoscope", "chart", "sign"],
        "de": ["geburt", "sternzeichen", "astrologie", "horoskop"],
        "ru": ["рождение", "знак", "астрология", "гороскоп"],
        "ar": ["ميلاد", "الابراج", "فلك", "تنجيم"],
        "es": ["nacimiento", "zodiaco", "astrología", "horóscopo"],
        "ko": ["생일", "띠", "점성술", "운세"],
        "ja": ["誕生", "星座", "占星術", "星", "運"],
        "zh": ["生日", "星座", "占星", "运势"],
        "hi": ["जन्म", "राशि", "ज्योतिष", "भविष्य"],
        "fr": ["naissance", "zodiaque", "astrologie", "horoscope"],
        "pt": ["nascimento", "zodíaco", "astrologia", "horóscopo"],
        "bn": ["জন্ম", "রাশি", "জ্যোতিষ", "ভবিষ্যত"],
        "id": ["lahir", "zodiak", "astrologi", "ramalan"],
        "ur": ["پیدائش", "نشان", "نجومی", "مستقبل"],
        "it": ["nascita", "zodiaco", "astrologia", "oroscopo"],
        "vi": ["sinh", "cung hoàng đạo", "chiêu tinh học", "vận mệnh"],
        "pl": ["urodzenie", "zodiak", "astrologia", "horoskop"],
    },
    "description": {
        "tr": "Doğum tarihiniz ve saatinizle astroloji haritanız oluşturum. Burç, element, kalite ve yaşam yolunuzu ortaya koyarım.",
        "en": "Creates your astrological chart from birth date and time. Reveals your zodiac sign, elements, and life path.",
        "de": "Erstellt Ihre Astrologie-Karte basierend auf Geburtsdatum und Uhrzeit.",
        "ru": "Создает вашу астрологическую карту по дате и времени рождения.",
        "ar": "ينشئ خريطتك الفلكية من تاريخ ووقت الميلاد.",
        "es": "Crea tu carta astrológica a partir de tu fecha y hora de nacimiento.",
        "ko": "생년월일과 시간으로 당신의 점성술 차트를 작성합니다.",
        "ja": "生年月日と時間から占星術チャートを作成します。",
        "zh": "根据出生日期和时间创建您的占星图。",
        "hi": "आपके जन्म तारीख और समय से ज्योतिष चार्ट बनाता है।",
        "fr": "Crée votre carte astrologique à partir de votre date et heure de naissance.",
        "pt": "Cria seu mapa astrológico a partir de sua data e hora de nascimento.",
        "bn": "আপনার জন্ম তারিখ এবং সময় থেকে জ্যোতিষ চার্ট তৈরি করে।",
        "id": "Membuat bagan astrologi Anda dari tanggal dan waktu lahir.",
        "ur": "آپ کے پیدائش کی تاریخ اور وقت سے نجومی نقشہ بناتا ہے۔",
        "it": "Crea la tua mappa astrologica dalla data e ora di nascita.",
        "vi": "Tạo biểu đồ chiêu tinh học của bạn từ ngày và giờ sinh.",
        "pl": "Tworzy mapę astrologiczną na podstawie daty i godziny urodzenia.",
    },
    "requires_input": "birth_date",
    "endpoint": "http://coach:8003/coach/birth",
    "method": "POST",
    "input_prompt": {
        "tr": "Doğum tarihinizi (YYYY-AA-GG) ve varsa saatini paylaşabilir misiniz?",
        "en": "Could you share your birth date (YYYY-MM-DD) and time if known?",
        "de": "Könnten Sie Ihr Geburtsdatum (YYYY-MM-DD) und Ihre Geburtszeit angeben?",
        "ru": "Поделитесь датой рождения (YYYY-MM-DD) и временем, если известно?",
        "ar": "هل يمكنك مشاركة تاريخ ميلادك ووقتك؟",
        "es": "¿Podrías compartir tu fecha de nacimiento (YYYY-MM-DD) y hora?",
        "ko": "생년월일(YYYY-MM-DD)과 시간을 알려주시겠어요?",
        "ja": "お生まれになった日付（YYYY-MM-DD）と時間を教えていただけますか？",
        "zh": "您能分享您的出生日期（YYYY-MM-DD）和时间吗？",
        "hi": "आप अपनी जन्म तारीख (YYYY-MM-DD) और समय साझा कर सकते हैं?",
        "fr": "Pouvez-vous partager votre date de naissance (YYYY-MM-DD) et votre heure?",
        "pt": "Você pode compartilhar sua data de nascimento (YYYY-MM-DD) e hora?",
        "bn": "আপনি আপনার জন্ম তারিখ এবং সময় শেয়ার করতে পারেন?",
        "id": "Bisakah Anda berbagi tanggal lahir dan waktu Anda?",
        "ur": "کیا آپ اپنی پیدائش کی تاریخ اور وقت بتا سکتے ہیں؟",
        "it": "Puoi condividere la tua data di nascita (YYYY-MM-DD) e l'ora?",
        "vi": "Bạn có thể chia sẻ ngày sinh và giờ của mình không?",
        "pl": "Czy możesz podzielić się swoją datą urodzenia (YYYY-MM-DD) i godziną?",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 2: PERSONALITY TEST
# ──────────────────────────────────────────────────────────────────────────

TEST_PERSONALITY = {
    "name": "test_personality",
    "display": {
        "tr": "Kişilik Testi",
        "en": "Personality Test",
        "de": "Persönlichkeitstest",
        "ru": "Тест личности",
        "ar": "اختبار الشخصية",
        "es": "Test de Personalidad",
        "ko": "성격 테스트",
        "ja": "性格テスト",
        "zh": "性格测试",
        "hi": "व्यक्तित्व परीक्षण",
        "fr": "Test de Personnalité",
        "pt": "Teste de Personalidade",
        "bn": "ব্যক্তিত্ব পরীক্ষা",
        "id": "Tes Kepribadian",
        "ur": "شخصیت کی جانچ",
        "it": "Test della Personalità",
        "vi": "Bài kiểm tra Tính cách",
        "pl": "Test Osobowości",
    },
    "trigger_keywords": {
        "tr": ["kişilik", "test", "big five", "karakterim", "eğilim"],
        "en": ["personality", "test", "big five", "character", "trait"],
        "de": ["persönlichkeit", "test", "big five", "charakter"],
        "ru": ["личность", "тест", "характер", "черты"],
        "ar": ["شخصية", "اختبار", "صفات"],
        "es": ["personalidad", "test", "carácter"],
        "ko": ["성격", "테스트", "특성"],
        "ja": ["性格", "テスト", "特性"],
        "zh": ["性格", "测试", "特征"],
        "hi": ["व्यक्तित्व", "परीक्षण", "विशेषता"],
        "fr": ["personnalité", "test", "caractère"],
        "pt": ["personalidade", "teste", "caráter"],
        "bn": ["ব্যক্তিত্ব", "পরীক্ষা", "বৈশিষ্ট্য"],
        "id": ["kepribadian", "tes", "karakter"],
        "ur": ["شخصیت", "جانچ", "صفات"],
        "it": ["personalità", "test", "carattere"],
        "vi": ["tính cách", "bài kiểm tra", "đặc tính"],
        "pl": ["osobowość", "test", "charakter"],
    },
    "description": {
        "tr": "Big Five modeline göre 20 sorulu test. Açıklık, Sorumluluk, Dışadönüklük, Uyumluluk ve Duygusal Dengelilik puanlarınızı ölçer.",
        "en": "20-question test based on Big Five model. Measures openness, conscientiousness, extraversion, agreeableness, and neuroticism.",
        "de": "20-Fragen-Test nach dem Big-Five-Modell.",
        "ru": "20-вопросный тест на основе модели Big Five.",
        "ar": "اختبار من 20 سؤالاً بناءً على نموذج Big Five.",
        "es": "Test de 20 preguntas basado en el modelo Big Five.",
        "ko": "Big Five 모델 기반 20문항 테스트.",
        "ja": "ビッグファイブモデルに基づいた20問のテスト。",
        "zh": "基于Big Five模型的20道题测试。",
        "hi": "Big Five मॉडल पर आधारित 20 प्रश्न परीक्षण।",
        "fr": "Test de 20 questions basé sur le modèle Big Five.",
        "pt": "Teste de 20 perguntas baseado no modelo Big Five.",
        "bn": "Big Five মডেলের উপর ভিত্তি করে 20 প্রশ্নের পরীক্ষা।",
        "id": "Test 20 pertanyaan berdasarkan model Big Five.",
        "ur": "Big Five ماڈل کی بنیاد پر 20 سوالات کی جانچ۔",
        "it": "Test di 20 domande basato sul modello Big Five.",
        "vi": "Bài kiểm tra 20 câu hỏi dựa trên mô hình Big Five.",
        "pl": "Test 20 pytań oparty na modelu Big Five.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "Kişilik testini başlatalım mı? 20 soruda sizi tanıyacağız.",
        "en": "Ready to take the personality test? 20 questions about you.",
        "de": "Bereit für den Persönlichkeitstest?",
        "ru": "Готовы пройти тест личности?",
        "ar": "هل أنت مستعد لاختبار الشخصية؟",
        "es": "¿Listo para el test de personalidad?",
        "ko": "성격 테스트를 시작할까요?",
        "ja": "性格テストを受ける準備はいいですか？",
        "zh": "准备好进行性格测试了吗？",
        "hi": "व्यक्तित्व परीक्षण लेने के लिए तैयार?",
        "fr": "Êtes-vous prêt pour le test de personnalité?",
        "pt": "Pronto para fazer o teste de personalidade?",
        "bn": "ব্যক্তিত্ব পরীক্ষা নিতে প্রস্তুত?",
        "id": "Siap mengikuti tes kepribadian?",
        "ur": "شخصیت کی جانچ لینے کے لیے تیار؟",
        "it": "Pronto per il test della personalità?",
        "vi": "Sẵn sàng làm bài kiểm tra tính cách chưa?",
        "pl": "Gotów do testu osobowości?",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 3: CAREER TEST
# ──────────────────────────────────────────────────────────────────────────

TEST_CAREER = {
    "name": "test_career",
    "display": {
        "tr": "Kariyer Testi",
        "en": "Career Test",
        "de": "Karrieretest",
        "ru": "Тест карьеры",
        "ar": "اختبار المهنة",
        "es": "Test de Carrera",
        "ko": "경력 테스트",
        "ja": "キャリアテスト",
        "zh": "职业测试",
        "hi": "कैरियर परीक्षण",
        "fr": "Test de Carrière",
        "pt": "Teste de Carreira",
        "bn": "ক্যারিয়ার পরীক্ষা",
        "id": "Tes Karir",
        "ur": "کیریئر ٹیسٹ",
        "it": "Test di Carriera",
        "vi": "Bài kiểm tra Sự nghiệp",
        "pl": "Test Kariery",
    },
    "trigger_keywords": {
        "tr": ["kariyer", "meslek", "işi", "bölüm", "eğilim", "iş"],
        "en": ["career", "job", "profession", "work", "occupation"],
        "de": ["karriere", "beruf", "arbeit"],
        "ru": ["карьера", "работа", "профессия"],
        "ar": ["مهنة", "عمل", "وظيفة"],
        "es": ["carrera", "trabajo", "profesión"],
        "ko": ["경력", "직업", "일"],
        "ja": ["キャリア", "職業", "仕事"],
        "zh": ["职业", "工作", "事业"],
        "hi": ["कैरियर", "काम", "व्यवसाय"],
        "fr": ["carrière", "travail", "profession"],
        "pt": ["carreira", "trabalho", "profissão"],
        "bn": ["ক্যারিয়ার", "কাজ", "পেশা"],
        "id": ["karir", "pekerjaan", "profesi"],
        "ur": ["کیریئر", "کام", "پیشہ"],
        "it": ["carriera", "lavoro", "professione"],
        "vi": ["sự nghiệp", "công việc", "nghề"],
        "pl": ["kariera", "praca", "zawód"],
    },
    "description": {
        "tr": "Kariyer eğilimlerini ölçen 20 sorulu test. Analitik, Yaratıcı, Sosyal, Girişimci, Yönetim ve Teknik yeteneğinizi keşfeder.",
        "en": "20-question test measuring career aptitude. Discovers your analytical, creative, social, entrepreneurial, managerial, and technical abilities.",
        "de": "Test zur Messung der Karriereeignung.",
        "ru": "Тест для измерения карьерных способностей.",
        "ar": "اختبار لقياس الكفاءة الوظيفية.",
        "es": "Test que mide la aptitud profesional.",
        "ko": "경력 적성을 측정하는 테스트.",
        "ja": "キャリア適性を測定するテスト。",
        "zh": "测量职业能力的测试。",
        "hi": "कैरियर योग्यता को मापने वाली परीक्षा।",
        "fr": "Test mesurant l'aptitude professionnelle.",
        "pt": "Teste que mede a aptidão profissional.",
        "bn": "ক্যারিয়ার যোগ্যতা পরিমাপ করার পরীক্ষা।",
        "id": "Test yang mengukur bakat karir.",
        "ur": "کیریئر کی صلاحیت کو ماپنے والی جانچ۔",
        "it": "Test che misura l'attitudine professionale.",
        "vi": "Bài kiểm tra đo lường khả năng sự nghiệp.",
        "pl": "Test mierzący zdolności zawodowe.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "Kariyer yolunuzu keşfedelim. 20 soruda sizin kariyer profili ortaya çıkacak.",
        "en": "Let's discover your ideal career path. 20 questions to reveal your strengths.",
        "de": "Entdecken Sie Ihren idealen Karriereweg.",
        "ru": "Откройте для себя идеальный карьерный путь.",
        "ar": "اكتشف المسار الوظيفي المثالي لك.",
        "es": "Descubre tu camino profesional ideal.",
        "ko": "이상적인 경력 경로를 발견하세요.",
        "ja": "理想的なキャリアパスを発見しましょう。",
        "zh": "发现您理想的职业道路。",
        "hi": "अपने आदर्श कैरियर पथ की खोज करें।",
        "fr": "Découvrez votre cheminement professionnel idéal.",
        "pt": "Descubra seu caminho profissional ideal.",
        "bn": "আপনার আদর্শ ক্যারিয়ার পথ আবিষ্কার করুন।",
        "id": "Temukan jalur karir ideal Anda.",
        "ur": "اپنے بہترین کیریئر کا راستہ دریافت کریں۔",
        "it": "Scopri il tuo percorso di carriera ideale.",
        "vi": "Khám phá con đường sự nghiệp lý tưởng của bạn.",
        "pl": "Odkryj swoją idealną ścieżkę kariery.",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 4: HR / WORK STYLE TEST
# ──────────────────────────────────────────────────────────────────────────

TEST_HR = {
    "name": "test_hr",
    "display": {
        "tr": "İK / Çalışma Stili Testi",
        "en": "HR / Work Style Test",
        "de": "HR / Arbeitsart-Test",
        "ru": "HR / Тест стиля работы",
        "ar": "اختبار نمط العمل",
        "es": "Test de Estilo de Trabajo",
        "ko": "HR / 업무 스타일 테스트",
        "ja": "HR / 仕事スタイルテスト",
        "zh": "人力资源/工作风格测试",
        "hi": "HR / कार्य शैली परीक्षण",
        "fr": "RH / Test de Style de Travail",
        "pt": "RH / Teste de Estilo de Trabalho",
        "bn": "এইচআর / কাজের শৈলী পরীক্ষা",
        "id": "HR / Test Gaya Kerja",
        "ur": "HR / کام کی انداز کی جانچ",
        "it": "HR / Test dello Stile di Lavoro",
        "vi": "HR / Bài kiểm tra Phong cách làm việc",
        "pl": "HR / Test Stylu Pracy",
    },
    "trigger_keywords": {
        "tr": ["çalışma", "takım", "liderlik", "iş ortamı", "hr"],
        "en": ["work", "team", "leadership", "workplace", "hr"],
        "de": ["arbeit", "team", "führung", "arbeitsplatz"],
        "ru": ["работа", "команда", "лидерство", "рабочая среда"],
        "ar": ["عمل", "فريق", "قيادة", "بيئة العمل"],
        "es": ["trabajo", "equipo", "liderazgo", "ambiente de trabajo"],
        "ko": ["일", "팀", "리더십", "직장"],
        "ja": ["仕事", "チーム", "リーダーシップ", "職場"],
        "zh": ["工作", "团队", "领导力", "工作环境"],
        "hi": ["काम", "टीम", "नेतृत्व", "कार्य वातावरण"],
        "fr": ["travail", "équipe", "leadership", "environnement de travail"],
        "pt": ["trabalho", "equipe", "liderança", "ambiente de trabalho"],
        "bn": ["কাজ", "দল", "নেতৃত্ব", "কর্মপরিবেশ"],
        "id": ["kerja", "tim", "kepemimpinan", "lingkungan kerja"],
        "ur": ["کام", "ٹیم", "قیادت", "کام کی جگہ"],
        "it": ["lavoro", "team", "leadership", "ambiente di lavoro"],
        "vi": ["công việc", "đội", "lãnh đạo", "môi trường làm việc"],
        "pl": ["praca", "zespół", "przywództwo", "środowisko pracy"],
    },
    "description": {
        "tr": "Takım ortamında ve iş yaşamında başarınızı ölçen test. Liderlik, Takım Uyumu, İletişim, Stres Toleransı ve Motivasyon boyutlarını değerlendirir.",
        "en": "Assesses your success in team environments. Evaluates leadership, team fit, communication, stress tolerance, and motivation.",
        "de": "Bewertet Ihren Erfolg in Teamumgebungen.",
        "ru": "Оценивает ваш успех в командной среде.",
        "ar": "يقيم نجاحك في بيئات العمل الجماعية.",
        "es": "Evalúa tu éxito en entornos de equipo.",
        "ko": "팀 환경에서의 성공을 평가합니다.",
        "ja": "チーム環境でのあなたの成功を評価します。",
        "zh": "评估您在团队环境中的成功。",
        "hi": "टीम वातावरण में आपकी सफलता का मूल्यांकन करता है।",
        "fr": "Évalue votre succès dans les environnements d'équipe.",
        "pt": "Avalia seu sucesso em ambientes de equipe.",
        "bn": "দলীয় পরিবেশে আপনার সফলতা মূল্যায়ন করে।",
        "id": "Mengevaluasi kesuksesan Anda dalam lingkungan tim.",
        "ur": "ٹیم کے ماحول میں آپ کی کامیابی کا تشخیص کرتا ہے۔",
        "it": "Valuta il tuo successo negli ambienti di squadra.",
        "vi": "Đánh giá thành công của bạn trong môi trường đội.",
        "pl": "Ocenia Twój sukces w środowiskach zespołowych.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "İK/Çalışma Stili Testi ile takım ortamınızdaki rolünüzü keşfedin.",
        "en": "Take the HR/Work Style Test to discover your role in team environments.",
        "de": "Machen Sie den HR/Arbeitsart-Test.",
        "ru": "Пройдите тест HR/стиля работы.",
        "ar": "أجرِ اختبار نمط العمل.",
        "es": "Realiza el Test de Estilo de Trabajo.",
        "ko": "HR/업무 스타일 테스트를 받으세요.",
        "ja": "HR/仕事スタイルテストを受けてください。",
        "zh": "进行HR/工作风格测试。",
        "hi": "HR/कार्य शैली परीक्षण लें।",
        "fr": "Passez le Test de Style de Travail RH.",
        "pt": "Faça o Teste de Estilo de Trabalho RH.",
        "bn": "এইচআর/কাজের শৈলী পরীক্ষা নিন।",
        "id": "Lakukan Test Gaya Kerja HR.",
        "ur": "HR/کام کی انداز کی جانچ لیں۔",
        "it": "Fai il Test dello Stile di Lavoro HR.",
        "vi": "Thực hiện Bài kiểm tra Phong cách làm việc HR.",
        "pl": "Przejdź test stylu pracy HR.",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 5: SKILLS TEST
# ──────────────────────────────────────────────────────────────────────────

TEST_SKILLS = {
    "name": "test_skills",
    "display": {
        "tr": "Beceri Testi",
        "en": "Skills Test",
        "de": "Fertigkeitsentest",
        "ru": "Тест навыков",
        "ar": "اختبار المهارات",
        "es": "Test de Habilidades",
        "ko": "기술 테스트",
        "ja": "スキルテスト",
        "zh": "技能测试",
        "hi": "कौशल परीक्षण",
        "fr": "Test de Compétences",
        "pt": "Teste de Habilidades",
        "bn": "দক্ষতা পরীক্ষা",
        "id": "Tes Keterampilan",
        "ur": "ہنر کی جانچ",
        "it": "Test di Abilità",
        "vi": "Bài kiểm tra Kỹ năng",
        "pl": "Test Umiejętności",
    },
    "trigger_keywords": {
        "tr": ["beceri", "yetenek", "güçlü", "zayıf", "kapasite"],
        "en": ["skill", "ability", "strength", "weakness", "capability"],
        "de": ["fertigkeit", "fähigkeit", "stärke", "schwäche"],
        "ru": ["навык", "способность", "сила", "слабость"],
        "ar": ["مهارة", "قدرة", "قوة", "ضعف"],
        "es": ["habilidad", "capacidad", "fortaleza", "debilidad"],
        "ko": ["기술", "능력", "강점", "약점"],
        "ja": ["スキル", "能力", "強み", "弱み"],
        "zh": ["技能", "能力", "优势", "劣势"],
        "hi": ["कौशल", "क्षमता", "शक्ति", "कमजोरी"],
        "fr": ["compétence", "capacité", "force", "faiblesse"],
        "pt": ["habilidade", "capacidade", "força", "fraqueza"],
        "bn": ["দক্ষতা", "ক্ষমতা", "শক্তি", "দুর্বলতা"],
        "id": ["keterampilan", "kemampuan", "kekuatan", "kelemahan"],
        "ur": ["ہنر", "صلاحیت", "طاقت", "کمزوری"],
        "it": ["abilità", "capacità", "forza", "debolezza"],
        "vi": ["kỹ năng", "khả năng", "sức mạnh", "yếu điểm"],
        "pl": ["umiejętność", "zdolność", "siła", "słabość"],
    },
    "description": {
        "tr": "Temel becerilerinizi ve yeteneğinizi ölçer. Problem Çözme, Empati, Organizasyon, Öğrenme Hızı ve Karar Verme yeteneğinizi değerlendirir.",
        "en": "Evaluates your core skills and capabilities. Measures problem-solving, empathy, organization, learning speed, and decision-making.",
        "de": "Bewertet deine Kernfähigkeiten und Fähigkeiten.",
        "ru": "Оценивает ваши основные навыки и способности.",
        "ar": "يقيم مهاراتك وقدراتك الأساسية.",
        "es": "Evalúa tus habilidades y capacidades fundamentales.",
        "ko": "핵심 기술과 능력을 평가합니다.",
        "ja": "あなたのコア スキルと能力を評価します。",
        "zh": "评估您的核心技能和能力。",
        "hi": "आपकी मूल कौशल और क्षमता का मूल्यांकन करता है।",
        "fr": "Évalue vos compétences et capacités fondamentales.",
        "pt": "Avalia suas habilidades e capacidades fundamentais.",
        "bn": "আপনার মূল দক্ষতা এবং ক্ষমতা মূল্যায়ন করে।",
        "id": "Mengevaluasi keterampilan dan kemampuan inti Anda.",
        "ur": "آپ کی بنیادی کاری صلاحیت اور صلاحیت کا اندازہ کرتا ہے۔",
        "it": "Valuta le tue abilità e capacità fondamentali.",
        "vi": "Đánh giá các kỹ năng và khả năng cốt lõi của bạn.",
        "pl": "Ocenia Twoje umiejętności i zdolności podstawowe.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "Beceri testimi alalım mı? 20 soruda gizli potansiyelinizi ortaya koyacağız.",
        "en": "Let's take your skills test. 20 questions to reveal your hidden potential.",
        "de": "Lassen Sie uns Ihren Fertigkeitentest machen.",
        "ru": "Давайте пройдём тест ваших навыков.",
        "ar": "دعنا نجري اختبار مهاراتك.",
        "es": "Realicemos tu test de habilidades.",
        "ko": "기술 테스트를 해보세요.",
        "ja": "スキル テストを受けましょう。",
        "zh": "让我们进行您的技能测试。",
        "hi": "आइए आपकी कौशल परीक्षा लें।",
        "fr": "Passons votre test de compétences.",
        "pt": "Vamos fazer seu teste de habilidades.",
        "bn": "আসুন আপনার দক্ষতা পরীক্ষা নিই।",
        "id": "Mari kita lakukan tes keterampilan Anda.",
        "ur": "آئیں آپ کی کاری جانچ لیتے ہیں۔",
        "it": "Facciamo il tuo test di abilità.",
        "vi": "Hãy làm bài kiểm tra kỹ năng của bạn.",
        "pl": "Zróbmy test Twoich umiejętności.",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 6: VOCATION TEST (Holland RIASEC)
# ──────────────────────────────────────────────────────────────────────────

TEST_VOCATION = {
    "name": "test_vocation",
    "display": {
        "tr": "Meslek Tercihi Testi",
        "en": "Vocational Test (Holland RIASEC)",
        "de": "Beruflichkeitstest",
        "ru": "Тест профессиональной пригодности",
        "ar": "اختبار المهنة",
        "es": "Test Vocacional",
        "ko": "직업 선택 테스트",
        "ja": "職業適性テスト",
        "zh": "职业选择测试",
        "hi": "व्यावसायिक परीक्षण",
        "fr": "Test Professionnel",
        "pt": "Teste Vocacional",
        "bn": "পেশাদার পরীক্ষা",
        "id": "Tes Kejuruan",
        "ur": "پیشہ کا انتخاب ٹیسٹ",
        "it": "Test Vocazionale",
        "vi": "Bài kiểm tra Lựa chọn nghề",
        "pl": "Test Zawodowy",
    },
    "trigger_keywords": {
        "tr": ["meslek", "vocasyon", "holland", "riasec", "ideal iş"],
        "en": ["vocation", "vocational", "holland", "riasec", "ideal job"],
        "de": ["beruf", "beruflich", "holland", "idealberuf"],
        "ru": ["профессия", "профессиональный", "идеальная работа"],
        "ar": ["مهنة", "مهني", "العمل المثالي"],
        "es": ["vocación", "vocacional", "trabajo ideal"],
        "ko": ["직업", "직업적", "이상적인 일"],
        "ja": ["職業", "職業的", "理想の仕事"],
        "zh": ["职业", "职业性", "理想工作"],
        "hi": ["व्यवसाय", "व्यावसायिक", "आदर्श काम"],
        "fr": ["vocation", "professionnel", "travail idéal"],
        "pt": ["vocação", "vocacional", "trabalho ideal"],
        "bn": ["পেশা", "পেশাদার", "আদর্শ কাজ"],
        "id": ["voikasi", "kejuruan", "pekerjaan ideal"],
        "ur": ["پیشہ", "پیشہ ورانہ", "بہترین کام"],
        "it": ["vocazione", "professionale", "lavoro ideale"],
        "vi": ["nghề", "nghề nghiệp", "công việc lý tưởng"],
        "pl": ["zawód", "zawodowy", "idealna praca"],
    },
    "description": {
        "tr": "Holland RIASEC modeli ile ideal mesleğinizi bulun. 20 soruda Gerçekçi, Araştırmacı, Sanatsal, Sosyal, Girişimci ve Geleneksel eğilimlerinizi ortaya çıkarın.",
        "en": "Discover your ideal profession using Holland's RIASEC model. 20 questions reveal your Realistic, Investigative, Artistic, Social, Enterprising, or Conventional interests.",
        "de": "Entdecken Sie Ihren Idealberuf mit dem Holland-Modell.",
        "ru": "Откройте для себя идеальную профессию с помощью модели Голланда.",
        "ar": "اكتشف مهنتك المثالية باستخدام نموذج هولندا.",
        "es": "Descubre tu profesión ideal con el modelo Holland.",
        "ko": "Holland 모델로 이상적인 직업을 찾으세요.",
        "ja": "Hollandモデルであなたの理想的な職業を発見してください。",
        "zh": "使用Holland模型发现您的理想职业。",
        "hi": "Holland मॉडल के साथ अपने आदर्श व्यवसाय की खोज करें।",
        "fr": "Découvrez votre profession idéale avec le modèle Holland.",
        "pt": "Descubra sua profissão ideal com o modelo Holland.",
        "bn": "Holland মডেলের সাথে আপনার আদর্শ পেশা আবিষ্কার করুন।",
        "id": "Temukan profesi ideal Anda dengan model Holland.",
        "ur": "Holland ماڈل سے اپنا بہترین پیشہ تلاش کریں۔",
        "it": "Scopri la tua professione ideale con il modello Holland.",
        "vi": "Khám phá nghề lý tưởng của bạn với mô hình Holland.",
        "pl": "Odkryj swoją idealną zawód za pomocą modelu Hollanda.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "Meslek tercihi testini yapalım? Holland modeli ile idealbir kariyerin anahtarını bulacağız.",
        "en": "Ready for the vocational test? Discover your ideal career path with Holland's model.",
        "de": "Bereit für den Beruflichkeitstest?",
        "ru": "Готовы к тесту профессиональной пригодности?",
        "ar": "هل أنت مستعد لاختبار المهنة؟",
        "es": "¿Listo para el test vocacional?",
        "ko": "직업 선택 테스트를 시작할까요?",
        "ja": "職業適性テストを受ける準備はいいですか？",
        "zh": "准备好进行职业选择测试了吗？",
        "hi": "व्यावसायिक परीक्षा के लिए तैयार?",
        "fr": "Êtes-vous prêt pour le test professionnel?",
        "pt": "Pronto para o teste vocacional?",
        "bn": "পেশাদার পরীক্ষার জন্য প্রস্তুত?",
        "id": "Siap untuk tes kejuruan?",
        "ur": "پیشہ کی جانچ کے لیے تیار؟",
        "it": "Pronto per il test vocazionale?",
        "vi": "Sẵn sàng cho bài kiểm tra lựa chọn nghề chưa?",
        "pl": "Gotów do testu zawodowego?",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 7: RELATIONSHIP TEST
# ──────────────────────────────────────────────────────────────────────────

TEST_RELATIONSHIP = {
    "name": "test_relationship",
    "display": {
        "tr": "İlişki & EQ Testi",
        "en": "Relationship & EQ Test",
        "de": "Beziehungs- und EQ-Test",
        "ru": "Тест отношений и эмоциональный интеллект",
        "ar": "اختبار العلاقات والذكاء العاطفي",
        "es": "Test de Relaciones y IE",
        "ko": "관계 및 EQ 테스트",
        "ja": "関係とEQテスト",
        "zh": "关系和情商测试",
        "hi": "संबंध और EQ परीक्षण",
        "fr": "Test de Relation et EI",
        "pt": "Teste de Relacionamento e IE",
        "bn": "সম্পর্ক এবং EQ পরীক্ষা",
        "id": "Tes Hubungan dan EQ",
        "ur": "تعلقات اور EQ ٹیسٹ",
        "it": "Test di Relazione e QE",
        "vi": "Bài kiểm tra Mối quan hệ và EQ",
        "pl": "Test Relacji i EQ",
    },
    "trigger_keywords": {
        "tr": ["ilişki", "sevgi", "dil", "bağlanma", "duygusal zeka", "eq"],
        "en": ["relationship", "love", "attachment", "emotional intelligence", "eq"],
        "de": ["beziehung", "liebe", "bindung", "emotionale intelligenz"],
        "ru": ["отношение", "любовь", "привязанность", "эмоциональный интеллект"],
        "ar": ["علاقة", "حب", "ارتباط", "ذكاء عاطفي"],
        "es": ["relación", "amor", "apego", "inteligencia emocional"],
        "ko": ["관계", "사랑", "애착", "감정지능"],
        "ja": ["関係", "愛", "愛着", "感情知能"],
        "zh": ["关系", "爱", "依恋", "情感智力"],
        "hi": ["संबंध", "प्रेम", "लगाव", "भावनात्मक बुद्धिमत्ता"],
        "fr": ["relation", "amour", "attachement", "intelligence émotionnelle"],
        "pt": ["relacionamento", "amor", "apego", "inteligência emocional"],
        "bn": ["সম্পর্ক", "ভালোবাসা", "সংযুক্তি", "আবেগজনক বুদ্ধিমত্তা"],
        "id": ["hubungan", "cinta", "ikatan", "kecerdasan emosional"],
        "ur": ["رشتہ", "محبت", "تعلق", "جذباتی ذہانت"],
        "it": ["relazione", "amore", "attaccamento", "intelligenza emotiva"],
        "vi": ["mối quan hệ", "tình yêu", "gắn bó", "trí tuệ cảm xúc"],
        "pl": ["relacja", "miłość", "przywiązanie", "inteligencja emocjonalna"],
    },
    "description": {
        "tr": "Romantik ilişkilerin ve duygusal zekanızın derinlikli analizi. Bağlanma Stili, Sevgi Dili, İlişki Beklentileri ve Duygusal Zeka boyutlarını ölçer.",
        "en": "Deep analysis of your romantic relationships and emotional intelligence. Measures attachment style, love language, relationship values, and emotional awareness.",
        "de": "Tiefenanalyse Ihrer romantischen Beziehungen und emotionalen Intelligenz.",
        "ru": "Глубокий анализ ваших романтических отношений и эмоционального интеллекта.",
        "ar": "تحليل عميق لعلاقاتك الرومانسية والذكاء العاطفي.",
        "es": "Análisis profundo de sus relaciones románticas e inteligencia emocional.",
        "ko": "낭만적인 관계와 감정지능에 대한 깊이 있는 분석.",
        "ja": "ロマンチックな関係と感情知能の深い分析。",
        "zh": "对您的浪漫关系和情感智力的深度分析。",
        "hi": "आपके रोमांटिक संबंधों और भावनात्मक बुद्धिमत्ता का गहन विश्लेषण।",
        "fr": "Analyse approfondie de vos relations romantiques et de votre intelligence émotionnelle.",
        "pt": "Análise profunda de seus relacionamentos românticos e inteligência emocional.",
        "bn": "আপনার রোমান্টিক সম্পর্ক এবং আবেগজনক বুদ্ধিমত্তার গভীর বিশ্লেষণ।",
        "id": "Analisis mendalam tentang hubungan romantis dan kecerdasan emosional Anda.",
        "ur": "آپ کے رومانوی تعلقات اور جذباتی ذہانت کا گہرائی سے تجزیہ۔",
        "it": "Analisi profonda dei tuoi rapporti romantici e dell'intelligenza emotiva.",
        "vi": "Phân tích sâu về các mối quan hệ lãng mạn và trí tuệ cảm xúc của bạn.",
        "pl": "Głęboka analiza twoich relacji romantycznych i inteligencji emocjonalnej.",
    },
    "requires_input": "none",
    "endpoint": "http://test:8004/test/start",
    "method": "POST",
    "input_prompt": {
        "tr": "Duygusal zekanızı ve ilişki stilinizi keşfedelim. 20 soruda sevginizin dilini ve bağlanma tarzınızı ortaya çıkaracağız.",
        "en": "Discover your emotional intelligence and relationship style. 20 questions reveal your love language and attachment style.",
        "de": "Entdecken Sie Ihre emotionale Intelligenz und Ihren Beziehungsstil.",
        "ru": "Откройте для себя свой эмоциональный интеллект и стиль отношений.",
        "ar": "اكتشف ذكاءك العاطفي وأسلوب علاقاتك.",
        "es": "Descubre tu inteligencia emocional y estilo de relación.",
        "ko": "감정지능과 관계 스타일을 발견하세요.",
        "ja": "感情知能と関係スタイルを発見してください。",
        "zh": "发现您的情感智力和关系风格。",
        "hi": "अपनी भावनात्मक बुद्धिमत्ता और संबंध शैली की खोज करें।",
        "fr": "Découvrez votre intelligence émotionnelle et votre style de relation.",
        "pt": "Descubra sua inteligência emocional e estilo de relacionamento.",
        "bn": "আপনার আবেগজনক বুদ্ধিমত্তা এবং সম্পর্কের শৈলী আবিষ্কার করুন।",
        "id": "Temukan kecerdasan emosional dan gaya hubungan Anda.",
        "ur": "اپنی جذباتی ذہانت اور تعلق کی شیلی دریافت کریں۔",
        "it": "Scopri la tua intelligenza emotiva e il tuo stile di relazione.",
        "vi": "Khám phá trí tuệ cảm xúc và phong cách mối quan hệ của bạn.",
        "pl": "Odkryj swoją inteligencję emocjonalną i styl relacji.",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULE 8: FACE ANALYSIS (PHRENOLOGY)
# ──────────────────────────────────────────────────────────────────────────

FACE_ANALYSIS = {
    "name": "face_analysis",
    "display": {
        "tr": "Yüz Analizi (Frenoloji)",
        "en": "Face Analysis (Phrenology)",
        "de": "Gesichtsanalyse (Phrenologie)",
        "ru": "Анализ лица (Френология)",
        "ar": "تحليل الوجه (فرينولوجيا)",
        "es": "Análisis Facial (Frenología)",
        "ko": "얼굴 분석 (골상학)",
        "ja": "顔分析（骨相学）",
        "zh": "面部分析（颅相学）",
        "hi": "चेहरे का विश्लेषण (फ्रेनोलॉजी)",
        "fr": "Analyse Faciale (Phrénologie)",
        "pt": "Análise Facial (Frenologia)",
        "bn": "মুখ বিশ্লেষণ (ফ্রেনোলজি)",
        "id": "Analisis Wajah (Frenologi)",
        "ur": "چہرے کا تجزیہ (فرینولوجی)",
        "it": "Analisi Facciale (Frenologia)",
        "vi": "Phân tích Khuôn mặt (Phrenology)",
        "pl": "Analiza Twarzy (Frenologia)",
    },
    "trigger_keywords": {
        "tr": ["selfie", "yüz", "fotoğraf", "analiz", "frenoloji", "karakterim"],
        "en": ["selfie", "face", "photo", "analyze", "phrenology", "character"],
        "de": ["selfie", "gesicht", "foto", "analyse"],
        "ru": ["селфи", "лицо", "фото", "анализ"],
        "ar": ["سيلفي", "وجه", "صورة", "تحليل"],
        "es": ["selfie", "cara", "foto", "análisis"],
        "ko": ["셀피", "얼굴", "사진", "분석"],
        "ja": ["セルフィー", "顔", "写真", "分析"],
        "zh": ["自拍", "脸", "照片", "分析"],
        "hi": ["सेल्फी", "चेहरा", "फोटो", "विश्लेषण"],
        "fr": ["selfie", "visage", "photo", "analyse"],
        "pt": ["selfie", "rosto", "foto", "análise"],
        "bn": ["সেলফি", "মুখ", "ছবি", "বিশ্লেষণ"],
        "id": ["selfie", "wajah", "foto", "analisis"],
        "ur": ["سیلفی", "چہرہ", "عکس", "تجزیہ"],
        "it": ["selfie", "viso", "foto", "analisi"],
        "vi": ["selfie", "khuôn mặt", "ảnh", "phân tích"],
        "pl": ["selfie", "twarz", "zdjęcie", "analiza"],
    },
    "description": {
        "tr": "Selfie çekerek yüz özelliklerinizden karakter analizi yapıyorum. Fiziksel özelliklerinizle kişiliğinizi bağlantılandırırım.",
        "en": "Upload a selfie to analyze your character from facial features. Links physical characteristics to personality traits.",
        "de": "Laden Sie ein Selfie hoch, um Ihren Charakter aus Gesichtszügen zu analysieren.",
        "ru": "Загрузите селфи для анализа вашего характера по чертам лица.",
        "ar": "حمّل صورة شخصية لتحليل شخصيتك من ملامح الوجه.",
        "es": "Sube un selfie para analizar tu carácter a partir de los rasgos faciales.",
        "ko": "셀피를 업로드하여 얼굴 특징으로 성격을 분석하세요.",
        "ja": "セルフィーをアップロードして、顔の特徴からキャラクターを分析します。",
        "zh": "上传自拍照来分析您的面部特征和性格。",
        "hi": "अपने चेहरे की विशेषताओं से व्यक्तित्व का विश्लेषण करने के लिए एक सेल्फी अपलोड करें।",
        "fr": "Téléchargez un selfie pour analyser votre caractère à partir des traits du visage.",
        "pt": "Faça upload de um selfie para analisar seu caráter a partir dos traços faciais.",
        "bn": "আপনার চেহরার বৈশিষ্ট্য থেকে ব্যক্তিত্ব বিশ্লেষণ করতে একটি সেলফি আপলোড করুন।",
        "id": "Unggah selfie untuk menganalisis karakter Anda dari fitur wajah.",
        "ur": "اپنے چہرے کی خصوصیات سے شخصیت کا تجزیہ کرنے کے لیے ایک سیلفی اپ لوڈ کریں۔",
        "it": "Carica un selfie per analizzare il tuo carattere dai tratti del viso.",
        "vi": "Tải lên một selfie để phân tích tính cách của bạn từ các đặc điểm khuôn mặt.",
        "pl": "Prześlij selfie, aby przeanalizować swoją osobowość na podstawie cech twarzy.",
    },
    "requires_input": "none",
    "endpoint": "http://backend:8000/api/v1/analysis/analyze/",
    "method": "POST",
    "input_prompt": {
        "tr": "Bir selfie çekerseniz yüzünüzün fiziksel özelliklerinden karakter analizi yapabilirim.",
        "en": "If you take a selfie, I can analyze your character from your facial features.",
        "de": "Wenn Sie ein Selfie machen, kann ich Ihren Charakter aus Ihren Gesichtszügen analysieren.",
        "ru": "Если вы сделаете селфи, я смогу проанализировать ваш характер по чертам лица.",
        "ar": "إذا التقطت صورة شخصية، يمكنني تحليل شخصيتك من ملامح وجهك.",
        "es": "Si tomas un selfie, puedo analizar tu carácter a partir de tus rasgos faciales.",
        "ko": "셀피를 촬영하면 얼굴 특징으로 성격을 분석할 수 있습니다.",
        "ja": "セルフィーを撮ると、顔の特徴からキャラクターを分析できます。",
        "zh": "如果你自拍，我可以根据你的面部特征来分析你的性格。",
        "hi": "अगर आप सेल्फी लेते हैं, तो मैं आपके चेहरे की विशेषताओं से आपके व्यक्तित्व का विश्लेषण कर सकता हूं।",
        "fr": "Si vous prenez un selfie, je peux analyser votre caractère à partir de vos traits du visage.",
        "pt": "Se você tirar um selfie, posso analisar seu caráter a partir de seus traços faciais.",
        "bn": "আপনি যদি একটি সেল্ফি নেন, আমি আপনার চেহরার বৈশিষ্ট্য থেকে আপনার ব্যক্তিত্ব বিশ্লেষণ করতে পারি।",
        "id": "Jika Anda mengambil selfie, saya dapat menganalisis karakter Anda dari fitur wajah Anda.",
        "ur": "اگر آپ سیلفی لیتے ہیں، تو میں آپ کے چہرے کی خصوصیات سے آپ کی شخصیت کا تجزیہ کر سکتا ہوں۔",
        "it": "Se scatti un selfie, posso analizzare il tuo carattere dai tuoi tratti del viso.",
        "vi": "Nếu bạn chụp một selfie, tôi có thể phân tích tính cách của bạn từ các đặc điểm khuôn mặt.",
        "pl": "Jeśli zrobisz selfie, mogę przeanalizować twoją osobowość na podstawie cech twarzy.",
    }
}

# ──────────────────────────────────────────────────────────────────────────
# MODULES 9-21: COACH MODULES (13 modules)
# ──────────────────────────────────────────────────────────────────────────

# Helper function to create coach module
def _make_coach_module(name: str, display: dict, keywords: dict, description: dict) -> dict:
    return {
        "name": f"coach_{name}",
        "display": display,
        "trigger_keywords": keywords,
        "description": description,
        "requires_input": "none",
        "endpoint": "http://coach:8003/coach/analyze/",
        "method": "POST",
        "input_prompt": display,
    }

# 1. Tavsiye (Personal Advice)
COACH_TAVSIYE = _make_coach_module(
    "tavsiye",
    {
        "tr": "Kişisel Tavsiyeler", "en": "Personal Advice", "de": "Persönliche Ratschläge",
        "ru": "Личный совет", "ar": "نصيحة شخصية", "es": "Consejo Personal", "ko": "개인 조언",
        "ja": "個人的なアドバイス", "zh": "个人建议", "hi": "व्यक्तिगत सलाह", "fr": "Conseil Personnel",
        "pt": "Conselho Pessoal", "bn": "ব্যক্তিগত পরামর্শ", "id": "Saran Pribadi", "ur": "ذاتی مشورہ",
        "it": "Consiglio Personale", "vi": "Lời khuyên cá nhân", "pl": "Porada Osobista",
    },
    {
        "tr": ["tavsiye", "fikir", "rehberlik", "yardım"], "en": ["advice", "suggest", "guide"],
        "de": ["ratschlag", "beratung"], "ru": ["совет", "рекомендация"], "ar": ["نصيحة", "اقتراح"],
        "es": ["consejo", "sugerencia"], "ko": ["조언", "제안"], "ja": ["アドバイス", "提案"],
        "zh": ["建议", "提议"], "hi": ["सलाह", "सुझाव"], "fr": ["conseil", "suggestion"],
        "pt": ["conselho", "sugestão"], "bn": ["পরামর্শ", "পরামর্শ"], "id": ["saran", "usul"],
        "ur": ["مشورہ", "تجویز"], "it": ["consiglio", "suggerimento"], "vi": ["lời khuyên", "gợi ý"],
        "pl": ["rada", "sugestia"],
    },
    {
        "tr": "Kişisel durumunuza göre özel tavsiyeler alır.",
        "en": "Get personalized advice for your situation.",
        "de": "Erhalten Sie personalisierte Ratschläge für Ihre Situation.",
        "ru": "Получите персональный совет для вашей ситуации.",
        "ar": "احصل على نصيحة شخصية لحالتك.",
        "es": "Obtén consejos personalizados para tu situación.",
        "ko": "당신의 상황에 맞는 개인화된 조언을 받으세요.",
        "ja": "あなたの状況に合わせたパーソナライズされたアドバイスを受け取ります。",
        "zh": "获取针对您情况的个性化建议。",
        "hi": "अपनी परिस्थिति के लिए व्यक्तिगत सलाह प्राप्त करें।",
        "fr": "Obtenez des conseils personnalisés pour votre situation.",
        "pt": "Obtenha conselhos personalizados para sua situação.",
        "bn": "আপনার পরিস্থিতির জন্য ব্যক্তিগত পরামর্শ পান।",
        "id": "Dapatkan saran yang dipersonalisasi untuk situasi Anda.",
        "ur": "اپنی صورتحال کے لیے ذاتی مشورہ حاصل کریں۔",
        "it": "Ottieni consigli personalizzati per la tua situazione.",
        "vi": "Nhận lời khuyên được cá nhân hóa cho tình huống của bạn.",
        "pl": "Uzyskaj spersonalizowane porady dla swojej sytuacji.",
    },
)

# 2. Motivasyon
COACH_MOTIVASYON = _make_coach_module(
    "motivasyon",
    {
        "tr": "Motivasyon", "en": "Motivation", "de": "Motivation", "ru": "Мотивация",
        "ar": "تحفيز", "es": "Motivación", "ko": "동기", "ja": "モチベーション",
        "zh": "动力", "hi": "प्रेरणा", "fr": "Motivation", "pt": "Motivação",
        "bn": "অনুপ্রেরণা", "id": "Motivasi", "ur": "حوصلہ", "it": "Motivazione",
        "vi": "Động lực", "pl": "Motywacja",
    },
    {
        "tr": ["motivasyon", "enerji", "başarı", "hedef"], "en": ["motivation", "energy", "goal", "success"],
        "de": ["motivation", "energie", "erfolg"], "ru": ["мотивация", "энергия", "успех"],
        "ar": ["تحفيز", "طاقة", "نجاح"], "es": ["motivación", "energía", "éxito"],
        "ko": ["동기", "에너지", "성공"], "ja": ["モチベーション", "エネルギー", "成功"],
        "zh": ["动力", "能量", "成功"], "hi": ["प्रेरणा", "ऊर्जा", "सफलता"],
        "fr": ["motivation", "énergie", "succès"], "pt": ["motivação", "energia", "sucesso"],
        "bn": ["অনুপ্রেরণা", "শক্তি", "সাফল্য"], "id": ["motivasi", "energi", "kesuksesan"],
        "ur": ["حوصلہ", "توانائی", "کامیابی"], "it": ["motivazione", "energia", "successo"],
        "vi": ["động lực", "năng lượng", "thành công"], "pl": ["motywacja", "energia", "sukces"],
    },
    {
        "tr": "Her gün sizi motive edecek öneriler.",
        "en": "Daily motivation and inspiration.",
        "de": "Tägliche Motivation und Inspiration.",
        "ru": "Ежедневная мотивация и вдохновение.",
        "ar": "تحفيز يومي والهام.",
        "es": "Motivación diaria e inspiración.",
        "ko": "매일 동기 부여와 영감.",
        "ja": "毎日のモチベーションとインスピレーション。",
        "zh": "每日动力和灵感。",
        "hi": "दैनिक प्रेरणा और अनुप्रेरणा।",
        "fr": "Motivation quotidienne et inspiration.",
        "pt": "Motivação diária e inspiração.",
        "bn": "দৈনিক অনুপ্রেরণা এবং প্রেরণা।",
        "id": "Motivasi harian dan inspirasi.",
        "ur": "روزانہ حوصلہ اور الہام۔",
        "it": "Motivazione quotidiana e ispirazione.",
        "vi": "Động lực hàng ngày và cảm hứng.",
        "pl": "Codzienna motywacja i inspiracja.",
    },
)

# 3. Etkinlik (Activities)
COACH_ETKINLIK = _make_coach_module(
    "etkinlik",
    {
        "tr": "Etkinlik Önerileri", "en": "Activity Suggestions", "de": "Aktivitätsvorschläge",
        "ru": "Рекомендации по деятельности", "ar": "اقتراحات الأنشطة", "es": "Sugerencias de Actividad",
        "ko": "활동 제안", "ja": "活動提案", "zh": "活动建议", "hi": "गतिविधि सुझाव",
        "fr": "Suggestions d'Activité", "pt": "Sugestões de Atividade", "bn": "কার্যকলাপের পরামর্শ",
        "id": "Saran Aktivitas", "ur": "سرگرمی کی تجاویز", "it": "Suggerimenti di Attività",
        "vi": "Gợi ý hoạt động", "pl": "Sugestie Aktywności",
    },
    {
        "tr": ["etkinlik", "aktivite", "yap", "hobi"], "en": ["activity", "do", "hobby", "engage"],
        "de": ["aktivität", "hobby", "engagement"], "ru": ["деятельность", "хобби"],
        "ar": ["نشاط", "هواية"], "es": ["actividad", "hobby"], "ko": ["활동", "취미"],
        "ja": ["活動", "趣味"], "zh": ["活动", "爱好"], "hi": ["गतिविधि", "शौक"],
        "fr": ["activité", "hobby"], "pt": ["atividade", "hobby"], "bn": ["কার্যকলাপ", "শখ"],
        "id": ["aktivitas", "hobi"], "ur": ["سرگرمی", "مشغلہ"], "it": ["attività", "hobby"],
        "vi": ["hoạt động", "sở thích"], "pl": ["aktywność", "hobby"],
    },
    {
        "tr": "Size uygun etkinlik ve hobiler önerilir.",
        "en": "Get activity suggestions tailored to you.",
        "de": "Erhalten Sie Aktivitätsvorschläge, die auf Sie zugeschnitten sind.",
        "ru": "Получите рекомендации по деятельности, адаптированные к вам.",
        "ar": "احصل على اقتراحات الأنشطة المخصصة لك.",
        "es": "Obtén sugerencias de actividad adaptadas a ti.",
        "ko": "당신에게 맞춘 활동 제안을 받으세요.",
        "ja": "あなた向けにカスタマイズされた活動提案を取得します。",
        "zh": "获取针对您的活动建议。",
        "hi": "आपके लिए तैयार की गई गतिविधि सुझाव प्राप्त करें।",
        "fr": "Obtenez des suggestions d'activité adaptées à vous.",
        "pt": "Obtenha sugestões de atividade personalizadas.",
        "bn": "আপনার জন্য তৈরি কার্যকলাপ পরামর্শ পান।",
        "id": "Dapatkan saran aktivitas yang disesuaikan dengan Anda.",
        "ur": "اپنے لیے تیار کی گئی سرگرمی کی تجاویز حاصل کریں۔",
        "it": "Ottieni suggerimenti di attività personalizzati.",
        "vi": "Nhận gợi ý hoạt động được cá nhân hóa cho bạn.",
        "pl": "Uzyskaj spersonalizowane sugestie aktywności.",
    },
)

# 4. Muzik (Music)
COACH_MUZIK = _make_coach_module(
    "muzik",
    {
        "tr": "Müzik Önerileri", "en": "Music Recommendations", "de": "Musikempfehlungen",
        "ru": "Рекомендации по музыке", "ar": "توصيات الموسيقى", "es": "Recomendaciones de Música",
        "ko": "음악 추천", "ja": "音楽の推奨", "zh": "音乐推荐", "hi": "संगीत सिफारिशें",
        "fr": "Recommandations Musicales", "pt": "Recomendações Musicais", "bn": "সঙ্গীত সুপারিশ",
        "id": "Rekomendasi Musik", "ur": "موسیقی کی سفارشات", "it": "Raccomandazioni Musicali",
        "vi": "Gợi ý âm nhạc", "pl": "Rekomendacje Muzyczne",
    },
    {
        "tr": ["müzik", "şarkı", "dinleme"], "en": ["music", "song", "listen"], "de": ["musik", "lied"],
        "ru": ["музыка", "песня"], "ar": ["موسيقى", "أغنية"], "es": ["música", "canción"],
        "ko": ["음악", "노래"], "ja": ["音楽", "歌"], "zh": ["音乐", "歌曲"],
        "hi": ["संगीत", "गीत"], "fr": ["musique", "chanson"], "pt": ["música", "canção"],
        "bn": ["সঙ্গীত", "গান"], "id": ["musik", "lagu"], "ur": ["موسیقی", "گانا"],
        "it": ["musica", "canzone"], "vi": ["âm nhạc", "bài hát"], "pl": ["muzyka", "piosenka"],
    },
    {
        "tr": "Kişiliğinize uygun müzik önerileri.",
        "en": "Music recommendations based on your personality.",
        "de": "Musikempfehlungen basierend auf Ihrer Persönlichkeit.",
        "ru": "Рекомендации по музыке на основе вашей личности.",
        "ar": "توصيات الموسيقى بناءً على شخصيتك.",
        "es": "Recomendaciones de música basadas en tu personalidad.",
        "ko": "당신의 성격에 기반한 음악 추천.",
        "ja": "あなたの性格に基づいた音楽の推奨。",
        "zh": "基于您的性格的音乐推荐。",
        "hi": "आपके व्यक्तित्व के आधार पर संगीत सुझाव।",
        "fr": "Recommandations musicales en fonction de votre personnalité.",
        "pt": "Recomendações de música baseadas em sua personalidade.",
        "bn": "আপনার ব্যক্তিত্বের উপর ভিত্তি করে সঙ্গীত সুপারিশ।",
        "id": "Rekomendasi musik berdasarkan kepribadian Anda.",
        "ur": "آپ کی شخصیت کی بنیاد پر موسیقی کی سفارشات۔",
        "it": "Raccomandazioni musicali basate sulla tua personalità.",
        "vi": "Gợi ý âm nhạc dựa trên tính cách của bạn.",
        "pl": "Rekomendacje muzyczne na podstawie Twojej osobowości.",
    },
)

# 5. Film & Dizi (Films/Series)
COACH_FILM_DIZI = _make_coach_module(
    "film_dizi",
    {
        "tr": "Film & Dizi Önerileri", "en": "Film & Series Recommendations", "de": "Film- und Serienempfehlungen",
        "ru": "Рекомендации по фильмам и сериалам", "ar": "توصيات الأفلام والمسلسلات",
        "es": "Recomendaciones de Películas y Series", "ko": "영화 및 시리즈 추천",
        "ja": "映画とシリーズの推奨", "zh": "电影和剧集推荐", "hi": "फिल्म और श्रृंखला सिफारिशें",
        "fr": "Recommandations de Films et Séries", "pt": "Recomendações de Filmes e Séries",
        "bn": "চলচ্চিত্র এবং সিরিজ সুপারিশ", "id": "Rekomendasi Film dan Seri",
        "ur": "فلمیں اور سیریز کی سفارشات", "it": "Raccomandazioni di Film e Serie",
        "vi": "Gợi ý phim và loạt phim", "pl": "Rekomendacje filmów i seriali",
    },
    {
        "tr": ["film", "dizi", "izle", "netflix"], "en": ["film", "series", "watch", "netflix"],
        "de": ["film", "serie", "schauen"], "ru": ["фильм", "сериал", "смотреть"],
        "ar": ["فيلم", "مسلسل", "مشاهدة"], "es": ["película", "serie", "ver"],
        "ko": ["영화", "시리즈", "보기"], "ja": ["映画", "シリーズ", "見る"],
        "zh": ["电影", "剧集", "观看"], "hi": ["फिल्म", "श्रृंखला", "देखें"],
        "fr": ["film", "série", "regarder"], "pt": ["filme", "série", "assistir"],
        "bn": ["চলচ্চিত্র", "সিরিজ", "দেখুন"], "id": ["film", "seri", "tonton"],
        "ur": ["فلم", "سیریز", "دیکھیں"], "it": ["film", "serie", "guardare"],
        "vi": ["phim", "loạt phim", "xem"], "pl": ["film", "serial", "oglądaj"],
    },
    {
        "tr": "İzlenmeye değer film ve dizi önerileri.",
        "en": "Personalized film and series recommendations.",
        "de": "Personalisierte Film- und Serienempfehlungen.",
        "ru": "Персонализированные рекомендации по фильмам и сериалам.",
        "ar": "توصيات الأفلام والمسلسلات المخصصة.",
        "es": "Recomendaciones personalizadas de películas y series.",
        "ko": "개인화된 영화 및 시리즈 추천.",
        "ja": "個人化された映画とシリーズの推奨。",
        "zh": "个性化的电影和剧集推荐。",
        "hi": "व्यक्तिगत फिल्म और श्रृंखला सिफारिशें।",
        "fr": "Recommandations personnalisées de films et séries.",
        "pt": "Recomendações personalizadas de filmes e séries.",
        "bn": "ব্যক্তিগত চলচ্চিত্র এবং সিরিজ সুপারিশ।",
        "id": "Rekomendasi film dan seri yang dipersonalisasi.",
        "ur": "ذاتی فلمیں اور سیریز کی سفارشات۔",
        "it": "Raccomandazioni personalizzate di film e serie.",
        "vi": "Gợi ý phim và loạt phim được cá nhân hóa.",
        "pl": "Spersonalizowane rekomendacje filmów i seriali.",
    },
)

# 6. Giyim (Style/Fashion)
COACH_GIYIM = _make_coach_module(
    "giyim",
    {
        "tr": "Stil & Moda Önerileri", "en": "Style & Fashion Advice", "de": "Stil- und Modeberatung",
        "ru": "Советы по стилю и моде", "ar": "نصائح الأسلوب والموضة", "es": "Consejos de Estilo y Moda",
        "ko": "스타일 및 패션 조언", "ja": "スタイルとファッションアドバイス", "zh": "风格和时尚建议",
        "hi": "शैली और फैशन सलाह", "fr": "Conseils de Style et Mode", "pt": "Conselhos de Estilo e Moda",
        "bn": "শৈলী এবং ফ্যাশন পরামর্শ", "id": "Saran Gaya dan Mode",
        "ur": "اسٹائل اور فیشن کی سلاہ", "it": "Consigli di Stile e Moda",
        "vi": "Lời khuyên về phong cách và thời trang", "pl": "Porady dotyczące stylu i mody",
    },
    {
        "tr": ["giyim", "stil", "moda", "kıyafet"], "en": ["style", "fashion", "clothes", "outfit"],
        "de": ["stil", "mode", "kleidung"], "ru": ["стиль", "мода", "одежда"],
        "ar": ["أسلوب", "موضة", "ملابس"], "es": ["estilo", "moda", "ropa"],
        "ko": ["스타일", "패션", "의류"], "ja": ["スタイル", "ファッション", "衣服"],
        "zh": ["风格", "时尚", "衣服"], "hi": ["शैली", "फैशन", "कपड़े"],
        "fr": ["style", "mode", "vêtements"], "pt": ["estilo", "moda", "roupas"],
        "bn": ["শৈলী", "ফ্যাশন", "পোশাক"], "id": ["gaya", "mode", "pakaian"],
        "ur": ["اسٹائل", "فیشن", "کپڑے"], "it": ["stile", "moda", "vestiti"],
        "vi": ["phong cách", "thời trang", "quần áo"], "pl": ["styl", "moda", "ubrania"],
    },
    {
        "tr": "Kişiliğinize uygun stil önerileri.",
        "en": "Style recommendations that match your personality.",
        "de": "Stilempfehlungen, die Ihrer Persönlichkeit entsprechen.",
        "ru": "Рекомендации по стилю, соответствующие вашей личности.",
        "ar": "توصيات الأسلوب التي تناسب شخصيتك.",
        "es": "Recomendaciones de estilo que se adapten a tu personalidad.",
        "ko": "당신의 성격에 맞는 스타일 추천.",
        "ja": "あなたの性格に合ったスタイルの推奨。",
        "zh": "与您的性格相符的风格建议。",
        "hi": "आपके व्यक्तित्व से मेल खाने वाली शैली सिफारिशें।",
        "fr": "Recommandations de style adaptées à votre personnalité.",
        "pt": "Recomendações de estilo que se adaptam à sua personalidade.",
        "bn": "আপনার ব্যক্তিত্বের সাথে মিল খাওয়া শৈলী সুপারিশ।",
        "id": "Rekomendasi gaya yang cocok dengan kepribadian Anda.",
        "ur": "آپ کی شخصیت سے مماثل اسٹائل کی سفارشات۔",
        "it": "Raccomandazioni di stile adatte alla tua personalità.",
        "vi": "Gợi ý phong cách phù hợp với tính cách của bạn.",
        "pl": "Rekomendacje stylu pasujące do Twojej osobowości.",
    },
)

# Remaining 7 modules (Liderlik, Duygusal, Uyum, Beceri, IK, Kariyer, Astroloji)
# are already covered or simpler - using the same pattern

# 7. Liderlik (Leadership)
COACH_LIDERLIK = _make_coach_module(
    "liderlik",
    {
        "tr": "Liderlik Gelişimi", "en": "Leadership Development", "de": "Führungsentwicklung",
        "ru": "Развитие лидерства", "ar": "تطوير القيادة", "es": "Desarrollo del Liderazgo",
        "ko": "리더십 개발", "ja": "リーダーシップ開発", "zh": "领导力发展",
        "hi": "नेतृत्व विकास", "fr": "Développement du Leadership", "pt": "Desenvolvimento de Liderança",
        "bn": "নেতৃত্ব উন্নয়ন", "id": "Pengembangan Kepemimpinan", "ur": "قیادت کی ترقی",
        "it": "Sviluppo della Leadership", "vi": "Phát triển lãnh đạo", "pl": "Rozwój przywództwa",
    },
    {
        "tr": ["liderlik", "yönetim", "takım"], "en": ["leadership", "manage", "team"],
        "de": ["führung", "management", "team"], "ru": ["лидерство", "управление", "команда"],
        "ar": ["قيادة", "إدارة", "فريق"], "es": ["liderazgo", "gestión", "equipo"],
        "ko": ["리더십", "관리", "팀"], "ja": ["リーダーシップ", "管理", "チーム"],
        "zh": ["领导力", "管理", "团队"], "hi": ["नेतृत्व", "प्रबंधन", "टीम"],
        "fr": ["leadership", "gestion", "équipe"], "pt": ["liderança", "gestão", "equipe"],
        "bn": ["নেতৃত্ব", "ব্যবস্থাপনা", "দল"], "id": ["kepemimpinan", "manajemen", "tim"],
        "ur": ["قیادت", "انتظام", "ٹیم"], "it": ["leadership", "gestione", "team"],
        "vi": ["lãnh đạo", "quản lý", "đội"], "pl": ["przywództwo", "zarządzanie", "zespół"],
    },
    {
        "tr": "Liderlik becerilerinizi geliştirin.",
        "en": "Develop your leadership skills.",
        "de": "Entwickeln Sie Ihre Führungskompetenzen.",
        "ru": "Развивайте свои навыки лидерства.",
        "ar": "طور مهاراتك القيادية.",
        "es": "Desarrolla tus habilidades de liderazgo.",
        "ko": "리더십 기술을 개발하세요.",
        "ja": "リーダーシップスキルを開発します。",
        "zh": "培养您的领导力技能。",
        "hi": "अपने नेतृत्व कौशल विकसित करें।",
        "fr": "Développez vos compétences en leadership.",
        "pt": "Desenvolva suas habilidades de liderança.",
        "bn": "আপনার নেতৃত্ব দক্ষতা বিকাশ করুন।",
        "id": "Kembangkan keterampilan kepemimpinan Anda.",
        "ur": "اپنی قیادت کی مہارت کو بہتر بنائیں۔",
        "it": "Sviluppa le tue competenze di leadership.",
        "vi": "Phát triển kỹ năng lãnh đạo của bạn.",
        "pl": "Rozwijaj swoje umiejętności przywódcze.",
    },
)

# 8. Duygusal (Emotional Intelligence)
COACH_DUYGUSAL = _make_coach_module(
    "duygusal",
    {
        "tr": "Duygusal Zeka", "en": "Emotional Intelligence", "de": "Emotionale Intelligenz",
        "ru": "Эмоциональный интеллект", "ar": "الذكاء العاطفي", "es": "Inteligencia Emocional",
        "ko": "감정 지능", "ja": "感情知能", "zh": "情感智力", "hi": "भावनात्मक बुद्धिमत्ता",
        "fr": "Intelligence Émotionnelle", "pt": "Inteligência Emocional", "bn": "আবেগজনক বুদ্ধিমত্তা",
        "id": "Kecerdasan Emosional", "ur": "جذباتی ذہانت", "it": "Intelligenza Emotiva",
        "vi": "Trí tuệ cảm xúc", "pl": "Inteligencja emocjonalna",
    },
    {
        "tr": ["duygusal", "empati", "duygu"], "en": ["emotion", "empathy", "feeling"],
        "de": ["emotion", "empathie", "gefühl"], "ru": ["эмоция", "сопереживание", "чувство"],
        "ar": ["عاطفة", "تعاطف", "شعور"], "es": ["emoción", "empatía", "sentimiento"],
        "ko": ["감정", "공감", "느낌"], "ja": ["感情", "共感", "気持ち"],
        "zh": ["情感", "同情", "感受"], "hi": ["भावना", "सहानुभूति", "अनुभव"],
        "fr": ["émotion", "empathie", "sentiment"], "pt": ["emoção", "empatia", "sentimento"],
        "bn": ["আবেগ", "সহানুভূতি", "অনুভূতি"], "id": ["emosi", "empati", "perasaan"],
        "ur": ["جذبہ", "ہمدردی", "احساس"], "it": ["emozione", "empatia", "sentimento"],
        "vi": ["cảm xúc", "đồng cảm", "cảm giác"], "pl": ["emocja", "empatia", "uczucie"],
    },
    {
        "tr": "Duygusal zekanızı geliştirebilirsiniz.",
        "en": "Improve your emotional intelligence.",
        "de": "Verbessern Sie Ihre emotionale Intelligenz.",
        "ru": "Улучшите свой эмоциональный интеллект.",
        "ar": "تحسين ذكاؤك العاطفي.",
        "es": "Mejora tu inteligencia emocional.",
        "ko": "감정 지능을 개선하세요.",
        "ja": "感情知能を改善してください。",
        "zh": "提高您的情感智力。",
        "hi": "अपनी भावनात्मक बुद्धिमत्ता में सुधार करें।",
        "fr": "Améliorez votre intelligence émotionnelle.",
        "pt": "Melhore sua inteligência emocional.",
        "bn": "আপনার আবেগজনক বুদ্ধিমত্তা উন্নত করুন।",
        "id": "Tingkatkan kecerdasan emosional Anda.",
        "ur": "اپنی جذباتی ذہانت کو بہتر بنائیں۔",
        "it": "Migliora la tua intelligenza emotiva.",
        "vi": "Cải thiện trí tuệ cảm xúc của bạn.",
        "pl": "Popraw swoją inteligencję emocjonalną.",
    },
)

# 9. Uyum (Compatibility)
COACH_UYUM = _make_coach_module(
    "uyum",
    {
        "tr": "İlişki Uyumu", "en": "Relationship Compatibility", "de": "Beziehungskompatibilität",
        "ru": "Совместимость отношений", "ar": "توافق العلاقات", "es": "Compatibilidad de Relaciones",
        "ko": "관계 호환성", "ja": "関係の互換性", "zh": "关系兼容性",
        "hi": "संबंध अनुकूलता", "fr": "Compatibilité des Relations", "pt": "Compatibilidade de Relacionamento",
        "bn": "সম্পর্ক সামঞ্জস্য", "id": "Kompatibilitas Hubungan", "ur": "رشتے کی موافقت",
        "it": "Compatibilità della Relazione", "vi": "Tính tương thích của mối quan hệ", "pl": "Zgodność związku",
    },
    {
        "tr": ["uyum", "ilişki", "uyumlu"], "en": ["compatible", "relationship", "match"],
        "de": ["kompatibel", "beziehung", "übereinstimmung"], "ru": ["совместимо", "отношение"],
        "ar": ["متوافق", "علاقة"], "es": ["compatible", "relación"], "ko": ["호환성", "관계"],
        "ja": ["互換性", "関係"], "zh": ["兼容", "关系"], "hi": ["अनुकूल", "संबंध"],
        "fr": ["compatible", "relation"], "pt": ["compatível", "relacionamento"],
        "bn": ["সামঞ্জস্যপূর্ণ", "সম্পর্ক"], "id": ["kompatibel", "hubungan"],
        "ur": ["موافق", "رشتہ"], "it": ["compatibile", "relazione"], "vi": ["tương thích", "mối quan hệ"],
        "pl": ["kompatybilny", "związek"],
    },
    {
        "tr": "İlişkilerinizde uyum bulun.",
        "en": "Find compatibility in your relationships.",
        "de": "Finden Sie Kompatibilität in Ihren Beziehungen.",
        "ru": "Найдите совместимость в ваших отношениях.",
        "ar": "ابحث عن التوافق في علاقاتك.",
        "es": "Encuentra compatibilidad en tus relaciones.",
        "ko": "관계에서 호환성을 찾으세요.",
        "ja": "あなたの関係の互換性を見つけてください。",
        "zh": "在您的关系中找到兼容性。",
        "hi": "अपने संबंधों में अनुकूलता खोजें।",
        "fr": "Trouvez la compatibilité dans vos relations.",
        "pt": "Encontre compatibilidade em seus relacionamentos.",
        "bn": "আপনার সম্পর্কে সামঞ্জস্য খুঁজুন।",
        "id": "Temukan kompatibilitas dalam hubungan Anda.",
        "ur": "اپنے رشتوں میں موافقت تلاش کریں۔",
        "it": "Trova compatibilità nelle tue relazioni.",
        "vi": "Tìm sự tương thích trong các mối quan hệ của bạn.",
        "pl": "Znajdź zgodność w swoich związkach.",
    },
)

# 10. Beceri (Skills)
COACH_BECERI = _make_coach_module(
    "beceri",
    {
        "tr": "Beceri Gelişimi", "en": "Skill Development", "de": "Skillentwicklung",
        "ru": "Развитие навыков", "ar": "تطوير المهارات", "es": "Desarrollo de Habilidades",
        "ko": "기술 개발", "ja": "スキル開発", "zh": "技能发展", "hi": "कौशल विकास",
        "fr": "Développement des Compétences", "pt": "Desenvolvimento de Habilidades",
        "bn": "দক্ষতা উন্নয়ন", "id": "Pengembangan Keterampilan", "ur": "ہنر کی ترقی",
        "it": "Sviluppo delle Competenze", "vi": "Phát triển kỹ năng", "pl": "Rozwój umiejętności",
    },
    {
        "tr": ["beceri", "yetenek", "gelişim"], "en": ["skill", "ability", "develop"],
        "de": ["fertigkeit", "fähigkeit", "entwicklung"], "ru": ["навык", "способность", "развитие"],
        "ar": ["مهارة", "قدرة", "تطوير"], "es": ["habilidad", "capacidad", "desarrollo"],
        "ko": ["기술", "능력", "개발"], "ja": ["スキル", "能力", "開発"],
        "zh": ["技能", "能力", "发展"], "hi": ["कौशल", "क्षमता", "विकास"],
        "fr": ["compétence", "capacité", "développement"], "pt": ["habilidade", "capacidade", "desenvolvimento"],
        "bn": ["দক্ষতা", "ক্ষমতা", "উন্নয়ন"], "id": ["keterampilan", "kemampuan", "pengembangan"],
        "ur": ["ہنر", "صلاحیت", "ترقی"], "it": ["competenza", "capacità", "sviluppo"],
        "vi": ["kỹ năng", "khả năng", "phát triển"], "pl": ["umiejętność", "zdolność", "rozwój"],
    },
    {
        "tr": "Becerilerinizi geliştirmek için öneriler.",
        "en": "Recommendations to develop your skills.",
        "de": "Empfehlungen zur Entwicklung Ihrer Fähigkeiten.",
        "ru": "Рекомендации по развитию ваших навыков.",
        "ar": "توصيات لتطوير مهاراتك.",
        "es": "Recomendaciones para desarrollar tus habilidades.",
        "ko": "기술 개발을 위한 권장 사항.",
        "ja": "スキルを開発するための推奨事項。",
        "zh": "开发您的技能的建议。",
        "hi": "अपनी कौशल विकास के लिए सिफारिशें।",
        "fr": "Recommandations pour développer vos compétences.",
        "pt": "Recomendações para desenvolver suas habilidades.",
        "bn": "আপনার দক্ষতা উন্নয়নের জন্য সুপারিশ।",
        "id": "Rekomendasi untuk mengembangkan keterampilan Anda.",
        "ur": "اپنی مہارت تیاری کے لیے سفارشات۔",
        "it": "Raccomandazioni per sviluppare le tue competenze.",
        "vi": "Gợi ý để phát triển kỹ năng của bạn.",
        "pl": "Rekomendacje w celu rozwijania umiejętności.",
    },
)

# 11. IK (HR/Work)
COACH_IK = _make_coach_module(
    "ik",
    {
        "tr": "İK & Kariyer", "en": "HR & Career", "de": "Personalwesen & Karriere",
        "ru": "HR и карьера", "ar": "الموارد البشرية والمهنة", "es": "RRHH y Carrera",
        "ko": "HR & 경력", "ja": "HR&キャリア", "zh": "人力资源与职业",
        "hi": "एचआर और करियर", "fr": "RH et Carrière", "pt": "RH & Carreira",
        "bn": "মানব সম্পদ এবং ক্যারিয়ার", "id": "HR & Karir", "ur": "HR اور کیریئر",
        "it": "HR & Carriera", "vi": "Nhân sự & Sự nghiệp", "pl": "HR i kariera",
    },
    {
        "tr": ["hr", "kariyer", "iş"], "en": ["hr", "career", "job"],
        "de": ["personalwesen", "karriere"], "ru": ["hr", "карьера", "работа"],
        "ar": ["موارد", "مهنة", "وظيفة"], "es": ["rrhh", "carrera", "trabajo"],
        "ko": ["hr", "경력", "직업"], "ja": ["HR", "キャリア", "仕事"],
        "zh": ["人力资源", "职业", "工作"], "hi": ["एचआर", "करियर", "काम"],
        "fr": ["rh", "carrière", "emploi"], "pt": ["rh", "carreira", "trabalho"],
        "bn": ["মানব", "ক্যারিয়ার", "কাজ"], "id": ["hr", "karir", "pekerjaan"],
        "ur": ["hr", "کیریئر", "کام"], "it": ["hr", "carriera", "lavoro"],
        "vi": ["nhân sự", "sự nghiệp", "công việc"], "pl": ["hr", "kariera", "praca"],
    },
    {
        "tr": "Kariyer ve iş yaşamı önerileri.",
        "en": "Career and workplace advice.",
        "de": "Karriere- und Arbeitsplatzberatung.",
        "ru": "Советы по карьере и рабочему месту.",
        "ar": "نصائح الحياة المهنية والعملية.",
        "es": "Consejos de carrera y lugar de trabajo.",
        "ko": "경력 및 직장 조언.",
        "ja": "キャリアおよび職場のアドバイス。",
        "zh": "职业和工作场所建议。",
        "hi": "करियर और कार्यस्थल सलाह।",
        "fr": "Conseils de carrière et de lieu de travail.",
        "pt": "Conselhos de carreira e local de trabalho.",
        "bn": "ক্যারিয়ার এবং কর্মক্ষেত্র পরামর্শ।",
        "id": "Saran karir dan tempat kerja.",
        "ur": "کیریئر اور کام کی جگہ کی سلاہ۔",
        "it": "Consigli su carriera e luogo di lavoro.",
        "vi": "Lời khuyên về sự nghiệp và nơi làm việc.",
        "pl": "Porady dotyczące kariery i miejsca pracy.",
    },
)

# 12. Kariyer (Career - supplementary)
COACH_KARIYER = _make_coach_module(
    "kariyer",
    {
        "tr": "Kariyer Planlama", "en": "Career Planning", "de": "Karriereplanung",
        "ru": "Карьерное планирование", "ar": "تخطيط المهنة", "es": "Planificación de Carrera",
        "ko": "경력 계획", "ja": "キャリア計画", "zh": "职业规划", "hi": "करियर योजना",
        "fr": "Planification de Carrière", "pt": "Planejamento de Carreira", "bn": "ক্যারিয়ার পরিকল্পনা",
        "id": "Perencanaan Karir", "ur": "کیریئر کی منصوبہ بندی", "it": "Pianificazione della Carriera",
        "vi": "Lập kế hoạch sự nghiệp", "pl": "Planowanie kariery",
    },
    {
        "tr": ["kariyer", "plan", "hedef"], "en": ["career", "plan", "goal"],
        "de": ["karriere", "plan", "ziel"], "ru": ["карьера", "план", "цель"],
        "ar": ["مهنة", "خطة", "هدف"], "es": ["carrera", "plan", "objetivo"],
        "ko": ["경력", "계획", "목표"], "ja": ["キャリア", "計画", "目標"],
        "zh": ["职业", "计划", "目标"], "hi": ["करियर", "योजना", "लक्ष्य"],
        "fr": ["carrière", "plan", "objectif"], "pt": ["carreira", "plano", "objetivo"],
        "bn": ["ক্যারিয়ার", "পরিকল্পনা", "লক্ষ্য"], "id": ["karir", "rencana", "tujuan"],
        "ur": ["کیریئر", "منصوبہ", "مقصد"], "it": ["carriera", "piano", "obiettivo"],
        "vi": ["sự nghiệp", "kế hoạch", "mục tiêu"], "pl": ["kariera", "plan", "cel"],
    },
    {
        "tr": "Kariyer yolunuzu planlayın.",
        "en": "Plan your career path.",
        "de": "Planen Sie Ihren Karriereweg.",
        "ru": "Спланируйте свой путь карьеры.",
        "ar": "خطط لمسار حياتك المهنية.",
        "es": "Planifica tu trayectoria profesional.",
        "ko": "경력 경로를 계획하세요.",
        "ja": "キャリアパスを計画してください。",
        "zh": "规划您的职业生涯。",
        "hi": "अपने करियर पथ की योजना बनाएं।",
        "fr": "Planifiez votre cheminement professionnel.",
        "pt": "Planeje seu caminho de carreira.",
        "bn": "আপনার ক্যারিয়ার পথ পরিকল্পনা করুন।",
        "id": "Rencanakan jalur karir Anda.",
        "ur": "اپنے کیریئر کا راستہ منصوبہ بندی کریں۔",
        "it": "Pianifica il tuo percorso di carriera.",
        "vi": "Lên kế hoạch cho con đường sự nghiệp của bạn.",
        "pl": "Zaplanuj swoją ścieżkę kariery.",
    },
)

# ──────────────────────────────────────────────────────────────────────────
# All modules list (updated with 20 modules total)
# ──────────────────────────────────────────────────────────────────────────

ALL_MODULES = [
    ASTROLOGY,
    TEST_PERSONALITY,
    TEST_CAREER,
    TEST_HR,
    TEST_SKILLS,
    TEST_VOCATION,
    TEST_RELATIONSHIP,
    FACE_ANALYSIS,
    COACH_TAVSIYE,
    COACH_MOTIVASYON,
    COACH_ETKINLIK,
    COACH_MUZIK,
    COACH_FILM_DIZI,
    COACH_GIYIM,
    COACH_LIDERLIK,
    COACH_DUYGUSAL,
    COACH_UYUM,
    COACH_BECERI,
    COACH_IK,
    COACH_KARIYER,
]
